### ISSUE TITLE
[Bug]: error during installing directml "AttributeError: module 'torch' has no attribute 'ops'"

### ISSUE THREAD

**Issue by ride5k** [lshqqytiger/stable-diffusion-webui-directml#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

venv "T:\auto1111\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Installing DirectML
Traceback (most recent call last):
  File "T:\auto1111\stable-diffusion-webui-directml\launch.py", line 354, in <module>
    prepare_environment()
  File "T:\auto1111\stable-diffusion-webui-directml\launch.py", line 227, in prepare_environment
    import torch_directml
  File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch_directml\__init__.py", line 13, in <module>
    torch.ops.load_library(directml_dll)
AttributeError: module 'torch' has no attribute 'ops'

### Steps to reproduce the problem

launch webui-user after pulling latest commit

### What should have happened?

directml should have installed

### Commit where the problem happens

5e1d799

### What platforms do you use to access the UI ?

Windows

### Command Line Arguments

```Shell
no
```

### List of extensions

no

### Console logs

```Shell
env "T:\auto1111\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Installing DirectML
Traceback (most recent call last):
  File "T:\auto1111\stable-diffusion-webui-directml\launch.py", line 354, in <module>
    prepare_environment()
  File "T:\auto1111\stable-diffusion-webui-directml\launch.py", line 227, in prepare_environment
    import torch_directml
  File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch_directml\__init__.py", line 13, in <module>
    torch.ops.load_library(directml_dll)
AttributeError: module 'torch' has no attribute 'ops'
Press any key to continue . . .
```

**Comment by lshqqytiger** [comment]
Can't reproduce.
Uninstall `torch` and `torch-directml` and try again.
```
$ pip uninstall torch torch-directml
$ python launch.py ... (or .\webui-user.bat)
```

**Comment by songib** [comment]
similar problem to me



> Can't reproduce. Uninstall `torch` and `torch-directml` and try again.
> 
> ```
> $ pip uninstall torch torch-directml
> $ python launch.py ... (or .\webui-user.bat)
> ```

Ahh thanks sir, have a good day.

**Comment by lshqqytiger** [comment]
> it launch using "launch.py" but when using webui.bat it broke again with the same error. is it corrupted bat file or something?

I have not used webui.bat actually.
I always activate venv using anaconda -> run `python launch.py ...`

> and since its launches without the commandline_args, I can't use it "RuntimeError: Could not allocate tensor with 1207959552
bytes. There is not enough GPU video memory available!
Time taken: 4.74s"

You can attach commandline arguments like `python launch.py --no-half --opt-...`

> and it use (torch: 2.0.0+cpu), is this fine for AMD?

Because ROCm for Windows did not release yet, we use torch for cpu + torch-directml.

> Update: try to instal the requirement and requirement version and it had this stuff, is this ok?

I have experienced same stuff on vladmandic/automatic. It occurred once and never occurred again.

**Comment by ride5k** [comment]
shqqytiger, i have circumvented the issue by reinstalling the fork entirely.  after a few restarts of webui (to clean up installs/upgrades/dependencies) i can successfully launch and generate images.

i appreciate the responses, but i have found that a fresh install is usually the best place to start! :)

**Comment by songib** [comment]
> l

i want to try this, did you do the backup first or just yolo?
i don't want to download all the models and extensions again.

**Comment by lshqqytiger** [comment]
When you ran `python launch.py` directly, did you activate virtual environment?

**Comment by songib** [comment]
@lshqqytiger nope.
if I reinstall this repo, will I lose all the settings and other stuff like model and extension?
should I just use "launch.py" from now on or backup all the models and extensions and reinstall the repo?

**Comment by lshqqytiger** [comment]
webui.bat activates venv.
Remove venv folder and run webui-user.bat again.

**Comment by songib** [comment]
> webui.bat activates venv. Remove venv folder and run webui-user.bat again.

ok ill try it.

**Comment by ride5k** [comment]
> @ride5k
> 
> i want to try this, did you do the backup first or just yolo? i don't want to download all the models and extensions again.

very easy to rename existing directory, then reinstall.  once up and running copy/move contents (models and extensions) of renamed directory to your new folder.  no redownload of the big stuff is necessary!
