### ISSUE TITLE
[Bug]: Massive slowdown after first image

### ISSUE THREAD

**Issue by aellul27** [lshqqytiger/stable-diffusion-webui-directml#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

After the first image, there is a massive slowdown, going from 10it/s to 90it/s. I'm on Windows 11, using the latest commit on Intel Iris Xe.

### Steps to reproduce the problem

1. Launch stable-diffusion-webui
2. Generate an image
3. Try generating a second image

### What should have happened?

Speed is maintained between images.

### Commit where the problem happens

b2f7f88a6b7f811a14df9fd4e350c76e6fd3e04a

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--lowvram
```

### List of extensions

No

### Console logs

```Shell
D:\stable-diffusion-webui-directml>webui-user.bat
venv "D:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: c88824995d87be36a62b110dd509ff7ccb6eeaa2
Installing requirements for Web UI
Launching Web UI with arguments: --lowvram
Warning: experimental graphic memory optimization is disabled due to gpu vendor. Currently this optimization is only available for AMDGPUs.
Disabled experimental graphic memory optimizations.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [e4b17ce185] from D:\stable-diffusion-webui-directml\models\Stable-diffusion\anything-v4.5-pruned.ckpt
Creating model from config: D:\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 93.9s (load weights from disk: 84.4s, create model: 1.3s, apply weights to model: 4.9s, apply half(): 2.5s, load VAE: 0.1s, hijack: 0.1s, load textual inversion embeddings: 0.4s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
 70%|█████████████████████████████████████████████████████████▍                        | 14/20 [03:44<01:36, 16.07s/it]
Total progress:  70%|██████████████████████████████████████████████▏                   | 14/20 [03:47<01:37, 16.25s/it]
 10%|████████▎                                                                          | 2/20 [03:09<28:53, 96.30s/it]
```

**Comment by SpyderMoHawK** [comment]
Can report that i have the same issue on my 7900 XT
For some reason it uses initially 13,7GB VRAM right away and adds another 2GB for each new image is completed.
When it reaches 80% usage of VRAM the performance of the application slow's down to a crawl.
This is when i uses no prompts, 20 sampling steps with resolution 512x512 and only 1 image at a time.
So somewhere it saves the completed image into VRAM and doesn't clear it at any time unless you close the CMD window.

![image](https://user-images.githubusercontent.com/24485594/220709266-242996ed-e9f7-487d-9930-d41f48591830.png)
![image](https://user-images.githubusercontent.com/24485594/220709573-b4999886-4987-4394-ae20-07e589cdd693.png)

**Comment by felixHerder** [comment]
Had the same issue with an RX 6600 8gb, adding the `--opt-split-attention` cmd arg fixed it. 

I also use: `--medvram  --disable-nan-check --opt-sub-quad-attention --no-half --precission full`, getting around 1.5 it/s at 512x512.

**Comment by aveeeteeeeee2** [comment]
Having this issue too

**Comment by lshqqytiger** [comment]
It's because DirectML doesn't return used memory and we can't empty memory on DirectML device using some features provided by PyTorch for now.

**Comment by webmilio** [comment]
Having this as well!

**Comment by revons1984** [comment]
I'm having this same issue on a 7900xtx.  Using windows and firefox, no command line arguments. First picture I can run 150 steps at 768x512 in about 5 seconds and then it's mega slow for the second attempt and ones after. If I close the Command window and open webui-user.bat while leaving the browser open it's fast again but after a handful of doing this it's slower and slower until I close both the cmd window and firefox (including task manager if need be) and then it's fast again for another round of this until I need to reboot my computer to gain the speed again.
