### ISSUE TITLE
[Bug]: swinir_4x upscaler is not on the list of upscalers  , please help

### ISSUE THREAD

**Issue by doctord98618** [lshqqytiger/stable-diffusion-webui-directml#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

after the update, extras upscaler swinir_4x is not there at its usual place, I cannot find it

### Steps to reproduce the problem

1. open stable diffusion
2. go to extras, swinir_4x is not there
3. ...

### What should have happened?

it should have been on the list

### Commit where the problem happens

recent

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
no
```

### List of extensions

swinir_4x is built in, its is not working, not other extension

### Console logs

```Shell
x
```

**Comment by Bu11ism** [comment]
Possible work around: 

Go to the "Extension"s tab
Set "Disable all extensions" from "none" to "extra"
Click "Apply and restart UI"
