### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Aternix12** [lshqqytiger/stable-diffusion-webui-directml#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Just bought a new AMD GPU RX 7900 XT, with the hopes of impoving AI render times over my ancient 900 series NVidia card. 
I did find out the hard way that this fork is the only version with AMD support. 

### Steps to reproduce the problem

I am using a clean clone using `git clone https://github.com/lshqqytiger/stable-diffusion-webui-directml && cd stable-diffusion-webui-directml && git submodule init && git submodule update`

This occurs on every clean install when I run web-ui or webuser.bat: 
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/27490476/c7176308-d40f-4ccb-8119-34ec3cae6b1a)

I am running Python 3.10.6, Windows 10.

### What should have happened?

Normal behavior: All packages get installed and the service is hosted

### Commit where the problem happens

108ada8

### Command Line Arguments

```Shell
None so far
```

### List of extensions

Not yet, but I will be using deforum

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: 108ada8334e7ac96c86ad847561337b4e401ca85
Installing torch and torchvision
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/cu118/torchaudio-2.0.2%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
ERROR: Could not find a version that satisfies the requirement torch-directml (from versions: none)
ERROR: No matching distribution found for torch-directml

[notice] A new release of pip available: 22.2.1 -> 23.1.2
[notice] To update, run: E:\stable-diffusion-webui-directml\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-directml\launch.py", line 371, in <module>
    prepare_environment()
  File "E:\stable-diffusion-webui-directml\launch.py", line 278, in prepare_environment
    run(f'"{python}" -m pip install {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "E:\stable-diffusion-webui-directml\launch.py", line 96, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "E:\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install torch torchaudio torchvision torch-directml --index-url https://download.pytorch.org/whl/cu118
Error code: 1
Press any key to continue . . .
```

**Comment by JJGall** [comment]
Might be similar to this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/111#issuecomment-1537640669

Try deleting anything related to Nvidia, drivers, etc. Use DDU or some other software to remove anything related to the old GPU drivers.

**Comment by Aternix12** [comment]
> Might be similar to this issue: [#111 (comment)](https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/111#issuecomment-1537640669)
> 
> Try deleting anything related to Nvidia, drivers, etc. Use DDU or some other software to remove anything related to the old GPU drivers.

That worked, I overlooked the simple solution. After deleting venv it, relaunching detected it wasn't able to use CUDA and installed with no issues. Thankyou :)
