### ISSUE TITLE
Torch-directml requirement not satisfied [Bug]: 

### ISSUE THREAD

**Issue by bspam11** [lshqqytiger/stable-diffusion-webui-directml#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I'm trying to install this for the first time and I ended up with the following error:
`Installing torch and torchvision
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/cu118/torchaudio-2.0.2%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
ERROR: Could not find a version that satisfies the requirement torch-directml (from versions: none)
ERROR: No matching distribution found for torch-directml
WARNING: There was an error checking the latest version of pip.
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-directml\launch.py", line 371, in <module>
    prepare_environment()
  File "C:\stable-diffusion-webui-directml\launch.py", line 278, in prepare_environment
    run(f'"{python}" -m pip install {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "C:\stable-diffusion-webui-directml\launch.py", line 96, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "C:\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install torch torchaudio torchvision torch-directml --index-url https://download.pytorch.org/whl/cu118
Error code: 1
Press any key to continue . . .`

### Steps to reproduce the problem

1. Installed stable-diffusion-webui-directml using the cmd prompt.
2. Opened openui-user.bat
3. Let the program load on it's own.

### What should have happened?

It should've ran just fine?

### Commit where the problem happens

I don't know what a commit is?

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
venv "C:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: 3f52b28025efbc52c2a745d34bc7ed37710c7a1c
Installing torch and torchvision
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/cu118/torchaudio-2.0.2%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
ERROR: Could not find a version that satisfies the requirement torch-directml (from versions: none)
ERROR: No matching distribution found for torch-directml
WARNING: There was an error checking the latest version of pip.
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-directml\launch.py", line 371, in <module>
    prepare_environment()
  File "C:\stable-diffusion-webui-directml\launch.py", line 278, in prepare_environment
    run(f'"{python}" -m pip install {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "C:\stable-diffusion-webui-directml\launch.py", line 96, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "C:\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install torch torchaudio torchvision torch-directml --index-url https://download.pytorch.org/whl/cu118
Error code: 1
Press any key to continue . . .
```

**Comment by JJGall** [comment]
Did you recently switch from Nvidia to AMD? You need to get rid of all Nvidia drivers, files, etc.  Then delete venv folder and relaunch.

**Comment by lshqqytiger** [comment]
Related: #123 #111

**Comment by lshqqytiger** [comment]
I added `--backend` argument. If this issue still exists, add `--backend directml` and try again.
