### ISSUE TITLE
[Bug]: Error code: 1 after pull request

### ISSUE THREAD

**Issue by VeteranXT** [lshqqytiger/stable-diffusion-webui-directml#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Started webui-user.bat

### Steps to reproduce the problem

Pressed webui-user.bat to start server

### What should have happened?

Created server to use graphic card on local area

### Commit where the problem happens

 9aa5e66

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
None
```

### List of extensions

None (reinstalled)

### Console logs

```Shell
E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl>git pull
Already up to date.
venv "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Version: <none>
Commit hash: f158f1032fd2e977cc884328a942c6ea0a6a06c5
Installing torch and torchvision
E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\venv\Scripts\python.exe: Error while finding module specification for 'torch==2.0.0' (ModuleNotFoundError: No module named 'torch==2')
Traceback (most recent call last):
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\launch.py", line 37, in <module>
    main()
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\launch.py", line 29, in main
    prepare_environment()
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\modules\launch_utils.py", line 257, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\modules\launch_utils.py", line 102, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\venv\Scripts\python.exe" -m torch==2.0.0 torchvision==0.15.1 torch-directml
Error code: 1
Press any key to continue . . .
```

**Comment by hkpD** [comment]
I think it may have something to do with the requirements calling torch==2.0.0 or something. I'm not a programmer at all but I think

**Comment by VeteranXT** [comment]
Well i did delete whole repo and git clone it. Got same results.
After i've updated repo i got this error.

**Comment by VeteranXT** [comment]
It installs fine form Autoamtic111 but here it throws error when installing

**Comment by hkpD** [comment]
What do you mean? I thought we couldn't use the regular Automatic1111 repository and we specifically had to wait on this repository to merge with it. 

Can I just go download the latest zip from Automatic1111 and it will work?

**Comment by VeteranXT** [comment]
Thing is it works slow with automatic111 with me, it wont generate fast enough with.
DirectTM works fine for 256x256 using SDmini model. That is what i've been using on RX  6600 XT GP.
It sometimes throws out of memory error but most of time just straight out wont give any results. 
Main reason i used this is support for AMD. With this repo i can do about 10x times faster than automatic.

Currently installing requirments and imma transfer model to automatic111 and see if it works.

**Comment by lshqqytiger** [comment]
Something went wrong while merging upstream commits.
Some contents of launch.py moved to `modules/launch_utils.py` and changed a bit little.
I missed `pip install ` while resolving conflicts.
I pushed a commit solving this issue and installation should be work now.

**Comment by VeteranXT** [comment]
Thanks!

**Comment by hkpD** [comment]
Thank you so much! We appreciate all of your hard work
