### ISSUE TITLE
[Bug]: No Idead, something with DirectML or K-Diffusion

### ISSUE THREAD

**Issue by Rizzlord** [lshqqytiger/stable-diffusion-webui-directml#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I had updated my DirectML, and now nothing works anymore.

### Steps to reproduce the problem

1. use the web-user.bat

### What should have happened?

it should open the Web-UI

### Commit where the problem happens

web-user.bat

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 5000 below)

### Command Line Arguments

```Shell
has nothing to do with the error
```

### List of extensions

has nothing to do with the error

### Console logs

```Shell
Already up to date.
venv "C:\Users\mull9\Documents\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: f158f1032fd2e977cc884328a942c6ea0a6a06c5
Fetching updates for K-diffusion...
Checking out commit for K-diffusion with hash: c9fe758757e022f05ca5a53fa8fac28889e4f1cf...
Traceback (most recent call last):
  File "C:\Users\mull9\Documents\stable-diffusion-webui-directml\launch.py", line 37, in <module>
    main()
  File "C:\Users\mull9\Documents\stable-diffusion-webui-directml\launch.py", line 29, in main
    prepare_environment()
  File "C:\Users\mull9\Documents\stable-diffusion-webui-directml\modules\launch_utils.py", line 287, in prepare_environment
    git_clone(k_diffusion_repo, repo_dir('k-diffusion'), "K-diffusion", k_diffusion_commit_hash)
  File "C:\Users\mull9\Documents\stable-diffusion-webui-directml\modules\launch_utils.py", line 145, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "C:\Users\mull9\Documents\stable-diffusion-webui-directml\modules\launch_utils.py", line 102, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't checkout commit c9fe758757e022f05ca5a53fa8fac28889e4f1cf for K-diffusion.
Command: "git" -C "C:\Users\mull9\Documents\stable-diffusion-webui-directml\repositories\k-diffusion" checkout c9fe758757e022f05ca5a53fa8fac28889e4f1cf
Error code: 128
stderr: fatal: reference is not a tree: c9fe758757e022f05ca5a53fa8fac28889e4f1cf

Drücken Sie eine beliebige Taste . . .
```

**Comment by lshqqytiger** [comment]
This is what I expected. I changed repository of submodules. They are no longer mine.
Remove `repositories\k-diffusion` and `repositories\stable-diffusion-stability-ai`, and try again.

**Comment by Rizzlord** [comment]
it works again... but was it because i updated DirectML? Need explanation so i wont do something stupid again^^

**Comment by lshqqytiger** [comment]
I realized this after I pushed commits 😭 I'm sorry I made you confused.
I think I can write an announcement on GitHub discussions.
I'm not familiar with discussions yet..
