### ISSUE TITLE
[Bug]: Launch fail with the latest git pull

### ISSUE THREAD

**Issue by dieselino0** [lshqqytiger/stable-diffusion-webui-directml#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When you click on webui-user.bat with git pull it breaks with the latest update, here is the error

`D:\AUTOMATIC1111\stable-diffusion-webui-directml>git pull
Already up to date.
venv "D:\AUTOMATIC1111\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: 8f1287355426216eb24332a64f9b4bf44256c699
Fetching updates for Stable Diffusion...
Checking out commit for Stable Diffusion with hash: cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf...
Traceback (most recent call last):
  File "D:\AUTOMATIC1111\stable-diffusion-webui-directml\launch.py", line 38, in <module>
    main()
  File "D:\AUTOMATIC1111\stable-diffusion-webui-directml\launch.py", line 29, in main
    prepare_environment()
  File "D:\AUTOMATIC1111\stable-diffusion-webui-directml\modules\launch_utils.py", line 285, in prepare_environment
    git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
  File "D:\AUTOMATIC1111\stable-diffusion-webui-directml\modules\launch_utils.py", line 145, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "D:\AUTOMATIC1111\stable-diffusion-webui-directml\modules\launch_utils.py", line 102, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't checkout commit cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf for Stable Diffusion.
Command: "git" -C "D:\AUTOMATIC1111\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai" checkout cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf
Error code: 128
stderr: fatal: reference is not a tree: cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf

Press any key to continue . . .`

### Steps to reproduce the problem

1. Launch the webui
2. Git pull is enabled 
3. Fails to update and also fails to launch if you reload

### What should have happened?

It should have opened normally without any issues

### Commit where the problem happens

8f1287355426216eb24332a64f9b4bf44256c699

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--opt-sub-quad-attention --no-half
```

### List of extensions

None

### Console logs

```Shell
D:\AUTOMATIC1111\stable-diffusion-webui-directml>git pull
Already up to date.
venv "D:\AUTOMATIC1111\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: 8f1287355426216eb24332a64f9b4bf44256c699
Fetching updates for Stable Diffusion...
Checking out commit for Stable Diffusion with hash: cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf...
Traceback (most recent call last):
  File "D:\AUTOMATIC1111\stable-diffusion-webui-directml\launch.py", line 38, in <module>
    main()
  File "D:\AUTOMATIC1111\stable-diffusion-webui-directml\launch.py", line 29, in main
    prepare_environment()
  File "D:\AUTOMATIC1111\stable-diffusion-webui-directml\modules\launch_utils.py", line 285, in prepare_environment
    git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
  File "D:\AUTOMATIC1111\stable-diffusion-webui-directml\modules\launch_utils.py", line 145, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "D:\AUTOMATIC1111\stable-diffusion-webui-directml\modules\launch_utils.py", line 102, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't checkout commit cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf for Stable Diffusion.
Command: "git" -C "D:\AUTOMATIC1111\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai" checkout cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf
Error code: 128
stderr: fatal: reference is not a tree: cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf

Press any key to continue . . .
```

**Comment by ladydarkness** [comment]
I had this error, so with some research I found a solution, I went to repositories folder, deleted k-diffusion and taming-transformers and then launched again, then the launcher downloaded it again, it worked here.

**Comment by ride5k** [comment]
i too have this issue.  unfortunately @ladydarkness suggestion did not work to resolve.

**Comment by dieselino0** [comment]
> I had this error, so with some research I found a solution, I went to the repositories folder, deleted k-diffusion and taming-transformers and then launched again, then the launcher downloaded it again, it worked here.

doesn't work for me, still same error, thanks anyways though

**Comment by islam0talha** [comment]
changing the commit hash in line 242 in \modules\launch_utils.py
`k_diffusion_commit_hash = os.environ.get('K_DIFFUSION_COMMIT_HASH', "47b6ef08bca986ff5e72815e74a419ef6616bdbb")`
to the latest commit of \repositories\k-diffusion repo 
`k_diffusion_commit_hash = os.environ.get('K_DIFFUSION_COMMIT_HASH', "c9fe758757e022f05ca5a53fa8fac28889e4f1cf")`
worked for me.

**Comment by dieselino0** [comment]
> changing the commit hash in line 242 in \modules\launch_utils.py `k_diffusion_commit_hash = os.environ.get('K_DIFFUSION_COMMIT_HASH', "47b6ef08bca986ff5e72815e74a419ef6616bdbb")` to the latest commit of \repositories\k-diffusion repo `k_diffusion_commit_hash = os.environ.get('K_DIFFUSION_COMMIT_HASH', "c9fe758757e022f05ca5a53fa8fac28889e4f1cf")` worked for me.

can you tell me what your stable_diffusion_commit_hash = os.environ.get is?

**Comment by dieselino0** [comment]
I got it working, I had to delete **stable-diffusion-stability-ai, k-diffusion and taming-transformers folders** in the **repositories folder**, once I did that I relaunched and it downloaded the new files

**Comment by ladydarkness** [comment]
> I got it working, I had to delete **stable-diffusion-stability-ai**, **k-diffusion** and **taming-transformers** folders located in the **repositories folder**, once I did that I relaunched and it downloaded the new files

Nice, in my case I had to delete just k-diffusion** and **taming-transformers**

**Comment by dieselino0** [comment]
> > I got it working, I had to delete **stable-diffusion-stability-ai**, **k-diffusion** and **taming-transformers** folders located in the **repositories folder**, once I did that I relaunched and it downloaded the new files
> 
> Nice, in my case I had to delete just **k-diffusion** and **taming-transformers**

thank you for your suggestion, that helped for sure

**Comment by sgtsixpack** [comment]
I followed this fix and now my pictures are not generating correctly just mainly noise (although I can run the GUI now).

**Comment by dieselino0** [comment]
> I followed this fix and now my pictures are not generating correctly just mainly noise (although I can run the GUI now). I've tried redownloading the whole lot to no avail. I think once you have a working directory - only update a copy!

https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/133

**Comment by Kaztigo** [comment]
I´ve tried all solutions posted on top, sadly non of them worked. My repositories is a bit different I think,  I have 4 folders there wich are BLIP, Code Former, k-Diffusion and stable-diffusion-stability-ai. Anything else I can try?
