### ISSUE TITLE
[Bug]: launch_utils.py should not assume 'GIT' environment variable to point to a git binary

### ISSUE THREAD

**Issue by ztx-lyghters** [lshqqytiger/stable-diffusion-webui-directml#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

`launch_utils.py` uses the contents of a 'GIT' environment variable, which in my case is set to a custom path and points to a directory. I am unable to find any 'GIT' reservation:
https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables
I also have never stumbled upon any script or software which used this variable, this is a first time I'm having this issue in about 4 years. Hence, I view this as a mistake.

### Steps to reproduce the problem

1. Clone the repo
2. Initialize and update submodules
3. Have GIT environment variable point to something else than git binary
4. Run the ./webui.sh

### What should have happened?

Script should have found the git binary instead

### Commit where the problem happens

8f12873

### What Python version are you running on ?

Python 3.11.x (above, no supported yet)

### What platforms do you use to access the UI ?

Linux

### Command Line Arguments

```Shell
No additional arguments or modifications
```

### List of extensions

No

### Console logs

```Shell
Cloning Stable Diffusion into /home/ztx/stuff/git/stable-diffusion-webui-directml/repositories/stable-diffusion-stability-ai...
Traceback (most recent call last):
  File "/home/ztx/stuff/git/stable-diffusion-webui-directml/launch.py", line 38, in <module>
    main()
  File "/home/ztx/stuff/git/stable-diffusion-webui-directml/launch.py", line 29, in main
    prepare_environment()
  File "/home/ztx/stuff/git/stable-diffusion-webui-directml/modules/launch_utils.py",
line 285, in prepare_environment
    git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
  File "/home/ztx/stuff/git/stable-diffusion-webui-directml/modules/launch_utils.py",
line 148, in git_clone
    run(f'"{git}" clone "{url}" "{dir}"', f"Cloning {name} into {dir}...", f"Couldn't
clone {name}")
  File "/home/ztx/stuff/git/stable-diffusion-webui-directml/modules/launch_utils.py",
line 102, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't clone Stable Diffusion.
Command: "/home/ztx/stuff/git" clone "https://github.com/Stability-AI/stablediffusion.git" "/home/ztx/stuff/git/stable-diffusion-webui-directml/repositories/stable-diffusion-stability-ai"
Error code: 126
stderr: /bin/sh: 1: /home/ztx/stuff/git: Permission denied
```

**Comment by ztx-lyghters** [comment]
A late thought:
Should I move this issue to upstream instead?

**Comment by lshqqytiger** [comment]
I think so. Does this problem still exist?
