### ISSUE TITLE
[Bug]: Embeddings aren't understood/processed correctly by SD

### ISSUE THREAD

**Issue by LappIand** [lshqqytiger/stable-diffusion-webui-directml#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Even after the new merge, I kept getting neon images for genuine prompts... 

I have discovered this is due to my embeddings yet I haven't found an embedding which would work.
Without these embeddings I was getting normal images but with obvious flaws.

### Steps to reproduce the problem

1. Load in an embedding of your choice
2. Generate an image (preferably with a prompt that gave you a good image before )
3. You'll see neon images and or massive artifacts

### What should have happened?

![00000-2328796512](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/68433453/0625cfe6-b67b-493b-acca-f4b370a38990) Without embeddings
![00001-1472638508](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/68433453/537b03e0-6bca-47c2-a7ec-724a7ad639f4) Same prompts with 1 embedding

### Commit where the problem happens

5e48f300c1b74f0312f692dc8d0485b5120fc497

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 5000 below)

### Command Line Arguments

```Shell
The default recommended :
set COMMANDLINE_ARGS= --lowvram --disable-nan-check --opt-sub-quad-attention --autolaunch
Same results with the inclusion of "--opt-split-attention"
```

### List of extensions

No

### Console logs

```Shell
E:\stable-diffusion-webui-directml>git pull
Already up to date.
venv "E:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: 5e48f300c1b74f0312f692dc8d0485b5120fc497
Installing requirements
Launching Web UI with arguments: --lowvram --disable-nan-check --opt-split-attention --autolaunch
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Loading weights [739260d554] from E:\stable-diffusion-webui-directml\models\Stable-diffusion\HoloIRL.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 8.4s (import torch: 1.9s, import gradio: 1.4s, import ldm: 0.6s, other imports: 1.6s, load scripts: 1.3s, create ui: 0.6s, gradio launch: 0.8s).
Creating model from config: E:\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: E:\stable-diffusion-webui-directml\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying optimization: Doggettx... done.
Textual inversion embeddings loaded(11): an6, bad-artist, bad-hands-5, badhandv4, deepnegative, easynegative, EasyNegativeV2, HyperStylizeV6, negative_hand, ulzzang-6500, verybadimagenegative
Model loaded in 19.0s (load weights from disk: 1.5s, create model: 0.9s, apply weights to model: 13.6s, apply half(): 1.4s, load VAE: 1.5s).
 31%|█████████████████████████▍                                                        | 13/42 [00:39<01:29,  3.08s/it]
Total progress:  31%|████████████████████▍                                             | 13/42 [00:37<01:24,  2.90s/it]
 33%|███████████████████████████▎                                                      | 14/42 [00:42<01:25,  3.07s/it]
Total progress:  33%|██████████████████████                                            | 14/42 [00:41<01:23,  2.98s/it]
Total progress:  33%|██████████████████████                                            | 14/42 [00:41<01:21,  2.90s/it]
```

### Additional information

Upon running "git checkout 3f52b28025efbc52c2a745d34bc7ed37710c7a1c" and then executing the same steps and using embeds, I got clear images

**Comment by Dardoth** [comment]
I've had this happen before and it was to do with an incompatibility running half precision on DirectML. https://github.com/vladmandic/automatic/issues/984

The solution was to add `--no-half` to the command line arguments. Can you re-run this test with that command added?

**Comment by lshqqytiger** [comment]
I strongly recommend to use `--no-half`. Otherwise, you can get incoherent images. (it's very random)
