### ISSUE TITLE
[Bug]: commit "0e4cbeb5318d1814a973509dfa45a6465f8719b5" uses only cpu

### ISSUE THREAD

**Issue by Dave811** [lshqqytiger/stable-diffusion-webui-directml#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

after the latest commit, it doesn't use directml, now it uses the cpu.
Because of that the generation is really slow.

### Steps to reproduce the problem

1. Be on commit "5e48f300c1b74f0312f692dc8d0485b5120fc497"
2. --> it uses the gpu for genearation
3. git pull
4. try generating an image

### What should have happened?

the image generation should take place on the gpu and not the cpu

### Commit where the problem happens

0e4cbeb5318d1814a973509dfa45a6465f8719b5

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 5000 below)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--medvram --no-half --precision full --opt-sub-quad-attention --backend=directml
```

### List of extensions

multidiffusion-upscaler-for-automatic1111  (not really using it)
sd-webui-controlnet (using)
ultimate-upscale-for-automatic1111 (using)

### Console logs

```Shell
venv "F:\Programs\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: 0e4cbeb5318d1814a973509dfa45a6465f8719b5
Installing requirements

Launching Web UI with arguments: --medvram --no-half --precision full --opt-sub-quad-attention --backend=directml
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
ControlNet v1.1.208
ControlNet v1.1.208
Loading weights [0b914c246e] from F:\Programs\stable-diffusion-webui-directml\models\Stable-diffusion\analogMadness_v40.safetensors
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 6.1s (import torch: 1.5s, import gradio: 1.1s, import ldm: 0.5s, other imports: 0.8s, load scripts: 1.2s, create ui: 0.3s, gradio launch: 0.6s).
Creating model from config: F:\Programs\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying optimization: sub-quadratic... done.
Textual inversion embeddings loaded(2): easynegative, lr
Model loaded in 2.7s (load weights from disk: 0.9s, create model: 0.9s, apply weights to model: 0.7s).
```

### Additional information

CPU: AMD Ryzen 5 5600X 6-Core Processor 
Arbeitsspeicher: 8,0 GB
GPU : Radeon RX Vega 64

**Comment by Dave811** [comment]
Forget it, I don't know how, but after I reset the repo everyting works fine.

**Comment by Milor123** [comment]
I have the same problem :(, what is the solution? after of today `git pull`, my GPU usagge is nulled less than 4%

**Comment by Dave811** [comment]
So I copied the models and extension folder, and files I copied or downloaded manually, to a save place (the start file too).

Then I deleted the repository and cloned it again. After that I copied the backup back and prevented files to override. Except for the start file with the parameters.

After that everything worked

**Comment by Milor123** [comment]
Solved using return to other commit https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/147#issuecomment-1573568988

> I have the same issue. However, I do not think that the updated driver is the issue. I get 9.53 s/it on commit https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/0e4cbeb5318d1814a973509dfa45a6465f8719b5 (current master), but git checkout to https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/5e48f300c1b74f0312f692dc8d0485b5120fc497 (one commit before) will get back to 3.00 it/s.

Solution, run: `git checkout 5e48f30`
Now my GPU is usage and very fast !!!!
Thank u guys !!!
