### ISSUE TITLE
[Bug]: Can't launch after first install

### ISSUE THREAD

**Issue by TTSKarlsson** [lshqqytiger/stable-diffusion-webui-directml#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![20230611_142712_1096x319](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/9962943/021e7040-a28f-4796-86aa-4eb19af48c9d)

### Steps to reproduce the problem

Follow the install instruction with submodule init and update.
Wait for it to finish installing.
Run the app.

### What should have happened?

It should have launched a backend web server for stable diffusion.

### Commit where the problem happens

ba780a8e4fb27d1eb9595947380a63bd84fc419e

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--autolaunch --skip-torch-cuda-test --backend=directml

Same result without arguments.
```

### List of extensions

None that I know of. Clean install.

### Console logs

```Shell
J:\automatic1111\stable-diffusion-webui-directml>webui-user.bat
venv "J:\automatic1111\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: <none>
Commit hash: ba780a8e4fb27d1eb9595947380a63bd84fc419e
Installing requirements
Launching Web UI with arguments: --autolaunch --skip-torch-cuda-test --backend=directml
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Loading weights [6ce0161689] from J:\automatic1111\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Press any key to continue . . .
```

### Additional information

Windows 11, AMD Ryzen 9 3900XT, AMD Radeon RX 7900 XT, 32 GB RAM

**Comment by lshqqytiger** [comment]
Please reopen this issue if it still persists.
