### ISSUE TITLE
昨天用着好好的，今天就用不了了，寻求帮助[Bug]: 

### ISSUE THREAD

**Issue by idesign2018** [lshqqytiger/stable-diffusion-webui-directml#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/42263070/9579b235-ea2f-4c2b-a2b7-0bcc9aba25da)
一打开就出现这个问题，我测试了之前可以用的版本，现在也用不了了，不知道是什么原因，我有很重要的事情需要做，耽误了很多事情

### Steps to reproduce the problem

现在完全用不了了

### What should have happened?

都不正常运行，如下图所显示
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/42263070/6d33dcb5-68d3-46f8-9284-f54312845856)

### Commit where the problem happens

D:\sd-webui\1\webui-user.bat

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above), AMD GPUs (RX 5000 below)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
否
```

### List of extensions

sd-webui-controlnet v 1.1.2219（具体版本不记得了，应该是最新的版本，旧版本也用不了了）
还装了其他插件，这个插件是最主要的，却用不了

### Console logs

```Shell
没有任何错误提示
```

### Additional information

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/42263070/20880b8d-ef19-4886-9d5b-ad8cb330d2cb)
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/42263070/c80eb386-e059-4bf0-bcf8-eb2d339b46c3)
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/42263070/3213be4c-1bdc-4a3e-b76d-c599c90121f6)

**Comment by lshqqytiger** [comment]
I can't reproduce. That message does not appear for me.
