### ISSUE TITLE
[Bug]: RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by happysad2021** [lshqqytiger/stable-diffusion-webui-directml#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

When trying to generate image. I know this issue to have existed, but the issue is closed (https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/146). I dont want to use --no-half, as this slows the generation extremely.

### Steps to reproduce the problem

clicking generate

### What should have happened?

generate properly

### Commit where the problem happens

ba780a8e

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Nvidia GPUs (RTX 20 above)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

only sd-dynamic-prompts extra

### Console logs

```Shell
File "\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 378, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "E:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\normalization.py", line 190, in forward
    return F.layer_norm(
  File "E:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```

**Comment by lshqqytiger** [comment]
I don't know which backend do you want.
If you want to use CUDA, add `--backend cuda`.
If you want to use DirectML, add `--backend directml`.

**Comment by happysad2021** [comment]
> `torch-directml` should be installed if you want DirectML. Remove venv folder and try again.

it should be "pip install torch-directml" right? I have installed this before installing the webui, but it stills says the module do not exist. Also, would this solve my issue of "RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'."? Thanks

**Comment by happysad2021** [comment]
> > `torch-directml` should be installed if you want DirectML. Remove venv folder and try again.
> 
> it should be "pip install torch-directml" right? I have installed this before installing the webui, but it stills says the module do not exist. Also, would this solve my issue of "RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'."? Thanks

I followed "...> .\venv\Scripts\activate.ps1 (.bat if you are using cmd)
(venv) ...> pip install torch-directml" to install and it says I already have its installed.

**Comment by happysad2021** [comment]
> > > `torch-directml` should be installed if you want DirectML. Remove venv folder and try again.
> > 
> > 
> > it should be "pip install torch-directml" right? I have installed this before installing the webui, but it stills says the module do not exist. Also, would this solve my issue of "RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'."? Thanks
> 
> I followed "...> .\venv\Scripts\activate.ps1 (.bat if you are using cmd) (venv) ...> pip install torch-directml" to install and it says I already have its installed.

WAIT! It shows it is installed but now when I run with --backend directml  it is working properly and no more runtime error.

To conclude:
1, installed "pip install torch-directml"
2, installed this webui
3, run the webui-user.bat to initialise things
4,  "...> .\venv\Scripts\activate.ps1 (.bat if you are using cmd)
(venv) ...> pip install torch-directml" to somehow register it?
5, add the line " --backend directml" in webui-user.bat
6, everything goes perfectly

Thanks!
