### ISSUE TITLE
BSOD: MEMORY MANAGEMENT ERROR 

### ISSUE THREAD

**Issue by BlackHatake** [lshqqytiger/stable-diffusion-webui-directml#170]
### Is there an existing issue for this?

- [ ] I have searched the existing issues and checked the recent builds/commits

### What happened?

I've been using SD for over 3 months and even with a weaker PC (FX-6300, 8GB RAM, RX570 8GB), I was able to get it to work normally with a few stutters at times.

But these last few days, i uninstalled my old webui and downloaded the latest one, at first it seemed to be working better and faster, but since yesterday when i try to open, blue screen occurs, or it rarely opens but after few generations i get a blue screen again , always with the same error message "MEMORY MANAGEMENT ERROR".

### Steps to reproduce the problem

1. Start "webui-user.bat" 
2. Wait for it to open and load
3. Get BSOD

OR

1. Start "webui-user.bat" 
2. Wait for it to open and load
3. Try to generate some images
4. Get BSOD

### What should have happened?

It should work fine with a little stutters sometimes

### Commit where the problem happens

ba780a8

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 5000 below)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--precision full --no-half --opt-sub-quad-attention --disable-nan-check
```

### List of extensions

No

### Console logs

```Shell
can't provide because my PC reboot before load CKPT
```

### Additional information

PC config:

FX-6300
8GB RAM
RX 570 8GB

**Comment by lshqqytiger** [comment]
I had never been reported BSOD issue on non-APU environment. Quite strange..

**Comment by lshqqytiger** [comment]
> 

Underclock & undervolt your gpu. It is known to be due to unstable power supply.

**Comment by stumpflt** [comment]
Its now happening to me, reinstalled and now when i try to generate, it BSOD just before 99% generation.
RX590, brand new 750W PSU. Never had a problem generating before the new update.

**Comment by festerz** [comment]
I get the same, first parts of my windows like start menu or desktop background bug out, then the browser (whichever I use, tried a few) bugs out, freezes, blinks, then stuff freezes and then blue screen with that error mentioned above, I got 8 ram, rx470 8gb

**Comment by nalayh** [comment]
I have an AMD Ryzen 9 3900X (12 core), 128 GB RAM and an NVIDIA Geforce 3900 FE (24GB), I have Geforce Studio in the latest version as of today (v546.33). I start A1111 with these parameters:
set COMMANDLINE_ARGS= --autolaunch --no-half-vae --xformers --opt-channelslast --medvram
set TF_ENABLE_ONEDNNN_OPTS=0
set SAFETENSORS_FAST_GPU=1
set PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512

WebUI version: v1.7.0 - python: 3.10.6 - torch: 2.0.1+cu118 - xformers: 0.0.20 - gradio: 3.41.2 - checkpoint: 31e35c80fc

After a while of generating images, it gives a BSOD and the computer restarts due to memory overflow,
I don't know if you have been able to solve it, and if so, I would appreciate some help.

**Comment by Ming2k8-Coder** [comment]
You have a nvidia card, why you not run a1111 cuda

Vào 15:57, T.2, 8 Th1, 2024 nalayh ***@***.***> đã viết:

**Comment by nalayh** [comment]
How can I do this? I thought I had it set up correctly. Thank you in
advance for your help.

**Comment by Ming2k8-Coder** [comment]
> How can I do this? I thought I had it set up correctly. Thank you in
> advance for your help.
> 
> El mar, 9 ene 2024 a las 7:25, Ming2k8-Coder ***@***.***>)
> escribió:
> 
> > You have a nvidia card, why you not run a1111 cuda
> >
> > Vào 15:57, T.2, 8 Th1, 2024 nalayh ***@***.***> đã viết:
> >
> > > I have an AMD Ryzen 9 3900X (12 core), 128 GB RAM and an NVIDIA Geforce
> > > 3900 FE (24GB), I have Geforce Studio in the latest version as of today
> > > (v546.33). I start A1111 with these parameters:
> > > set COMMANDLINE_ARGS= --autolaunch --no-half-vae --xformers
> > > --opt-channelslast --medvram
> > > set TF_ENABLE_ONEDNNN_OPTS=0
> > > set SAFETENSORS_FAST_GPU=1
> > > set PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
> > >
> > > WebUI version: v1.7.0 - python: 3.10.6 - torch: 2.0.1+cu118 - xformers:

You should install https://github.com/AUTOMATIC1111/stable-diffusion-webui version.
Bcuz you are comment on ishqqytiger fork so i think you installed directml version
