### ISSUE TITLE
[Bug]: OutofMemory by using no-half 

### ISSUE THREAD

**Issue by Pinoles17** [lshqqytiger/stable-diffusion-webui-directml#181]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What happened?

I was able to do 512x512 with Hires.Fix x2 (1024x1024) but wasn't able to use Inpaint, I looked up and find out that I needed "--no-half", I added to my ARGS and I was able to use Inpaint but now I can't use Hires.Fix, when it's 100% it appears the "RuntimeError: Could not allocate tensor with 1073741824 bytes. There is not enough GPU video memory available!". Sometimes is instantaneous after I press Generate

Edit: If a remove "--no-half" I can use Hires.Fix but can't use Inpaint :(

I have a 6600XT (8GB)

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/138397475/8ce1bd07-7bf4-4907-a706-47c3120ba405)

### Steps to reproduce the problem

1. I add Positive prompt: best quality, masterpiece, highres, / Negative prompt: (worst quality:1.4), (low quality:1.4), (normal quality:1.4), lowres, bad fingers, artifacts, watermark,
2. Select Hires.fix x2 (1024x1024) and leave everything at default
3. Press Generate and praying to work

### What should have happened?

Before modifying my ARGS by adding --no-half, everything works fine but can't use Inpaint

### Version or Commit where the problem happens

1.4.0

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --precision full --no-half --medvram --disable-nan-check --opt-sub-quad-attention --opt-split-attention --sub-quad-q-chunk-size 256 --sub-quad-kv-chunk-size 256 --sub-quad-chunk-threshold 70 --autolaunch --no-half-vae --opt-split-attention-v1

call webui.bat
```

### List of extensions

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/138397475/e8fd04a1-c969-4783-bca8-e13806cac099)

### Console logs

```Shell
Startup time: 176.4s (import torch: 4.5s, import gradio: 1.1s, import ldm: 1.4s, other imports: 3.8s, setup codeformer: 0.2s, list SD models: 0.8s, load scripts: 34.1s, initialize extra networks: 0.2s, create ui: 129.2s, gradio launch: 0.9s).
preload_extensions_git_metadata for 38 extensions took 5.73s
                                  *** Error running process: F:\SD2.0\stable-diffusion-webui-directml2\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "F:\SD2.0\stable-diffusion-webui-directml2\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "F:\SD2.0\stable-diffusion-webui-directml2\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 478, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "F:\SD2.0\stable-diffusion-webui-directml2\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
        all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
      File "F:\SD2.0\stable-diffusion-webui-directml2\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 71, in generate
        prompts.append(next(iter(gen)))
    StopIteration

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:17<00:00,  1.13it/s]
Total prTile 1/9 50%|█████████████████████████████████                                 | 20/40 [00:24<00:12,  1.63it/s]
        Tile 2/9
        Tile 3/9
        Tile 4/9
        Tile 5/9
        Tile 6/9
        Tile 7/9
        Tile 8/9
        Tile 9/9
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [01:35<00:00,  4.77s/it]
*** Error completing request███████████████████████████████████████████████████████████| 40/40 [02:04<00:00,  4.67s/it]
*** Arguments: ('task(olwsttkk5267clx)', '', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, True, 0.7, 2, 'R-ESRGAN 4x+ Anime6B', 0, 0, 0, 0, '', '', [], 0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 512, 64, True, True, True, False, False, '', 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002E8E666C040>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002E8E6BB5C30>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002E8E666C8E0>, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Bilinear', False, 'Lerp', '', '', False, False, None, True, False, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0, '', False, False, False, False, False, [], [], [], 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "F:\SD2.0\stable-diffusion-webui-directml2\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "F:\SD2.0\stable-diffusion-webui-directml2\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "F:\SD2.0\stable-diffusion-webui-directml2\modules\txt2img.py", line 94, in txt2img
        processed = processing.process_images(p)
      File "F:\SD2.0\stable-diffusion-webui-directml2\modules\processing.py", line 623, in process_images
        res = process_images_inner(p)
      File "F:\SD2.0\stable-diffusion-webui-directml2\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "F:\SD2.0\stable-diffusion-webui-directml2\modules\processing.py", line 744, in process_images_inner
        x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
      File "F:\SD2.0\stable-diffusion-webui-directml2\modules\processing.py", line 744, in <listcomp>
        x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
      File "F:\SD2.0\stable-diffusion-webui-directml2\modules\processing.py", line 525, in decode_first_stage
        x = model.decode_first_stage(x)
      File "F:\SD2.0\stable-diffusion-webui-directml2\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "F:\SD2.0\stable-diffusion-webui-directml2\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "F:\SD2.0\stable-diffusion-webui-directml2\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "F:\SD2.0\stable-diffusion-webui-directml2\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
        return self.first_stage_model.decode(z)
      File "F:\SD2.0\stable-diffusion-webui-directml2\modules\lowvram.py", line 54, in first_stage_model_decode_wrap
        return first_stage_model_decode(z)
      File "F:\SD2.0\stable-diffusion-webui-directml2\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
        dec = self.decoder(z)
      File "F:\SD2.0\stable-diffusion-webui-directml2\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\SD2.0\stable-diffusion-webui-directml2\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 637, in forward
        h = self.up[i_level].block[i_block](h, temb)
      File "F:\SD2.0\stable-diffusion-webui-directml2\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\SD2.0\stable-diffusion-webui-directml2\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 131, in forward
        h = self.norm1(h)
      File "F:\SD2.0\stable-diffusion-webui-directml2\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\SD2.0\stable-diffusion-webui-directml2\venv\lib\site-packages\torch\nn\modules\normalization.py", line 273, in forward
        return F.group_norm(
      File "F:\SD2.0\stable-diffusion-webui-directml2\venv\lib\site-packages\torch\nn\functional.py", line 2530, in group_norm
        return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
    RuntimeError: Could not allocate tensor with 1073741824 bytes. There is not enough GPU video memory available!
```

### Additional information

I've search for some ARGS and some people says that those are the optimal for performance (without --no-half) but I don't know what they do. If you can provide me any other COMMANDLINE_ARGS to improve performance or settings inside SD, I would really appreciate (:

**Comment by songib** [comment]
Had a similar problem for the first generation, what I did is just ignore it atm. After the last update, I got `"RuntimeError: Could not allocate tensor with xxxxxxx byte` more often idk why it's the case for the current version it had more memory leak problems.
Each time this happens, what I do is go to setting "Action" and then "Unload SD checkpoint to free VRAM" it resolves the problem but it's cumbersome at best. xd

**Comment by Pinoles17** [comment]
> 

I tried to do the same but nothing changed ):

**Comment by Pinoles17** [comment]
The solution was *****Disabling ADblocks*****

**Comment by Pinoles17** [comment]
It stop working again, adblockers didn't affect

**Comment by pw405** [comment]
Near as I can tell, --no half is only needed for inpainting.  If you don't plan to inpaint, you could just place that in a commented out section.  Not ideal, but figured it may be worth a mention.

**Comment by imathrowback** [comment]
You can find all the command line options here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-And-Settings

For one, remove all the "--opt" settings in your command line. They are mutually exclusive, you can only have one enabled at a time so trying to enable 3 at once does nothing. Instead set it in the UI under Settings->Optimizations->Cross attention optimization. if you are having out of memory issues use "Sub-quadratic". But try different ones and pick one that works for you, once you change and hit apply you don't have to restart the whole application.

Also instead of --no-half try --upcast-sampling instead, see if it helps. 
Also try removing --precision full, it's not supposed to be needed for RDNA2 cards.

See also: 
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8626
- https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/84
- https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/87

**Comment by Pinoles17** [comment]
> 

Thank you, I will try those commands and see if I can use Hiresfix and Inpainting. I'm still looking for the best optimal settings and high detailed images

**Comment by Pinoles17** [comment]
> You can find all the command line options here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-And-Settings
> 
> For one, remove all the "--opt" settings in your command line. They are mutually exclusive, you can only have one enabled at a time so trying to enable 3 at once does nothing. Instead set it in the UI under Settings->Optimizations->Cross attention optimization. if you are having out of memory issues use "Sub-quadratic". But try different ones and pick one that works for you, once you change and hit apply you don't have to restart the whole application.
> 
> Also instead of --no-half try --upcast-sampling instead, see if it helps. Also try removing --precision full, it's not supposed to be needed for RDNA2 cards.
> 
> See also:
> 
> * [Best parameteres for AMD users? AUTOMATIC1111/stable-diffusion-webui#8626](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8626)
> * [Sharing the experience of using DirectML for the new users. #84](https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/84)
> * [[Bug]: Inpainting suddenly stopped working #87](https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/87)

Update: It seems that "--no-half" it's required since Inpaint doesn't work. And I'm still unnable to use hiresfix x2 (1024x1024) :(

**Comment by karimball** [comment]
Second that. Running a RT6900XT with 16GB and can't get HiRes Fix flying. 
Before the Update i used: --no-half --precision full --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1 --disable-nan-check --api --listen
Tried different paramenters but no go..
--upcast-sampling --no-half-vae --opt-split-attention-v1 --disable-nan-check --api --listen i.E.

**Comment by pw405** [comment]
Confirmed can successfully inpaint (RDNA 3) using:

--medvram --upcast-sampling --no-half

(SDP optimization set in the UI)

However, VRAM will eventually be used and crash GPU driver.

**Comment by songib** [comment]
@pw405 Yep, `--opt-split-attention` or Doggettx memory leak still a problem `--opt-sub-quad-attentio` or sub-quadratic is good but can produce black Img. 

I got a memory leak when using Adetailer atm. idk what to do, each time it occurs I need to kill the process and start the `webui-user.bat` all over again. xd

**Comment by aa-parky** [comment]
> Confirmed can successfully inpaint (RDNA 3) using:
> 
> --medvram --upcast-sampling --no-half
> 
> (SDP optimization set in the UI)
> 
> However, VRAM will eventually be used and crash GPU driver.

Was experiencing these nan errors, but only with the sdxl model. On a RX7900xtx. The above has worked for me. Only thing I had to add was the `--medvram ` . Bit of research is this maybe a DirectML issue about not releasing vram?

**Comment by songib** [comment]
> Bit of research is this maybe a DirectML issue about not releasing vram?

Yes. and atm I haven't gone to SDXL yet since for some reason it can crash my PC just loading the model, stutter the GPU for just load the model into memory is kinda nuts (rx5700xt 8GB plebs here). xd
But with token merging under `Optimization` settings you can get away with it, set it at 0.5 for all three setting might help a bit. and the important setting for me was `--backend directml --medvram --no-half` the problem atm is the load time for each img gen is so slow. and I didn't even try the refiner extension yet (maybe later today, maybe it didn't work for DirectML. idk yet).

**Comment by pw405** [comment]
> > Bit of research is this maybe a DirectML issue about not releasing vram?
> 
> Yes. and atm I haven't gone to SDXL yet since for some reason it can crash my PC just loading the model, stutter the GPU for just load the model into memory is kinda nuts (rx5700xt 8GB plebs here). xd But with token merging under `Optimization` settings you can get away with it, set it at 0.5 for all three setting might help a bit. and the important setting for me was `--backend directml --medvram --no-half` the problem atm is the load time for each img gen is so slow. and I didn't even try the refiner extension yet (maybe later today, maybe it didn't work for DirectML. idk yet).

I also tried Refiner extension and it doesn't work.  I'm confused why there are no options for it. What is the CFG Scale? What steps does it use? etc. 

On the --backend directml , I wonder why that works? I thought this was already using DirectML?
