### ISSUE TITLE
[Bug]: `--hide-ui-dir-config` flag causes "Paste" button to not work

### ISSUE THREAD

**Issue by robonxt** [lshqqytiger/stable-diffusion-webui-directml#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I've enabled the `--hide-ui-dir-conf` flag recently and noticed that I cannot paste the previous prompt back into the WebUI.

This issues happens even if I disabled all extensions to make sure there is no conflicts.

### Steps to reproduce the problem

1. Add `--hide-ui-dir-conf` when launching WebUI 
2. Disable all extensions to make sure nothing conflicts
3. Reload WebUI/server
4. Type "test" to both positive and negative prompts
5. Press `Generate` and cancel it halfway
6. Clear both positive and negative prompts
7. Press the `Paste` button (↙️)
8. Notice the text not pasting back "test" to the prompts

### What should have happened?

The `Paste` button should work normally while the directories in settings should be hidden.

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows, Android

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### Cross attention optimization

InvokeAI

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--backend directml 
--disable-nan-check 
--skip-torch-cuda-test 
--hide-ui-dir-config 
--no-download-sd-model 
--enable-insecure-extension-access 
--medvram 
--precision full 
--upcast-sampling 
--use-cpu CLIP BLIP interrogate gfpgan bsrgan esrgan scunet codeformer 
--opt-sub-quad-attention 
--sub-quad-q-chunk-size 512 
--sub-quad-kv-chunk-size 512 
--sub-quad-chunk-threshold 80 
--update-all-extensions 
--skip-version-check 
--update-check 
--listen 
--port 7860
```

### List of extensions

No (Set to disable all for repeatable testing)

### Console logs

```Shell
Nothing on logs
```

### Additional information

Removing the `--hide-ui-dir-config` makes the `Paste` button work, so would this be a upstream problem?

**Comment by lshqqytiger** [comment]
I didn't touch many things related to UI. I think this is a upstream's.

**Comment by robonxt** [comment]
Ok, thanks for the quick response. Should I repost this bug upstream then?

**Comment by lshqqytiger** [comment]
If there's no same issue reported, yes.

**Comment by robonxt** [comment]
Seems like it's a intentional feature. Closing!
