### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Osaedasia** [lshqqytiger/stable-diffusion-webui-directml#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

During the installation or when I launch the webui there is the following bug : 

**Fetching updates for K-diffusion...
Checking out commit for K-diffusion with hash: c9fe758757e022f05ca5a53fa8fac28889e4f1cf...
Traceback (most recent call last):
  File "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\launch.py", line 38, in <module>
    main()
  File "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\launch.py", line 29, in main
    prepare_environment()
  File "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\modules\launch_utils.py", line 322, in prepare_environment
    git_clone(k_diffusion_repo, repo_dir('k-diffusion'), "K-diffusion", k_diffusion_commit_hash)
  File "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\modules\launch_utils.py", line 158, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\modules\launch_utils.py", line 108, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't checkout commit c9fe758757e022f05ca5a53fa8fac28889e4f1cf for K-diffusion.
Command: "git" -C "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\repositories\k-diffusion" checkout c9fe758757e022f05ca5a53fa8fac28889e4f1cf
Error code: 128
stderr: fatal: reference is not a tree: c9fe758757e022f05ca5a53fa8fac28889e4f1cf**

When I searched for the resolution of this bug it seems that in the "launch_utils.py" at line 271 the commit reference does not exist in the "K DIFFUSION" repo. When i replace it by this commit "47b6ef08bca986ff5e72815e74a419ef6616bdbb" the actual last master commit it work and start the UI.

### Steps to reproduce the problem

1. Delete Venv
2. Launch webui-user.bat

If venv already exist the bug is steel there

### What should have happened?

Check for an existing commit in the k_diffusion repository

### Version or Commit where the problem happens

097f9a096e84dd15cf75fdc0e8f0c763df256956

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### Cross attention optimization

None 

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
Creating venv in directory C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\venv using python "C:\Users\Osaedasia\AppData\Local\Programs\Python\Python310\python.exe"
venv "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: ## 1.4.1
Commit hash: 097f9a096e84dd15cf75fdc0e8f0c763df256956
Installing torch and torchvision
Collecting torch==2.0.0
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting torchvision==0.15.1
  Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
Collecting torch-directml
  Using cached torch_directml-0.2.0.dev230426-cp310-cp310-win_amd64.whl (8.2 MB)
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting filelock
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-10.0.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting numpy
  Downloading numpy-1.25.1-cp310-cp310-win_amd64.whl (15.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.0/15.0 MB 36.3 MB/s eta 0:00:00
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.0.4-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.9/123.9 kB ? eta 0:00:00
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.2.0-cp310-cp310-win_amd64.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.9/96.9 kB ? eta 0:00:00
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torch-directml
Successfully installed MarkupSafe-2.1.3 certifi-2023.5.7 charset-normalizer-3.2.0 filelock-3.12.2 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.25.1 pillow-10.0.0 requests-2.31.0 sympy-1.12 torch-2.0.0 torch-directml-0.2.0.dev230426 torchvision-0.15.1 typing-extensions-4.7.1 urllib3-2.0.4

[notice] A new release of pip available: 22.2.1 -> 23.2
[notice] To update, run: C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\venv\Scripts\python.exe -m pip install --upgrade pip
Installing gfpgan
Installing clip
Installing open_clip
Fetching updates for K-diffusion...
Checking out commit for K-diffusion with hash: c9fe758757e022f05ca5a53fa8fac28889e4f1cf...
Traceback (most recent call last):
  File "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\launch.py", line 38, in <module>
    main()
  File "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\launch.py", line 29, in main
    prepare_environment()
  File "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\modules\launch_utils.py", line 322, in prepare_environment
    git_clone(k_diffusion_repo, repo_dir('k-diffusion'), "K-diffusion", k_diffusion_commit_hash)
  File "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\modules\launch_utils.py", line 158, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\modules\launch_utils.py", line 108, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't checkout commit c9fe758757e022f05ca5a53fa8fac28889e4f1cf for K-diffusion.
Command: "git" -C "C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\repositories\k-diffusion" checkout c9fe758757e022f05ca5a53fa8fac28889e4f1cf
Error code: 128
stderr: fatal: reference is not a tree: c9fe758757e022f05ca5a53fa8fac28889e4f1cf

Appuyez sur une touche pour continuer...
```

**Comment by lshqqytiger** [comment]
Remove `C:\Stockage\Developpement\IA\stable-diffusion-webui-directml\repositories\k-diffusion` and try again.
