### ISSUE TITLE
[Bug]: Fails with memory error

### ISSUE THREAD

**Issue by theonlyremedy** [lshqqytiger/stable-diffusion-webui-directml#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

OS: Windows 11 Pro
GPU: AMD RX 5700XT
VRAM: 8GB
Processor: AMD Ryzen 5600X
Primary Memory: 16GB

I followed the installation instructions from here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs
After installation, I was able to start the WebUI but was unable to generate anything, I keep getting the error : RuntimeError: Could not allocate tensor with 9831040 bytes. There is not enough GPU video memory available!

Please check console logs for complete error information

### Steps to reproduce the problem

1. RX 5700XT GPU
2, Follow the manual installation guide for Windows from https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs
3. Start WebUI

### What should have happened?

It should have generated the image.

### Commit where the problem happens

6a6dd587

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--opt-sub-quad-attention --medvram --disable-nan-check --no-half --precision full
```

### List of extensions

none

### Console logs

```Shell
PS H:\Python\AI\stable-diffusion-webui-directml> .\webui.bat
venv "H:\Python\AI\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: 6a6dd5879811156baeea3a1c5b8c6aa306ec9dd9
Installing requirements for Web UI
Launching Web UI with arguments:
Interrogate will be fallen back to cpu. Because DirectML device does not support it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [fe4efff1e1] from H:\Python\AI\stable-diffusion-webui-directml\models\Stable-diffusion\model.ckpt
Creating model from config: H:\Python\AI\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 48.1s (load weights from disk: 41.8s, create model: 2.1s, apply weights to model: 1.3s, apply half(): 1.4s, move model to device: 1.4s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
  5%|████▏                                                                              | 1/20 [00:08<02:42,  8.56s/it]
Error completing request                                                                        | 0/20 [00:00<?, ?it/s]
Arguments: ('task(h16ycxt2jmydnil)', 'book with red cover', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\processing.py", line 832, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 349, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 349, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 150, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 117, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 778, in forward
    h = module(h, emb, context)
  File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 272, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 246, in split_cross_attention_forward_invokeAI
    r = einsum_op(q, k, v)
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 221, in einsum_op
    return einsum_op_dml(q, k, v)
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 209, in einsum_op_dml
    return einsum_op_tensor_mem(q, k, v, (mem_reserved - mem_active) if mem_reserved > mem_active else 1)
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 194, in einsum_op_tensor_mem
    return einsum_op_slice_1(q, k, v, max(q.shape[1] // div, 1))
  File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 169, in einsum_op_slice_1    r[:, i:end] = einsum_op_compvis(q[:, i:end], k, v)
RuntimeError: Could not allocate tensor with 9831040 bytes. There is not enough GPU video memory available!
```

**Comment by Miraihi** [comment]
Once again, arguments in webui-user.bat
`set COMMANDLINE_ARGS=--medvram --precision full --no-half --opt-sub-quad-attention --opt-split-attention --disable-nan-check`

**Comment by theonlyremedy** [comment]
Thanks for the input, sorry it didn't work :(

Full error log:
> PS H:\Python\AI\stable-diffusion-webui-directml> .\webui.bat
> venv "H:\Python\AI\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
> Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
> Commit hash: 6a6dd5879811156baeea3a1c5b8c6aa306ec9dd9
> Installing requirements for Web UI
> Launching Web UI with arguments:
> Interrogate will be fallen back to cpu. Because DirectML device does not support it.
> Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
> No module 'xformers'. Proceeding without it.
> Loading weights [fe4efff1e1] from H:\Python\AI\stable-diffusion-webui-directml\models\Stable-diffusion\model.ckpt
> Creating model from config: H:\Python\AI\stable-diffusion-webui-directml\configs\v1-inference.yaml
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> Applying cross attention optimization (InvokeAI).
> Textual inversion embeddings loaded(0):
> Model loaded in 50.5s (load weights from disk: 42.7s, create model: 1.3s, apply weights to model: 2.7s, apply half(): 1.7s, move model to device: 1.8s).
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
>   0%|                                                                                                                                                                                                                                                           | 0/20 [00:06<?, ?it/s]
> Error completing request
> Arguments: ('task(ytbydls3uzoonzq)', 'book red cover', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
> Traceback (most recent call last):
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
>     res = list(func(*args, **kwargs))
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
>     res = func(*args, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
>     processed = process_images(p)
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
>     res = process_images_inner(p)
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\processing.py", line 632, in process_images_inner
>     samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\processing.py", line 832, in sample
>     samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 349, in sample
>     samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
>     return func()
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 349, in <lambda>
>     samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
>   File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 150, in sample_euler_ancestral
>     denoised = model(x, sigmas[i] * s_in, **extra_args)
>   File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 117, in forward
>     x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
>   File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
>     eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
>     return self.inner_model.apply_model(*args, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
>     setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
>     return self.__orig_func(*args, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
>     x_recon = self.model(x_noisy, t, **cond)
>   File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
>     out = self.diffusion_model(x, t, context=cc)
>   File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 783, in forward
>     h = module(h, emb, context)
>   File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
>     x = layer(x, context)
>   File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
>     x = block(x, context=context[i])
>   File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
>     return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 114, in checkpoint
>     return CheckpointFunction.apply(func, len(inputs), *args)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 129, in forward
>     output_tensors = ctx.run_function(*ctx.input_tensors)
>   File "H:\Python\AI\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 272, in _forward
>     x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
>   File "H:\Python\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 246, in split_cross_attention_forward_invokeAI
>     r = einsum_op(q, k, v)
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 221, in einsum_op
>     return einsum_op_dml(q, k, v)
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 209, in einsum_op_dml
>     return einsum_op_tensor_mem(q, k, v, (mem_reserved - mem_active) if mem_reserved > mem_active else 1)
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 194, in einsum_op_tensor_mem
>     return einsum_op_slice_1(q, k, v, max(q.shape[1] // div, 1))
>   File "H:\Python\AI\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 169, in einsum_op_slice_1
>     r[:, i:end] = einsum_op_compvis(q[:, i:end], k, v)
> RuntimeError: Could not allocate tensor with 4915840 bytes. There is not enough GPU video memory available!

webui-user.bat

> @echo off
> 
> set PYTHON=
> set GIT=
> set VENV_DIR=
> set COMMANDLINE_ARGS=--medvram --precision full --no-half --opt-sub-quad-attention --disable-nan-check --opt-split-attention-v1
> 
> call webui.bat

**Comment by Miraihi** [comment]
Also, if you try to generate something bigger than 600x800, it won't work on 8 GB graphics card because of a really bad memory management of DirectML.

**Comment by Miraihi** [comment]
I have no idea what WSL is, but my graphics card is 8 GB (RX 580) too and it works just fine for me with these arguments. Can't fathom what is the problem.

**Comment by gogogame** [comment]
I also have this same problem I run it on RX5700 XT, but mine just crash the PC outright everytime I tried to run it.
If RX580 work maybe I'll try this with my old RX570, it should work since it's on same architecture.

**Comment by theonlyremedy** [comment]
WSL is a Windows Subsystem for Linux, that enables you to run Linux on top of Windows. I read that SD works on AMD GPUs in Linux using ROCm. Was just checking if anyone has got it to run successfully on WSL.

**Comment by gogogame** [comment]
> 

I doubt that was the issue I think 850w should be plenty for that but I can't confirmed it since I don't have a higher wattage PSU.
On the other hand fall back to Rx570 generate picture in 512x512 just fine with around 2s/it speed.

**Comment by Miraihi** [comment]
> I doubt that was the issue I think 850w should be plenty for that but I can't confirmed it since I don't have a higher wattage PSU.

I also doubted because the wattage in my PSU also seemed fine. Some condensators may've became weary over time and were giving up under a big load.
But happy for you getting RX570 working.

**Comment by theonlyremedy** [comment]
I was able to fix it. It was my fault totally, I was running it from a Windows Terminal that was opened with Admin rights. Works fine now.

**Comment by lshqqytiger** [comment]
1. stable-diffusion-webui-directml targets only Windows. But you can run it on WSL.
2. ROCm does not work on WSL.

**Comment by gogogame** [comment]
> I was able to fix it. It was my fault totally, I was running it from a Windows Terminal that was opened with Admin rights. Works fine now.
Kind of weird mine but work sometimes, so I suspect it could be an issue with my driver, can I ask which's driver you're one? I'm on 22.Q4

Also my terminal has this extra line after Launching Web UI with arguments
```
Warning: experimental graphic memory optimization for AMDGPU is disabled. Because there is an unknown error.
Disabled experimental graphic memory optimizations.
```

**Comment by Miraihi** [comment]
> Also my terminal has this extra line after Launching Web UI with arguments
> 
> ```
> Warning: experimental graphic memory optimization for AMDGPU is disabled. Because there is an unknown error.
> Disabled experimental graphic memory optimizations.

Everyone who use `--opt-split-attention` have this message. This is normal.

**Comment by gogogame** [comment]
> Everyone who use `--opt-split-attention` have this message. This is normal.

Ah I didn't know that, thanks. 

I've done some GPU stress test and it runs perfectly fine so now I strongly doubt that it's PSU problem and the system crash didn't dump it since it report error as ID 6008 which is the "Unexpected" error with no dump.
So I guess I'll try to have to try others GPU driver next.

**Comment by TheAkashicTraveller** [comment]
Well I'm getting this too, also on a 5700 XT with the same runtime error. I only just instaloled it and have the COMMANDLINE_ARGS set. I know my gpu is fine because I can run stable diffusion onnx, it just doesn't have a gui at all and I have no idea how to set up half the features this has.

**Comment by justanothernguyen** [comment]
In my case I'm on APU (Ryzen 6900HX with Radeon 680M). If I use `set COMMANDLINE_ARGS=--medvram --precision full --no-half --opt-sub-quad-attention --opt-split-attention-v1 --disable-nan-check` like @Miraihi suggested, I can only get pure black image.

Removing `--disable-nan-check` and it works again, still very RAM hungry though but at least it let me get to 720x360 and stays there for subsequent inferences
![image](https://user-images.githubusercontent.com/1379769/222719218-9c723d85-8ead-4d97-83fd-1a685637922b.png)

So maybe try enable/disable one flags at a time and see if it helps?


Interestingly, running in CPU-only mode it does not use as much RAM, that I never really run into memory allocation issue, and CPU inferences is only about 3-5 times slower because mobile APU is sh*t.

**Comment by lshqqytiger** [comment]
> Interestingly, running in CPU-only mode it does not use as much RAM

Because memory garbage collector works fine on cpu mode.
But we are not able to use features provided by pytorch and to manually collect garbage on DirectML device.

**Comment by TheAkashicTraveller** [comment]
I tried disabling those flags and the only thing that happened was it got one iteration in once but I couldn't repeat it.

**Comment by TheAkashicTraveller** [comment]
Well, I reinstalled from scratch and now it's working with the low vram arguments. So either I did somthing dumb or somthing wierd happened. Anyway I need to figure out which of those argument's I actually need since it's using less than half of my vram right now and running twice as fast as the comandline version I've been using. Thoug it is nice having my computer actually be usable while it's running.

**Comment by Miraihi** [comment]
@TheAkashicTraveller Try `--medvram` if you see that your GPU is underutilized.

**Comment by TheAkashicTraveller** [comment]
I'm now running even faster than the command line version I was using with just these --precision full --no-half --opt-sub-quad-attention --disable-nan-check and I was getting black squares without --precision full --no-half but it looks like I'm good now.

**Comment by Winnougan** [comment]
> Once again, arguments in webui-user.bat `set COMMANDLINE_ARGS=--medvram --precision full --no-half --opt-sub-quad-attention --opt-split-attention-v1 --disable-nan-check` You WILL go out of memory without those

How do we add that line of code? When I launch webui-user.bat it doesn't let me add any lines. Can you explain it please? Thank you

**Comment by soredake** [comment]
Is there a way to run SD with rx 560 4gb? No matter what i try i get this `RuntimeError: Could not allocate tensor with 1638400 bytes. There is not enough GPU video memory available!`
