### ISSUE TITLE
[Feature Request]: There should be a thing that slows down the generation process

### ISSUE THREAD

**Issue by Spas120** [lshqqytiger/stable-diffusion-webui-directml#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

There should be a thing that slows down the generation process so people can generate bigger images without it crashing. it happened to me when i use --no-half and it was actually really useful but --no-half just crashes it whenever added so there should be a option to slow down the generation process since i was able to generate 1000x1000 pixels big images without it crashing when using --no-half.

### Proposed workflow

There should be like a switch or button that turns on slower generations and i hope it shouldnt be to hard to add

### Additional information

This feature would help many people in my opinion since there are some other people that want to make bigger images but cant

**Comment by lshqqytiger** [comment]
There are `--medvram` and `--lowvram` for that purpose.

**Comment by Spas120** [comment]
> There are `--medvram` and `--lowvram` for that purpose.

it doesnt change anything tho they both do the same to at least for me and maybe even for more people

**Comment by Spas120** [comment]
> There are `--medvram` and `--lowvram` for that purpose.

in fact the lowvram actually crashes it faster so there should be an option for slow generation like when i used --no-half for slow generations before it just started to not work at all it would go slow and use less gpu and then spikes to more gpu being used for a bit and then goes back to less gpu and then it kept repeating that and i was actually able to make 1000x1000 pixel big images without it crashing every minute

**Comment by Spas120** [comment]
> There are `--medvram` and `--lowvram` for that purpose.

please consider adding a slow down feature to it cause --medvram and --lowvram dont change anything besides one crashes faster then the other

**Comment by lshqqytiger** [comment]
"slowing down" and "making larger image generatable" are separate matters.
Slowing down does not allow us to generate larger image.
Large image generation requires the memory space which is sufficient to store large tensors.
Luckily, we have "tiling" technique which helps us to generate larger images.

**Comment by Spas120** [comment]
> Doesn't hires. fix basically do what you're looking for? It's a lot slower but you can use it to make higher resolution pictures which also don't suffer from possible issues normal high-resolution generation brings, like most of the finished image being noise.
> 
> The model doesn't crash because it's "going too fast". It crashes if it runs out of vram to use, "slowing down" the process would just mean you wait longer before it crashes.
> 
> Also, --no-half isn't a "slowdown". It's more like "half" is a speedup, but as for now it's less stable than full precision.

i know --no-half isnt a slowdown im just saying when i used it the generation process was slow and i was using it as an example for what im trying to say

**Comment by Helius22** [comment]
Ahh my bad I mixed up hires fix with something else. Lookup "Controlnet 1.1 tiles tutorial." You still need to generate a lower resolution image close to what you want for your end result and then run it through img2img with controlnet for that high resolution. 

The way it works is it renders parts of the image with the "tile" resolution and blends them together. Your gpu shouldn't run out of memory as long as it can handle the resolution of 1 tile, and the more tiles you add the higher the end resolution in exchange for it taking more time.

**Comment by Spas120** [comment]
> Ahh my bad I mixed up hires fix with something else. Lookup "Controlnet 1.1 tiles tutorial." You still need to generate a lower resolution image close to what you want for your end result and then run it through img2img with controlnet for that high resolution.
> 
> The way it works is it renders parts of the image with the "tile" resolution and blends them together. Your gpu shouldn't run out of memory as long as it can handle the resolution of 1 tile, and the more tiles you add the higher the end resolution in exchange for it taking more time.

I tied a tutorial for this and once i clicked generate my pc screen instantly went out
