### ISSUE TITLE
[Bug]:  Always Use the Integrated graphics rather than Discrete graphics

### ISSUE THREAD

**Issue by SheepChef** [lshqqytiger/stable-diffusion-webui-directml#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Well, my laptop have two GPU devices.
GPU0 is an Intel integrated graphic card, which, actually, uses cpu to calculate.
GPU1 is a basic AMD discrete graphic card.

However, the GPU1 remains zero occupation during loading models, until the script finally crashed due to the lack of RAM.
I've already add --device-id 1, however, the calculation seems still using the GPU0 and finally gives a Runtime Error.

### Steps to reproduce the problem

There is no reproduction.

### What should have happened?

GPU1 is used to calculate rather than GPU0(CPU)

### Version or Commit where the problem happens

4f46f9bd54e0ce25a50fa3c04b82e9bf74b97c66

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 5000 below)

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--medvram --precision full --no-half --no-half-vae --opt-split-attention-invokeai --always-batch-cond-uncond --opt-sub-quad-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --disable-nan-check --upcast-sampling --device-id 1
```

### List of extensions

No

### Console logs

```Shell
Runtime Error

```

**Comment by lshqqytiger** [comment]
It seems to work properly for me.
`--backend directml --device-id 1`
GPU0
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/39524005/600ee9fa-8dd3-4786-82b5-ca577ef1f0f7)
GPU1
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/39524005/ffcefaee-1006-4cee-ac49-4ba629440d72)

**Comment by lshqqytiger** [comment]
Run these lines in venv activated powershell/prompt.
```python
(venv) $ python
>>> import torch_directml
>>> torch_directml.device_name(0) # --device-id 0
>>> torch_directml.device_name(1) # --device-id 1
```

**Comment by rocky533** [comment]
not sure if this will help but i have a 5600 apu with a 580 and can choose the apu or the card to run python through windows 11 settings.  Not sure if this is in win 10.

right click desktop, select display settings, 
click on the graphics button.
find python if its in the list, if not add it.
once added you can change the gpu used for that program.

**Comment by SheepChef** [comment]
ok, the problem is solved.
However, it is a pity that even my AMD graphics cannot run the model, which have only 2GB memory.
