### ISSUE TITLE
[Feature Request]: Update repo reademe for install instructions

### ISSUE THREAD

**Issue by GoZippy** [lshqqytiger/stable-diffusion-webui-directml#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

readme is for auto1111 - should add notes on this specific fork

### Proposed workflow

readme is for auto1111 - should add notes on this specific fork

**Comment by lshqqytiger** [comment]
I already updated README like [this](https://github.com/lshqqytiger/stable-diffusion-webui-directml#automatic-installation-on-windows).
Is there something else needed?
