### ISSUE TITLE
[Bug]: Interrogate Clip produces <error>

### ISSUE THREAD

**Issue by jsnprojs** [lshqqytiger/stable-diffusion-webui-directml#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Interrogate Clip produces <error>, however, Interrogate DeepBooru works fine

I also found that using the version from https://github.com/AUTOMATIC1111/stable-diffusion-webui 

`git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git.`

works just fine, though I couldn't get DeepBooru to work.

### Steps to reproduce the problem

1. Go to img2img
2. Upload image to img2img
3. Press Interrogate Clip
4. produces <error> in prompt

### What should have happened?

produces prompts for the image uploaded

### Version or Commit where the problem happens

version: 1.5.0  •  python: 3.10.6  •  torch: 2.0.0+cpu  •  xformers: N/A  •  gradio: 3.32.0  •  checkpoint: 52484e6845

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--upcast-sampling --autolaunch --opt-sdp-attention --skip-torch-cuda-test
```

### List of extensions

No

### Console logs

```Shell
To create a public link, set `share=True` in `launch()`.
Creating model from config: C:\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
Startup time: 6.7s (launcher: 0.4s, import torch: 2.6s, import gradio: 0.7s, setup paths: 0.6s, other imports: 0.9s, list SD models: 0.1s, load scripts: 0.8s, create ui: 0.3s, gradio launch: 0.3s).
DiffusionWrapper has 859.52 M params.
Applying attention optimization: sdp... done.
Model loaded in 3.7s (load weights from disk: 0.5s, create model: 0.5s, apply weights to model: 0.4s, apply half(): 0.4s, move model to device: 1.9s, calculate empty prompt: 0.1s).
load checkpoint from C:\stable-diffusion-webui-directml\models\BLIP\model_base_caption_capfilt_large.pth
*** Error interrogating
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui-directml\modules\interrogate.py", line 195, in interrogate
        caption = self.generate_caption(pil_image)
      File "C:\stable-diffusion-webui-directml\modules\interrogate.py", line 181, in generate_caption
        caption = self.blip_model.generate(gpu_image, sample=False, num_beams=shared.opts.interrogate_clip_num_beams, min_length=shared.opts.interrogate_clip_min_length, max_length=shared.opts.interrogate_clip_max_length)
      File "C:\stable-diffusion-webui-directml\repositories\BLIP\models\blip.py", line 156, in generate
        outputs = self.text_decoder.generate(input_ids=input_ids,
      File "C:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\generation\utils.py", line 1518, in generate
        return self.greedy_search(
      File "C:\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\generation\utils.py", line 2325, in greedy_search
        next_tokens = next_tokens * unfinished_sequences + pad_token_id * (1 - unfinished_sequences)
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, privateuseone:0 and cpu!
```

### Additional information

GPU: AMD RX6800
CPU: AMD 5600x
MB: Asus B550x
Windows 11

**Comment by Miraihi** [comment]
Yeah, Interrogate Clip didn't work as long as I remember.

**Comment by lcuhov** [comment]
I have the same problem on a similar hardware

**Comment by kazssym** [comment]
I tried this change to fix the issue, but I got another error with a memory full in interrogation. Can anyone test it if it really fixes the issue?

```diff
--- a/modules/dml/hijack/torch.py
+++ b/modules/dml/hijack/torch.py
@@ -5,4 +5,4 @@ from modules.sd_hijack_utils import CondFunc
 CondFunc('torchsde._brownian.brownian_interval._randn', lambda _, size, dtype, device, seed: torch.randn(size, dtype=dtype, device=torch.device("cpu"), generator=torch.Generator(torch.device("cpu")).manual_seed(int(seed))).to(device), lambda _, size, dtype, device, seed: device.type == 'privateuseone')
 
 # https://github.com/microsoft/DirectML/issues/400
-CondFunc('torch.Tensor.new', lambda orig, self, *args, **kwargs: orig(self.cpu(), *args, **kwargs), lambda orig, self, *args, **kwargs: torch.dml.is_directml_device(self.device))
+CondFunc('torch.Tensor.new', lambda orig, self, *args, **kwargs: orig(self.cpu(), *args, **kwargs).to(torch.dml.default_device()), lambda orig, self, *args, **kwargs: torch.dml.is_directml_device(self.device))
```

**Comment by EvansJahja** [comment]
@kazssym Confirmed that solves the issue. I also have to reduce the limit of lines for CLIP.
The default number of lines was set as 1500, calling for too much memory. Setting it to something sensible like 20 solves it for me.

**Comment by maxencry** [comment]
> @kazssym Confirmed that solves the issue. I also have to reduce the limit of lines for CLIP. The default number of lines was set as 1500, calling for too much memory. Setting it to something sensible like 20 solves it for me.

My value was 0, then infinite.
I set to 20 and now it works perfectly
