### ISSUE TITLE
[Bug]: 2nd image generation is way slower than the first...

### ISSUE THREAD

**Issue by LappIand** [lshqqytiger/stable-diffusion-webui-directml#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Basically I try to generate any image with set settings which we'll refer to as settings Alpha.

Using settings Alpha only and no changes between the two image generations, the first one on my RX 5600 XT generates with 3 - 5 s/it which is good for me.

However, the second image still using settings Alpha, will go all the way to 18s/it for no reason that I can decipher...

### Steps to reproduce the problem

1 - Set up SD for an image generation
2 - Generate image 1
3 - Generate image 2 (and see the climb in s/it )

### What should have happened?

Should've been very close to the time it takes for each iteration to complete.

### Version or Commit where the problem happens

2c2ca1170bcb7bbd12eef4551b8a42ab16dbe5f7

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 5000 below)

### Cross attention optimization

InvokeAI

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
V1.5.1 : set COMMANDLINE_ARGS= --lowvram --disable-nan-check
<V1.3 : set COMMANDLINE_ARGS= --lowvram --disable-nan-check --no-half-vae --autolaunch
```

### List of extensions

V1.5.1 - No extensions
<V1.3 :
   - a1111-sd-webui-lycoris
   - a1111-sd-webui-tagcomplete
   - OneButtonPrompt
   - SD-CN-Animation
   - sd-webui-controlnet
   - sd-webui-regional-prompter
   - stable-diffusion-webui-composable-lora
   - ultimate-upscale-for-automatic1111

### Console logs

```Shell
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

venv "E:\Stability SD\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.1
Commit hash: 2c2ca1170bcb7bbd12eef4551b8a42ab16dbe5f7
Launching Web UI with arguments: --lowvram --disable-nan-check
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception '', memory monitor disabled
Loading weights [739260d554] from E:\Stability SD\stable-diffusion-webui-directml\models\Stable-diffusion\HoloIRL.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 7.4s (launcher: 0.4s, import torch: 2.8s, import gradio: 0.8s, setup paths: 0.7s, other imports: 1.1s, load scripts: 0.9s, create ui: 0.5s, gradio launch: 0.2s).
Creating model from config: E:\Stability SD\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: InvokeAI... done.
Model loaded in 9.1s (load weights from disk: 1.1s, create model: 0.3s, apply weights to model: 6.9s, apply half(): 0.4s, calculate empty prompt: 0.2s).
100%|██████████████████████████████████████████████████████████████████████████████████| 42/42 [02:28<00:00,  3.53s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 42/42 [02:24<00:00,  3.44s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 42/42 [07:43<00:00, 11.03s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 42/42 [07:31<00:00, 10.75s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 42/42 [07:31<00:00, 11.33s/it]
```

### Additional information

I'm desperate to find any help that one can lend me.

I've only seen a few people encounter this issue, and I have already ruled out the version issue as I've tried older commits which used to work perfectly and have reinstalled SD as a whole.

No matter if I'm before V1.3 (my stablest version) or latest V1.5.1, the bug presists.

**Comment by pw405** [comment]
Have you tried using SDP (Scaled Dot Product) optimization instead of InvokeAI?  You can add it to the command line arguments, or just set it in the Settings -> Optimization menu within the UI.  

Additionally, you might try these commands in your webui-user.bat file:

--upcast-sampling --no-half

**Comment by LappIand** [comment]
Thank you pw405, this has worked for me.

Have a wonderful day !
