### ISSUE TITLE
[Bug]: Latest update causes errors on launch

### ISSUE THREAD

**Issue by dieselino0** [lshqqytiger/stable-diffusion-webui-directml#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

After launcing the webui and after it pulls the latest update I get these errors in the below screenshots

![70b2fa1bbf38e8053c9c3025ce73876d](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/132487877/e787381c-8bce-422e-aee1-d1c3777e16db)
![34ab73a2f68310f258443e185a986e8b](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/132487877/d53e9708-d539-4ccf-8a7b-18197d541d5a)

### Steps to reproduce the problem

Launched webui, webui pulled the latest update which caused all these errors

### What should have happened?

Launched normally

### Version or Commit where the problem happens

ed20ba7f9ff593bcf012db79278930a381a55748

### What Python version are you running on ?

None

### Cross attention optimization

Automatic

### Command Line Arguments

```Shell
--opt-sub-quad-attention --upcast-sampling
```

### List of extensions

None

### Console logs

```Shell
https://pastebin.com/Y6yS6f04
```

**Comment by SunGreen777** [comment]
Last update
ImportError: cannot import name 'opts' from partially initialized module 'modules.shared' (most likely due to a
circular import) (W:\stable-diffusion-webui-directml\modules\shared.py)

**Comment by Adsen38** [comment]
Same Error 7900 XTX here,

**Comment by hkpD** [comment]
As a workaround, you can open a terminal window in your "webui.bat" directory and type `git checkout 4873e6aaba62c2fa2e4481798e85098e50e1e2c6`

**Comment by zethriller** [comment]
I had this issue and managed to overcome it with the git checkout command.
However now i have something else:
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.1
Commit hash: 4873e6aaba62c2fa2e4481798e85098e50e1e2c6
Launching Web UI with arguments: --disable-nan-check --opt-sub-quad-attention --gradio-img2img-tool color-sketch --deepdanbooru --no-half --no-half-vae --medvram
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception '', memory monitor disabled
Loading weights [6ce0161689] from D:\Automatic1111_AMD\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Traceback (most recent call last):
  File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\launch.py", line 39, in <module>
    main()
  File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\launch.py", line 35, in main
    start()
  File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\launch_utils.py", line 447, in start
    webui.webui()
  File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\webui.py", line 393, in webui
    shared.demo = modules.ui.create_ui()
  File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\ui.py", line 501, in create_ui
    modules.scripts.scripts_txt2img.setup_ui_for_section(category)
  File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\scripts.py", line 433, in setup_ui_for_section
    self.create_script_ui(script)
  File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\scripts.py", line 383, in create_script_ui
    import modules.api.models as api_models
  File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\api\models.py", line 112, in <module>
    ).generate_model()
  File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\api\models.py", line 97, in generate_model
    DynamicModel.__config__.allow_population_by_field_name = True
  File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 205, in __getattr__
    raise AttributeError(item)
AttributeError: __config__
Creating model from config: D:\Automatic1111_AMD\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: sub-quadratic... done.
Model loaded in 2.4s (load weights from disk: 0.3s, create model: 0.3s, apply weights to model: 1.2s, calculate empty prompt: 0.5s).
Press any key to continue . . .
```

Radeon RX6800 XT
Launch settings: `--disable-nan-check --opt-sub-quad-attention --gradio-img2img-tool color-sketch --deepdanbooru --no-half --no-half-vae --medvram`

**Comment by songib** [comment]
> I had this issue and managed to overcome it with the git checkout command. However now i have something else:
> 
> ```
> Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
> Version: 1.5.1
> Commit hash: 4873e6aaba62c2fa2e4481798e85098e50e1e2c6
> Launching Web UI with arguments: --disable-nan-check --opt-sub-quad-attention --gradio-img2img-tool color-sketch --deepdanbooru --no-half --no-half-vae --medvram
> no module 'xformers'. Processing without...
> no module 'xformers'. Processing without...
> No module 'xformers'. Proceeding without it.
> Warning: caught exception '', memory monitor disabled
> Loading weights [6ce0161689] from D:\Automatic1111_AMD\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
> Traceback (most recent call last):
>   File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\launch.py", line 39, in <module>
>     main()
>   File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\launch.py", line 35, in main
>     start()
>   File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\launch_utils.py", line 447, in start
>     webui.webui()
>   File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\webui.py", line 393, in webui
>     shared.demo = modules.ui.create_ui()
>   File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\ui.py", line 501, in create_ui
>     modules.scripts.scripts_txt2img.setup_ui_for_section(category)
>   File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\scripts.py", line 433, in setup_ui_for_section
>     self.create_script_ui(script)
>   File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\scripts.py", line 383, in create_script_ui
>     import modules.api.models as api_models
>   File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\api\models.py", line 112, in <module>
>     ).generate_model()
>   File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\modules\api\models.py", line 97, in generate_model
>     DynamicModel.__config__.allow_population_by_field_name = True
>   File "D:\Automatic1111_AMD\stable-diffusion-webui-directml\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 205, in __getattr__
>     raise AttributeError(item)
> AttributeError: __config__
> Creating model from config: D:\Automatic1111_AMD\stable-diffusion-webui-directml\configs\v1-inference.yaml
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> Applying attention optimization: sub-quadratic... done.
> Model loaded in 2.4s (load weights from disk: 0.3s, create model: 0.3s, apply weights to model: 1.2s, calculate empty prompt: 0.5s).
> Press any key to continue . . .
> ```
> 
> Radeon RX6800 XT Launch settings: `--disable-nan-check --opt-sub-quad-attention --gradio-img2img-tool color-sketch --deepdanbooru --no-half --no-half-vae --medvram`

Try to delete the venv folder and try again, maybe it can help.

**Comment by zethriller** [comment]
Just did, but it ends up with the same error.

**Comment by songib** [comment]
@zethriller 
at this point just wait for the update, I'm waiting too. xd

**Comment by dieselino0** [comment]
Newest commit update has been released and issue has been fixed for me

https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/723974a8b74ffd5acc1a1fdaf36e9c2426651537
