### ISSUE TITLE
[Bug]: SDXL problem with the management of the RAM memory (32go)

### ISSUE THREAD

**Issue by StudioDUzes** [lshqqytiger/stable-diffusion-webui-directml#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

PC freezes after image generation, 99% ram memory usage (32go)

### Steps to reproduce the problem

1. load model SDXL
2. generate image 768 x 768
3. PC freezes after image generation, 99% ram memory usage (32go)
4. take your smartphone for a screenshot...

### What should have happened?

work 

### Version or Commit where the problem happens

Version: 1.5.1 Commit hash: 3f69a46aced47d8b14a9abb24181231ae7976966

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Other GPUs

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--device-id 1 --port 7861 --medvram --opt-sdp-no-mem-attention --opt-sdp-attention --no-half --no-half-vae --precision full --opt-sub-quad-attention --opt-split-attention-v1 --disable-nan-check --autolaunch
```

### List of extensions

No problem

### Console logs

```Shell
No problem
```

### Additional information

take my smartphone for a screenshot
![1691055235159](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/3be93096-8b43-45f6-b5d0-34f6488b43d2)

CHRONOLOGY OF THE PROBLEM (Intel Arc a770 16go)

PC at rest
![ram au repos](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/c75a54b6-1d5b-4f17-8874-236753ab8c30)

Run WEBUI with 1.5 model
![webui + model 1 5](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/ce55451a-359e-4989-8f32-9577d2e9abf1)

Generate image 768X768
![calcul 768x768](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/a995419b-cf29-45c3-aa60-5cda96207d97)

After génération
![après calcul 768x768](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/e9d867a9-0088-406f-b864-9afdb9bfd5a5)
![python](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/52819da5-f69f-4b2f-a41a-2f350cdfd519)
![descente](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/b5196432-57e9-4180-8c0a-8cc263dcb190)
![python descente](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/5364674e-4f70-4557-90ee-790560fbfec9)

Run SDXL model
![SDXL model](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/57eae600-e7ff-469b-8862-0ea42d3f3eb8)

Generate image 768x768
![SDXL 768x768](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/c08bb693-27fd-49bc-9dff-8980b9d8fd1a)

After génération
![après generation](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/b6553cb6-0e9c-4004-a14e-77cd830ddb27)

 PC freezes, take my smartphone for a screenshot
![1691055235159](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/3be93096-8b43-45f6-b5d0-34f6488b43d2)

After 2 or 3 minutes PC OK
![after 3 minutes](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/0f9083b8-4e39-4dac-86f4-049ae4398d0c)

**Comment by lshqqytiger** [comment]
Does your GPU work on generation? Or it is normal if you are running SD on iGPU.

**Comment by StudioDUzes** [comment]
> Does your GPU work on generation? Or it is normal if you are running SD on iGPU.

I have 2 GPU intel arc a770 16go, not iGPU... "i try one GPU for windows and one only for SD for Vram saving or for two instance of SD", but I don't think that's the problem, at the moment only one GPU work for SD...

**Comment by HyunJae5463** [comment]
I have the same issue, got an Arc A770 too so i guess the card is the problem. It feels like SDXL uses your normal ram instead of your vram lol.

**Comment by StudioDUzes** [comment]
> I have the same issue, got an Arc A770 too so i guess the card is the problem. It feels like SDXL uses your normal ram instead of your vram lol.

Now everything works fine with SDXL and I have two installations of Automatic1111 each working on an intel arc a770

I went up to 64gb of ram

webui.user.bat like that :

@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --device-id 1 --port 7861 --medvram --always-batch-cond-uncond --upcast-sampling --precision full --no-half-vae --disable-nan-check --use-cpu interrogate codeformer --api --autolaunch

set SAFETENSORS_FAST_GPU=1

git pull

call webui.bat

And

![optimization](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/131154500/06434119-7d36-441f-8e3f-a8fbd9bd5d8f)

**Comment by HyunJae5463** [comment]
Thanks! I copied your settings and now it only takes like 12GB.
