### ISSUE TITLE
[Bug]: Stable Diffusion Extensions doesn't work

### ISSUE THREAD

**Issue by Bongoff** [lshqqytiger/stable-diffusion-webui-directml#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Hello! Well I was using stable diffusion without a graphics card, but now I bought an rx6700xt 12g and watched a few tutorials on how to install stable diffusion to run with an AMD graphics card. so I deleted my current Stable Diffusion folder saving my models folder only.
After that I reinstalled stable diffusion by running "git clone https://github.com/lshqqytiger/stable-diffusion-webui-directml && cd stable-diffusion-webui-directml && git submodule init && git submodule update"
and now for some reason, when I try to search for an extension it does not load and when I install from URL, the extension installs but does not load.
![a](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/83730261/ceca623b-4708-4afc-af00-e5d6845caffe)

take for example Controlnet, the tab does not even appear in the txt to img tab

![b](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/83730261/7e0c2bdf-2679-4287-9d21-2a4d84d2835c)

here is what shows up
venv "C:\Users\Gabriel\stable-diffusion-webui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.1
Commit hash: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/58b9fb5f1db36ea8335b7553b5391e4ec1e53393
Launching Web UI with arguments: --opt-sub-quad-attention --no-half --precision full --xformers
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.0+cpu)
Python 3.10.11 (you have 3.10.6)
Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
Memory-efficient attention, SwiGLU, sparse and more won't be available.
Set XFORMERS_MORE_DETAILS=1 for more details
Loading weights [f71a8b41d1] from C:\Users\Gabriel\stable-diffusion-webui\stable-diffusion-webui-directml\models\Stable-diffusion\bongpng_epicrealism.ckpt
Running on local URL: http://127.0.0.1:7860/

To create a public link, set share=True in launch().
Startup time: 19.4s (launcher: 1.4s, import torch: 6.8s, import gradio: 2.3s, setup paths: 2.7s, other imports: 3.5s, load scripts: 1.9s, create ui: 0.6s, gradio launch: 0.2s).
Creating model from config: C:\Users\Gabriel\stable-diffusion-webui\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: sub-quadratic... done.
Model loaded in 8.9s (load weights from disk: 1.5s, create model: 0.5s, apply weights to model: 0.6s, move model to device: 5.7s, calculate empty prompt: 0.4s).

### Steps to reproduce the problem

1. Go to Stable Diffusion folder
2. Run webui-user.bat
3. Go to Extensions tab

### What should have happened?

Search extension, install, update, run

### Version or Commit where the problem happens

1.5.1

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs

### Cross attention optimization

xformers

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sub-quad-attention --no-half --precision full --xformers
```

### List of extensions

or now I tried ControlNet and ultimate-upscale-for-automatic1111

### Console logs

```Shell
venv "C:\Users\Gabriel\stable-diffusion-webui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.1
Commit hash: 58b9fb5f1db36ea8335b7553b5391e4ec1e53393
Launching Web UI with arguments: --opt-sub-quad-attention --no-half --precision full --xformers
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.0+cpu)
    Python  3.10.11 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Loading weights [f71a8b41d1] from C:\Users\Gabriel\stable-diffusion-webui\stable-diffusion-webui-directml\models\Stable-diffusion\bongpng_epicrealism.ckpt
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 19.4s (launcher: 1.4s, import torch: 6.8s, import gradio: 2.3s, setup paths: 2.7s, other imports: 3.5s, load scripts: 1.9s, create ui: 0.6s, gradio launch: 0.2s).
Creating model from config: C:\Users\Gabriel\stable-diffusion-webui\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: sub-quadratic... done.
Model loaded in 8.9s (load weights from disk: 1.5s, create model: 0.5s, apply weights to model: 0.6s, move model to device: 5.7s, calculate empty prompt: 0.4s).
```

**Comment by Bongoff** [comment]
now I'm having an issue generating images, great
RuntimeError: Could not allocate tensor with 805306368 bytes. There is not enough GPU video memory available!

**Comment by VeteranXT** [comment]
to Launch.py after from modules import launch_utils
Just add this

import ssl
ssl._create_default_https_context = ssl._create_unverified_context
