### ISSUE TITLE
[Bug]: IMG2IMG upscaling not working from fresh install

### ISSUE THREAD

**Issue by jhodak** [lshqqytiger/stable-diffusion-webui-directml#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Installed a fresh version following this guide:
https://community.amd.com/t5/gaming/how-to-running-optimized-automatic1111-stable-diffusion-webui-on/ba-p/625585

in general it is working well, and is quite fast running on a 7900xtx.

Unfortunately when trying to upscale using img 2 img I get the error:

 TypeError: 'StableDiffusionProcessingImg2Img' object is not callable

### Steps to reproduce the problem

1. Generate an image any dimensions with any commands
2. Go to image 2 image to try and upscale 
4. hit generate
5. you will get an error saying 'StableDiffusionProcessingImg2Img' object is not callable

selecting upscale by factor, providing new dimensions, changing from just resize or just resize latent upscaler, adding or removing scripts does not change the behavior

### What should have happened?

It should have generated an image and upscaled if you set either new dimensions, or upscale by factor,

### Version or Commit where the problem happens

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/9a8a2a47f63c3d9b04c014a715f95d680f461963

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--xformers --autolaunch --onnx --backend directml
```

### List of extensions

version: 1.5.1 •  python: 3.10.6  •  torch: 2.0.0+cpu  •  xformers: 0.0.20  •  gradio: 3.32.0

### Console logs

```Shell
*** Arguments: ('task(5t00w7sk31p3y2g)', 0, '', '', [], <PIL.Image.Image image mode=RGBA size=512x512 at 0x2B4ACDF6740>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 0, 512, 512, 1, 0, 0, 32, 0, '', '', '', [], False, [], '', <gradio.routes.Request object at 0x000002B4ACE2E680>, 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
    Traceback (most recent call last):
      File "C:\Users\xxx\stable-diffusion-webui-directml\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\xxx\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "C:\Users\xxx\stable-diffusion-webui-directml\modules\img2img.py", line 232, in img2img
        processed = process_images(p)
      File "C:\Users\xxx\stable-diffusion-webui-directml\modules\processing.py", line 667, in process_images
        return p()
    TypeError: 'StableDiffusionProcessingImg2Img' object is not callable

---
```

**Comment by lshqqytiger** [comment]
Currently, img2img is not available for ONNX. I will add soon.

**Comment by lshqqytiger** [comment]
Img2Img implemented. https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/191#discussioncomment-6833815

**Comment by jhodak** [comment]
Thank you so much, testing it out now!

**Comment by jhodak** [comment]
Unfortunately when running with ONNX this does not seem to be working still.  As the ONNX model is so much more optimized than using the normal setup, I was hoping to be able to upscale by using the img2img.

Thank you for looking into it, when running on ONNX I still get the same errors, and I see you have a lot going on, thank you again!
