### ISSUE TITLE
[Bug]:fatal: No names found, cannot describe anything.

### ISSUE THREAD

**Issue by skywizeskychan** [lshqqytiger/stable-diffusion-webui-directml#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Running with AMD, after a while I will run out of memory, and have to close and restart my computer to clear this.  

Sometimes, (not always) when I then run my webui.settings.bat I will get the error message 
fatal: No names found, cannot describe anything.

And of course then nothing will work.

### Steps to reproduce the problem

1. Go to .... After having run out of memory close all windows and restart
2. Press .... run the webui.bat file
3. ... get the warning message as part of the resulting text in the cmd window

### What should have happened?

It should run normally?

### Version or Commit where the problem happens

Commit hash: 8ea37a924696435e1d777a2d5ab2909d64ce8975

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--opt-sub-quad-attention --lowvram --disable-nan-check
call webui.bat
```

### List of extensions

no

### Console logs

```Shell
venv "C:\Users\skywi\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
NVIDIA driver was found. Automatically changed backend to 'cuda'. You can manually select which backend will be used through '--backend' argument.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: ## 1.4.1
Commit hash: 8ea37a924696435e1d777a2d5ab2909d64ce8975
Installing requirements
Launching Web UI with arguments: --opt-sub-quad-attention --lowvram --disable-nan-check
No module 'xformers'. Proceeding without it.
Loading weights [9c59842129] from C:\Users\skywi\stable-diffusion-webui-directml\models\Stable-diffusion\dosmix_.safetensors
preload_extensions_git_metadata for 7 extensions took 0.00s
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 22.7s (import torch: 6.3s, import gradio: 2.7s, import ldm: 2.2s, other imports: 7.2s, list SD models: 0.1s, load scripts: 1.6s, create ui: 1.5s, gradio launch: 0.7s).
Creating model from config: C:\Users\skywi\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: sub-quadratic... done.
Textual inversion embeddings loaded(0):
Model loaded in 44.0s (load weights from disk: 2.6s, create model: 4.5s, apply weights to model: 23.5s, apply half(): 12.2s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.9s).
```

**Comment by Sparks72** [comment]
I found that to run sd with AMD I needed to uninstall all the nvidia drivers, as it led to conflict
