### ISSUE TITLE
[Bug]: fatal: No names found, cannot describe anything.

### ISSUE THREAD

**Issue by Mirak1052** [lshqqytiger/stable-diffusion-webui-directml#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Downloaded python 3.10.6 added to path and installed git, ran "git clone https://github.com/lshqqytiger/stable-diffusion-webui-directml && cd stable-diffusion-webui-directml && git submodule init && git submodule update" then ran webui-user.bat and it came up with this error "venv "C:\Users\Seven\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything." Tried a fresh boot of windows 10 and still had the same issue. It worked properly once a few weeks ago and now it keeps coming up with that same error

### Steps to reproduce the problem

1. Go to .... stable-diffusion-webui-directml
2. Press .... webui-user.bat
3. ...fatal error

### What should have happened?

properly ran without errors

### Version or Commit where the problem happens

1.5.2?

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs

### Cross attention optimization

Automatic

### Command Line Arguments

```Shell
no
```

### List of extensions

no

### Console logs

```Shell
Creating venv in directory C:\Users\Seven\stable-diffusion-webui-directml\venv using python "C:\Users\Seven\AppData\Local\Programs\Python\Python310\python.exe"
venv "C:\Users\Seven\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.2
Commit hash: 253a6bbfa651168dea13bb37be17e8a47c183bf2
Installing torch and torchvision
Collecting torch==2.0.0
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting torchvision==0.15.1
  Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
Collecting torch-directml
  Using cached torch_directml-0.2.0.dev230426-cp310-cp310-win_amd64.whl (8.2 MB)
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting filelock
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-10.0.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting numpy
  Using cached numpy-1.25.2-cp310-cp310-win_amd64.whl (15.6 MB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.2.0-cp310-cp310-win_amd64.whl (96 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torch-directml
Successfully installed MarkupSafe-2.1.3 certifi-2023.7.22 charset-normalizer-3.2.0 filelock-3.12.2 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.25.2 pillow-10.0.0 requests-2.31.0 sympy-1.12 torch-2.0.0 torch-directml-0.2.0.dev230426 torchvision-0.15.1 typing-extensions-4.7.1 urllib3-2.0.4

[notice] A new release of pip available: 22.2.1 -> 23.2.1
[notice] To update, run: C:\Users\Seven\stable-diffusion-webui-directml\venv\Scripts\python.exe -m pip install --upgrade pip
Installing gfpgan
Installing clip
Installing open_clip
Installing requirements for CodeFormer
Installing requirements
Launching Web UI with arguments: --precision full --no-half
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
                 It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
Traceback (most recent call last):
  File "C:\Users\Seven\stable-diffusion-webui-directml\launch.py", line 39, in <module>
    main()
  File "C:\Users\Seven\stable-diffusion-webui-directml\launch.py", line 35, in main
    start()
  File "C:\Users\Seven\stable-diffusion-webui-directml\modules\launch_utils.py", line 438, in start
    import webui
  File "C:\Users\Seven\stable-diffusion-webui-directml\webui.py", line 38, in <module>
    import torch
  File "C:\Users\Seven\stable-diffusion-webui-directml\venv\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Seven\stable-diffusion-webui-directml\venv\lib\site-packages\torch\lib\c10.dll" or one of its dependencies.
Press any key to continue . . .
```

### Additional information

Worked once a few weeks ago then hasnt since

**Comment by Mirak1052** [comment]
closed and re-ran with arguements and same error but with odd error at the end




venv "C:\Users\Seven\OneDrive\Desktop\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.2
Commit hash: 253a6bbfa651168dea13bb37be17e8a47c183bf2
Launching Web UI with arguments: --precision full --no-half
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Loading weights [4362cfddc4] from C:\Users\Seven\OneDrive\Desktop\stable-diffusion-webui-directml\models\Stable-diffusion\bb95FurryMix_v110.safetensors
Creating model from config: C:\Users\Seven\OneDrive\Desktop\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 16.4s (launcher: 1.1s, import torch: 6.3s, import gradio: 1.6s, setup paths: 1.6s, other imports: 3.1s, load scripts: 1.5s, create ui: 0.8s, gradio launch: 0.4s).
DiffusionWrapper has 859.52 M params.
Applying attention optimization: InvokeAI... done.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
C:\Users\Seven\OneDrive\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\PIL\Image.py:3176: DecompressionBombWarning: Image size (136602400 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

**Comment by inverlock** [comment]
I get this as well. I believe it's an error when git tries to load the tags of a repository with no tags or if it was a shallow clone at some point.

**Comment by mayzon96** [comment]
SAME PROBLEM HELP PLEASE IM DYING I CANT FIND ANYTHING THIS FCKIN ISSUE KILLING ME

**Comment by Dimersion32** [comment]
I have same problem

venv "C:\Users\danii\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: 64e6b0687e182d5f17216755561c9c143d69c220
Installing requirements

And nothing more...

**Comment by Danny-707** [comment]
Could it be because the portable version of SD is installed? Without Git installed in the system

**Comment by thorrican** [comment]
I had kinda the same error codea and for me I solved it by editing the webui_user.bat and adding 
`--skip-torch-cuda-test`  to the line "set COMMANDLINE_ARGS="

**Comment by GiorgioGhisotti** [comment]
I had this issue as well, and adding the `--skip-torch-cuda-test` as suggested above was not enough to solve the issue.

I did find a workaround. Instead of running the batch file, simply run the python launch script directly (after installing the dependencies manually, if necessary):
`python .\launch.py --use-directml`

@mayzon96 hopefully this will give you some relief 😉
