### ISSUE TITLE
[Bug]: Generating images causes driver crash after some time

### ISSUE THREAD

**Issue by Gamemaster2022** [lshqqytiger/stable-diffusion-webui-directml#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Generating images after some time causes driver crash that require reinstall after reboot

### Steps to reproduce the problem

1. Start Stable Diffusion webui directml
2. Start generating more pictures (or turn on "Generate forever", pics are res about 400x300 upscaled to 800x600)
3. Video drivers crash making GPU fans spin at maximum speed (requires restart and reinstalling drivers)

### What should have happened?

SD shouldn't have crashed my PC and kept generating

### Version or Commit where the problem happens

253a6bb (but happened to me at every commit yet)

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--medvram --no-half-vae --no-half --opt-sub-quad-attention --opt-split-attention-v1 --autolaunch --theme=dark
```

### List of extensions

openpose-editor
a1111-sd-webui-tagcomplete
posex-0.4
sd-extension-system-info
sd-webui-controlnet
sd-webui-openpose-editor

### Console logs

```Shell
Can't get the console log as it crashes before I can do anything
```

### Additional information

I am not really sure if it's a problem related with the webui itself but I am still making this issue to let you know about it. Maybe it's a DirectML related problem

This is my specifications: 
AMD Athlon 200GE
24GB RAM
Radeon RX580 8GB

**Comment by lshqqytiger** [comment]
Try under-volting using AMD Software.

**Comment by ocarina0001** [comment]
I'm getting the same issue too, same GPU but different PSU. I just tried to undervolt it by -20% and that didn't stop it so I'm gonna try again but with -50%.

**Comment by Gamemaster2022** [comment]
Problem solved - upgraded to 700W PSU from 500W (it arrived today) and no more problems.

**Comment by Gamemaster2022** [comment]
> 

One question,

how many tabs do you usually have open in your browser?

**Comment by Gamemaster2022** [comment]
So far, closing few tabs in my browser helped a lot

**Comment by Boarlock** [comment]
I have the same issue, I've been generated images for a week now and it just happened.  I have a 500W EVGA PSU and have not overclocked at all.  Been using DirectML to run Stable Diffusion, I have the RX 580 XFX card.  Just underclocked my power by 10% will see if that does the trick.
