### ISSUE TITLE
[Bug]: VRAM memory leak

### ISSUE THREAD

**Issue by cactus24556** [lshqqytiger/stable-diffusion-webui-directml#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I launch the webui from the webui-user.bat and it starts up normally except I notice once the webui is open in my browser my VRAM is filled about to 5GB out of my 8GB. It seems to be happening when it is trying to load the model. So when i try to generate a image it runs out of VRAM in the middle and the generation is stopped. This even happens on a fresh install of the webui where it uses the default model.

Also after trying to generate the image unsuccessfully the VRAM is not released at all. My VRAM is completely full until I shutdown the program.

Another issue is that in the webui I am unable to change which model the generator uses. I pick another model and it shows it processing it but it fails to change and also it takes up my VRAM and does not release any VRAM when it finishes.

### Steps to reproduce the problem

1. Start webui with webui-user.bat
2. Look at task manager and see VRAM is already half used up.
 

### What should have happened?

I should have enough VRAM to generate a 512x512 image without running out of VRAM. My VRAM should be clear if I'm not generating anything.

### Sysinfo

[sysinfo-2023-09-08-20-11.txt](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/12563454/sysinfo-2023-09-08-20-11.txt)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Console logs

```Shell
venv "C:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: 92849df26f73b416d396b95c3fb8c64070fe3ad8
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Loading weights [b4c1d10a2d] from C:\stable-diffusion-webui-directml\models\Stable-diffusion\perfectWorld_v5Baked.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: C:\stable-diffusion-webui-directml\configs\v1-inference.yaml
Startup time: 7.5s (prepare environment: 0.2s, import torch: 2.7s, import gradio: 0.7s, setup paths: 0.7s, initialize shared: 1.0s, other imports: 0.3s, load scripts: 0.9s, create ui: 0.3s, gradio launch: 0.6s).
Applying attention optimization: InvokeAI... done.
Model loaded in 6.7s (load weights from disk: 0.5s, create model: 0.5s, apply weights to model: 4.9s, apply half(): 0.5s, calculate empty prompt: 0.2s).
```

**Comment by lshqqytiger** [comment]
`torch-directml` can't release/collect/empty memory because its tensor implementation inherits OpaqueTensorImpl which can't have storage.
```python
import torch
import torch_directml

device = torch_directml.device()

torch.tensor(1.0).storage() # [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 1]
torch.tensor(1.0).to(device).storage # NotImplementedError: Cannot access storage of OpaqueTensorImpl
```
But `onnxruntime-directml` partially does release memory. If you want something like that, you can use [Olive+ONNX implementation](https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/149) instead.

**Comment by cactus24556** [comment]
Thanks for the response. I'm not sure I want to commit with the olive+onnx. As I would have optimize all the models I use when some commits ago I could generate images just fine without any modifications.

**Comment by cactus24556** [comment]
managed to generate images by using --medvram --medvram-sdxl --opt-split-attention --no-half-vae --disable-nan-check. i guess that's the trick. Even when all the VRAM is full I can generate an image right after I made another image.

**Comment by GeneralVincent1** [comment]
Yes, this is something that AMD users have to find workarounds for while Nvidia users generally have an easier time from what I understand. 

[Here is a great discussion](https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/84) about ways to avoid running out of Vram and having it crash after running it once

**Comment by lshqqytiger** [comment]
You should know: this does not happen only for AMD. This will happen for **ANY** GPUs with `torch-directml`.
Originally, we should use ROCm, a low-level toolkit like CUDA, but we use DirectML because it didn't support Windows (now partially does). This alone, there should not be a memory issue, but there was an issue where `torch-directml`, a plugin library for PyTorch, inherited OpaqueTensorImpl, making it impossible to track the memory of the Tensor.
I don't know if its developers are interested in fixing such issue with `torch-directml`, but if you want to avoid memory issue at this point, you should use `onnxruntime-directml` (implemented with `--onnx` in this repository, but it will be slow if you don't optimize models with Olive), or wait until PyTorch has full support on ROCm.

**Comment by Lamer217** [comment]
Thanks for such a detailed replies, @lshqqytiger.
From this I see my options are following:
- Use the project within a UNIX based system
- Use the `onnxruntime-directml` project in conjunction with this one

I'll try the Linux and ROCm option first, as it seems like the `onnxruntime-directml` solution is not that well established yet.

**Comment by lshqqytiger** [comment]
The Linux + ROCm option will be the best option if you are familiar with the Linux environment. DirectML is the secondary for who is not.

**Comment by johiny** [comment]
> The Linux + ROCm option will be the best option if you are familiar with the Linux environment. DirectML is the secondary for who is not.

I have a doubt the ROCm setup could be possible with WSL? I have been reading that it can access GPU but I don't know if it is compatible with ROCm or someone is working on that
https://learn.microsoft.com/en-us/windows/wsl/tutorials/gpu-compute

**Comment by lshqqytiger** [comment]
ROCm on WSL can not find GPU.
