### ISSUE TITLE
[Bug]: txt2img uses only CPU and not GPU even when it's set to use GPU.

### ISSUE THREAD

**Issue by Blaz1kennBG** [lshqqytiger/stable-diffusion-webui-directml#270]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What happened?

After the whole guide, i tried to create a picture but i noticed that the CPU was maxing out and the GPU was not moving. I have only one argument set: `set COMMANDLINE_ARGS=--no-half `

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
 

### What should have happened?

Use GPU on txt2img instead of CPU

### What browsers do you use to access the UI ?

Google Chrome

### Console logs

```Shell
.
```

### Additional information

No errors whatsoever. Just regular creating but with CPU
[sysinfo-2023-09-09-22-46.txt](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/12566817/sysinfo-2023-09-09-22-46.txt)

**Comment by cheremo** [comment]
Which GPU/ vendor are u talking about?
If you've an AMD-GPU try this (working @7800xt)

`@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--medvram --precision full --no-half --no-half-vae --opt-split-attention --opt-sub-quad-attention --disable-nan-check
set SAFETENSORS_FAST_GPU=1
git pull
call webui.bat
`

**Comment by lshqqytiger** [comment]
Do you have `dml` under `modules` directory?

**Comment by Blaz1kennBG** [comment]
> Do you have `dml` under `modules` directory?

Yes i do have `dml`
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/73253075/ba911420-536a-433c-8642-554daa39af15)

**Comment by Blaz1kennBG** [comment]
> Which GPU/ vendor are u talking about? If you're talking about an AMD-GPU try this (working @7800xt) commandline-args
> 
> ```
> @echo off
> 
> set PYTHON=
> set GIT=
> set VENV_DIR=
> set COMMANDLINE_ARGS=--medvram --precision full --no-half --no-half-vae --opt-split-attention --opt-sub-quad-attention --disable-nan-check
> set SAFETENSORS_FAST_GPU=1
> git pull
> call webui.bat
> ```

AMD RX 6700 XT, I would try that now

**Comment by lshqqytiger** [comment]
Try again with `--backend directml --device-id 0`. (0 is an example. Replace it if you have other cards installed)

**Comment by MariyanEOD** [comment]
> Try again with `--backend directml --device-id 0`. (0 is an example. Replace it if you have other cards installed)

Arguments are as following: `--no-half --backend directml --device-id 0` however i get an error about a `torch_directml` package
```
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "D:\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "D:\stable-diffusion-webui-directml\modules\launch_utils.py", line 476, in start
    import webui
  File "D:\stable-diffusion-webui-directml\webui.py", line 13, in <module>
    initialize.imports()
  File "D:\stable-diffusion-webui-directml\modules\initialize.py", line 34, in imports
    shared_init.initialize()
  File "D:\stable-diffusion-webui-directml\modules\shared_init.py", line 25, in initialize
    dml.initialize()
  File "D:\stable-diffusion-webui-directml\modules\dml\__init__.py", line 40, in initialize
    from modules.dml.backend import DirectML # pylint: disable=ungrouped-imports
  File "D:\stable-diffusion-webui-directml\modules\dml\backend.py", line 4, in <module>
    import torch_directml # pylint: disable=import-error
ModuleNotFoundError: No module named 'torch_directml'
```

**Comment by MariyanEOD** [comment]
Edit:  Activating the virtual environment and doing `pip install torch-directml` worked. The error is gone and supposedly 
`--backend directml ` or `--device-id 0` did fix the problem.
