### ISSUE TITLE
[Feature Request]: FreeU Implementation

### ISSUE THREAD

**Issue by GreenLandisaLie** [lshqqytiger/stable-diffusion-webui-directml#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

[FreeU](https://github.com/ChenyangSi/FreeU) - supposedly improves image quality with no extra costs.
Code got released today and its easy to implement, here's an extension for Automatic1111 already: [link](https://github.com/ljleb/sd-webui-freeu).

Tried it out but fails at this line:

> x_freq = torch.fft.fftn(x, dim=(-2, -1))

Gives the following error:

> [F D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_util.cc:118] Invalid or unsupported data type.

I remember ToMe could not be added because DirectML doesn't support negative dimensions and this is probably the case here as well but I'm no dev so I'll let someone who knows what they are doing take a loot into it.

Please consider adding this if at all possible and if it even works as they claim it does to begin with.

### Proposed workflow

.

**Comment by lshqqytiger** [comment]
This is because the complex types are not implemented in DirectML.
I've asked about complex types support before, but it doesn't appear to be planning at the moment.

**Comment by GreenLandisaLie** [comment]
Yeah nothing we can do about it then. 
I'll keep a eye on it and if they ever add support I shall reopen.
