### ISSUE TITLE
[Feature Request]: Würstchen 2.0

### ISSUE THREAD

**Issue by patientx** [lshqqytiger/stable-diffusion-webui-directml#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

A new diffusion with less system resources needed 

### Proposed workflow

Vlad-diffusion seems to have it.

**Comment by lshqqytiger** [comment]
This repository is based on AUTOMATIC1111/stable-diffusion-webui and I don't want to change many things from it.
