### ISSUE TITLE
[Bug]: VRAM doesn't go down after generating an image.

### ISSUE THREAD

**Issue by aveeeteeeeee2** [lshqqytiger/stable-diffusion-webui-directml#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

OS: Windows 11
GPU: AMD Radeon 6700 XT
VRAM: 12 GB
Processor: AMD Ryzen 7 3700X 8-Core Processor
Primary Memory: 16 GB

I have some VRAM usage when I load up stable diffusion, but it doubles and stays there once I generate an image. If I continue to generate images, they will stack on top of each other and crash unless I close my command prompt window, at which point it will return to normal.

before generating
![KBdfnu8](https://user-images.githubusercontent.com/112240247/222995552-b353ab7d-6a66-48ce-bdd8-51ac93e42fd8.png)

after generating
![U6meZMK](https://user-images.githubusercontent.com/112240247/222995584-0a60e659-bfa3-464f-b756-27c0f2d51b71.png)

### Steps to reproduce the problem

1. Open the WebUI
2. Generate 5 to 6 images
3. Crashes PC or I close the command prompt window to stop it.

### What should have happened?

It shouldn't stack VRAM usage after every generation.

### Commit where the problem happens

ff558348

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Command Line Arguments

```Shell
--lowvram --no-half --precision full --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1
```

### List of extensions

No

### Console logs

```Shell
No certain point, just after every generation.
```

### Additional information

To generate more than a few images I have to close and reopen my command prompt window.

**Comment by Tamar-J** [comment]
same problem here

**Comment by Miraihi** [comment]
This is not a problem, that's how directml stable diffusion works right now. Also if you have 8 Gb graphics card or higher you don't need `--lowvram`, go with `--medvram` instead.

**Comment by lshqqytiger** [comment]
It's because memory cleaning features provided by PyTorch CUDA are not available on DirectML for now.
It seems to be basically same issue with #20 .

**Comment by aveeeteeeeee2** [comment]
> This is not a problem, that's how directml stable diffusion works right now ([Topic 1](https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/19), [Topic 2](https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/17)). Also if you have 8 Gb graphics card or higher you don't need `--lowvram`, go with `--medvram` instead. Collectively waiting for DirectML/Pytorch improvements.

Ah mkay, guess I'll just wait.
