### ISSUE TITLE
[Bug]: last update, doesn't start

### ISSUE THREAD

**Issue by SunGreen777** [lshqqytiger/stable-diffusion-webui-directml#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Already up to date.
venv "w:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: f5c31ac10da7eba201862f4ba0dc338d69db4098
Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.004563700000289828
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Launching Web UI with arguments: --medvram --opt-sdp-no-mem-attention --api
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "w:\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "w:\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "w:\stable-diffusion-webui-directml\modules\launch_utils.py", line 681, in start
    webui.webui()
  File "w:\stable-diffusion-webui-directml\webui.py", line 52, in webui
    initialize.initialize()
  File "w:\stable-diffusion-webui-directml\modules\initialize.py", line 75, in initialize
    initialize_rest(reload_script_modules=False)
  File "w:\stable-diffusion-webui-directml\modules\initialize.py", line 103, in initialize_rest
    sd_models.list_models()
  File "W:\stable-diffusion-webui-directml\modules\sd_models.py", line 207, in list_models
    if jit_model_list is not None:
UnboundLocalError: local variable 'jit_model_list' referenced before assignment
Для продолжения нажмите любую клавишу . . .

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

-

### Sysinfo

-

### Console logs

```Shell
Already up to date.
venv "w:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: f5c31ac10da7eba201862f4ba0dc338d69db4098
Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.004563700000289828
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Launching Web UI with arguments: --medvram --opt-sdp-no-mem-attention --api
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "w:\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "w:\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "w:\stable-diffusion-webui-directml\modules\launch_utils.py", line 681, in start
    webui.webui()
  File "w:\stable-diffusion-webui-directml\webui.py", line 52, in webui
    initialize.initialize()
  File "w:\stable-diffusion-webui-directml\modules\initialize.py", line 75, in initialize
    initialize_rest(reload_script_modules=False)
  File "w:\stable-diffusion-webui-directml\modules\initialize.py", line 103, in initialize_rest
    sd_models.list_models()
  File "W:\stable-diffusion-webui-directml\modules\sd_models.py", line 207, in list_models
    if jit_model_list is not None:
UnboundLocalError: local variable 'jit_model_list' referenced before assignment
Для продолжения нажмите любую клавишу . . .
```

**Comment by Monganose** [comment]
I am also having this issue and I deleted my venv folder and had it rebuild and issue persists.

**Comment by ride5k** [comment]
also reproduced here

**Comment by Mohamed-K-666** [comment]
I'm facing the same error

**Comment by mule-bya** [comment]
> I am also having this issue and I deleted my venv folder and had it rebuild and issue persists.

Me too

**Comment by SunGreen777** [comment]
UPD:
new  installs into a new directory, but also does not start!

**Comment by OperationTwelve** [comment]
until there is a fix do `git checkout 6197993f573b91f8b06889fcd09efd5353dc2cb9` to go back to the previous version

**Comment by SunGreen777** [comment]
> until there is a fix do `git checkout 6197993f573b91f8b06889fcd09efd5353dc2cb9` to go back to the previous version

Thank you!

**Comment by OperationTwelve** [comment]
> > until there is a fix do `git checkout 6197993f573b91f8b06889fcd09efd5353dc2cb9` to go back to the previous version
> 
> Thank you!

No problem and once there is an update do `git checkout master` to go back to using the latest version

**Comment by HernanFoster** [comment]
git checkout 6197993f573b91f8b06889fcd09efd5353dc2cb9    where do I put it? in webui-user.bat?

**Comment by dieselino0** [comment]
Same issue here for me, hopefully it will be fixed soon

**Comment by pw405** [comment]
Same issue for me as well.

**Comment by lshqqytiger** [comment]
Should be solved in the latest commit.

**Comment by pw405** [comment]
> Should be solved in the latest commit.

Yep! Confirmed it launches OK now.  Thank you @lshqqytiger !
