### ISSUE TITLE
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'[Bug]: 

### ISSUE THREAD

**Issue by chaosaiart** [lshqqytiger/stable-diffusion-webui-directml#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

In my community, several people have encountered this issue:
TypeError: AsyncConnectionPool.init() got an unexpected keyword argument 'socket_options'

### Steps to reproduce the problem

Error fixed in a1111, please apply. 
Fix: by adding "httpx==0.24.1" to requirements_versions.txt.

Here are more details about the solution:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13847

### What should have happened?

-

### Sysinfo

-

### Console logs

```Shell
-
```

**Comment by lshqqytiger** [comment]
Merged.
