### ISSUE TITLE
[Bug]: ERROR:onnxruntime.transformers.optimizer:There is no gpu for onnxruntime to do optimization

### ISSUE THREAD

**Issue by MCShotty** [lshqqytiger/stable-diffusion-webui-directml#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Trying to use it at all and I get this error

### Steps to reproduce the problem

1. Run webui 
2. Press generate after inserting any prompt
3. Get error

### What should have happened?

Worked as normal and generate an image

### Sysinfo

{
    "Platform": "Windows-10-10.0.22631-SP0",
    "Python": "3.10.6",
    "Version": "1.6.1",
    "Commit": "03eec1791be011e087985ae93c1f66315d5a250e",
    "Script path": "C:\\Users\\23j20\\Downloads\\SDXL",
    "Data path": "C:\\Users\\23j20\\Downloads\\SDXL",
    "Extensions dir": "C:\\Users\\23j20\\Downloads\\SDXL\\extensions",
    "Checksum": "e696c4776e616a77603a1d3db86fd3ae3d3110fe0335a30195bf425ac73a7850",
    "Commandline": [
        "launch.py",
        "--onnx",
        "--backend",
        "directml"
    ],
    "Torch env info": {
        "torch_version": "1.13.1+cpu",
        "is_debug_build": "False",
        "cuda_compiled_version": null,
        "gcc_version": null,
        "clang_version": null,
        "cmake_version": null,
        "os": "Microsoft Windows 11 Pro",
        "libc_version": "N/A",
        "python_version": "3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] (64-bit runtime)",
        "python_platform": "Windows-10-10.0.22631-SP0",
        "is_cuda_available": "False",
        "cuda_runtime_version": null,
        "cuda_module_loading": "N/A",
        "nvidia_driver_version": null,
        "nvidia_gpu_models": null,
        "cudnn_version": null,
        "pip_version": "pip3",
        "pip_packages": [
            "numpy==1.23.5",
            "open-clip-torch==2.20.0",
            "pytorch-lightning==1.9.4",
            "torch==1.13.1",
            "torch-directml==0.1.13.1.dev230413",
            "torchdiffeq==0.2.3",
            "torchmetrics==0.10.3",
            "torchsde==0.2.5",
            "torchvision==0.14.1"
        ],
        "conda_packages": null,
        "hip_compiled_version": "N/A",
        "hip_runtime_version": "N/A",
        "miopen_runtime_version": "N/A",
        "caching_allocator_config": "",
        "is_xnnpack_available": "True"
    },
    "Exceptions": [],
    "CPU": {
        "model": "Intel64 Family 6 Model 151 Stepping 2, GenuineIntel",
        "count logical": 20,
        "count physical": 12
    },
    "RAM": {
        "total": "32GB",
        "used": "15GB",
        "free": "17GB"
    },
    "GPU": {
        "model": "AMD Radeon RX 7900 XTX",
        "total_memory": 3682304
    },
    "Extensions": [],
    "Inactive extensions": [],
    "Environment": {
        "COMMANDLINE_ARGS": " --onnx --backend directml",
        "GRADIO_ANALYTICS_ENABLED": "False"
    },
    "Config": {
        "samples_save": true,
        "samples_format": "png",
        "samples_filename_pattern": "",
        "save_images_add_number": true,
        "grid_save": true,
        "grid_format": "png",
        "grid_extended_filename": false,
        "grid_only_if_multiple": true,
        "grid_prevent_empty_spots": false,
        "grid_zip_filename_pattern": "",
        "n_rows": -1,
        "font": "",
        "grid_text_active_color": "#000000",
        "grid_text_inactive_color": "#999999",
        "grid_background_color": "#ffffff",
        "enable_pnginfo": true,
        "save_txt": false,
        "save_images_before_face_restoration": false,
        "save_images_before_highres_fix": false,
        "save_images_before_color_correction": false,
        "save_mask": false,
        "save_mask_composite": false,
        "jpeg_quality": 80,
        "webp_lossless": false,
        "export_for_4chan": true,
        "img_downscale_threshold": 4.0,
        "target_side_length": 4000,
        "img_max_size_mp": 200,
        "use_original_name_batch": true,
        "use_upscaler_name_as_suffix": false,
        "save_selected_only": true,
        "save_init_img": false,
        "temp_dir": "",
        "clean_temp_dir_at_start": false,
        "save_incomplete_images": false,
        "outdir_samples": "",
        "outdir_txt2img_samples": "outputs/txt2img-images",
        "outdir_img2img_samples": "outputs/img2img-images",
        "outdir_extras_samples": "outputs/extras-images",
        "outdir_grids": "",
        "outdir_txt2img_grids": "outputs/txt2img-grids",
        "outdir_img2img_grids": "outputs/img2img-grids",
        "outdir_save": "log/images",
        "outdir_init_images": "outputs/init-images",
        "save_to_dirs": true,
        "grid_save_to_dirs": true,
        "use_save_to_dirs_for_ui": false,
        "directories_filename_pattern": "[date]",
        "directories_max_prompt_words": 8,
        "ESRGAN_tile": 192,
        "ESRGAN_tile_overlap": 8,
        "realesrgan_enabled_models": [
            "R-ESRGAN 4x+",
            "R-ESRGAN 4x+ Anime6B"
        ],
        "upscaler_for_img2img": null,
        "face_restoration": false,
        "face_restoration_model": "CodeFormer",
        "code_former_weight": 0.5,
        "face_restoration_unload": false,
        "auto_launch_browser": "Local",
        "show_warnings": false,
        "show_gradio_deprecation_warnings": true,
        "memmon_poll_rate": 8,
        "samples_log_stdout": false,
        "multiple_tqdm": true,
        "print_hypernet_extra": false,
        "list_hidden_files": true,
        "disable_mmap_load_safetensors": false,
        "hide_ldm_prints": true,
        "api_enable_requests": true,
        "api_forbid_local_requests": true,
        "api_useragent": "",
        "unload_models_when_training": false,
        "pin_memory": false,
        "save_optimizer_state": false,
        "save_training_settings_to_txt": true,
        "dataset_filename_word_regex": "",
        "dataset_filename_join_string": " ",
        "training_image_repeats_per_epoch": 1,
        "training_write_csv_every": 500,
        "training_xattention_optimizations": false,
        "training_enable_tensorboard": false,
        "training_tensorboard_save_images": false,
        "training_tensorboard_flush_every": 120,
        "sd_model_checkpoint": "stable-diffusion-v1-5",
        "sd_checkpoints_limit": 1,
        "sd_checkpoints_keep_in_cpu": true,
        "sd_checkpoint_cache": 0,
        "sd_unet": "Automatic",
        "enable_quantization": false,
        "enable_emphasis": true,
        "enable_batch_seeds": true,
        "comma_padding_backtrack": 20,
        "CLIP_stop_at_last_layers": 1,
        "upcast_attn": false,
        "randn_source": "GPU",
        "tiling": false,
        "hires_fix_refiner_pass": "second pass",
        "sdxl_crop_top": 0,
        "sdxl_crop_left": 0,
        "sdxl_refiner_low_aesthetic_score": 2.5,
        "sdxl_refiner_high_aesthetic_score": 6.0,
        "sd_vae_explanation": "<abbr title='Variational autoencoder'>VAE</abbr> is a neural network that transforms a standard <abbr title='red/green/blue'>RGB</abbr>\nimage into latent space representation and back. Latent space representation is what stable diffusion is working on during sampling\n(i.e. when the progress bar is between empty and full). For txt2img, VAE is used to create a resulting image after the sampling is finished.\nFor img2img, VAE is used to process user's input image before the sampling, and to create an image after sampling.",
        "sd_vae_checkpoint_cache": 0,
        "sd_vae": "Automatic",
        "sd_vae_overrides_per_model_preferences": true,
        "auto_vae_precision": true,
        "sd_vae_encode_method": "Full",
        "sd_vae_decode_method": "Full",
        "inpainting_mask_weight": 1.0,
        "initial_noise_multiplier": 1.0,
        "img2img_extra_noise": 0.0,
        "img2img_color_correction": false,
        "img2img_fix_steps": false,
        "img2img_background_color": "#ffffff",
        "img2img_editor_height": 720,
        "img2img_sketch_default_brush_color": "#ffffff",
        "img2img_inpaint_mask_brush_color": "#ffffff",
        "img2img_inpaint_sketch_default_brush_color": "#ffffff",
        "return_mask": false,
        "return_mask_composite": false,
        "enable_mem_pattern": true,
        "enable_mem_reuse": true,
        "collect_garbage_for_each_generation": false,
        "offload_state_dict": false,
        "onnx_olive": "<h2>Olive</h2>",
        "use_just_in_time_optimization": false,
        "cache_optimized_model": false,
        "cross_attention_optimization": "Automatic",
        "s_min_uncond": 0.0,
        "token_merging_ratio": 0.0,
        "token_merging_ratio_img2img": 0.0,
        "token_merging_ratio_hr": 0.0,
        "pad_cond_uncond": false,
        "persistent_cond_cache": true,
        "batch_cond_uncond": true,
        "directml_memory_provider": "Performance Counter",
        "use_old_emphasis_implementation": false,
        "use_old_karras_scheduler_sigmas": false,
        "no_dpmpp_sde_batch_determinism": false,
        "use_old_hires_fix_width_height": false,
        "dont_fix_second_order_samplers_schedule": false,
        "hires_fix_use_firstpass_conds": false,
        "use_old_scheduling": false,
        "interrogate_keep_models_in_memory": false,
        "interrogate_return_ranks": false,
        "interrogate_clip_num_beams": 1,
        "interrogate_clip_min_length": 24,
        "interrogate_clip_max_length": 48,
        "interrogate_clip_dict_limit": 1500,
        "interrogate_clip_skip_categories": [],
        "interrogate_deepbooru_score_threshold": 0.5,
        "deepbooru_sort_alpha": true,
        "deepbooru_use_spaces": true,
        "deepbooru_escape": true,
        "deepbooru_filter_tags": "",
        "extra_networks_show_hidden_directories": true,
        "extra_networks_hidden_models": "When searched",
        "extra_networks_default_multiplier": 1.0,
        "extra_networks_card_width": 0,
        "extra_networks_card_height": 0,
        "extra_networks_card_text_scale": 1.0,
        "extra_networks_card_show_desc": true,
        "extra_networks_add_text_separator": " ",
        "ui_extra_networks_tab_reorder": "",
        "textual_inversion_print_at_load": false,
        "textual_inversion_add_hashes_to_infotext": true,
        "sd_hypernetwork": "None",
        "localization": "None",
        "gradio_theme": "Default",
        "gradio_themes_cache": true,
        "gallery_height": "",
        "return_grid": true,
        "do_not_show_images": false,
        "send_seed": true,
        "send_size": true,
        "js_modal_lightbox": true,
        "js_modal_lightbox_initially_zoomed": true,
        "js_modal_lightbox_gamepad": false,
        "js_modal_lightbox_gamepad_repeat": 250,
        "show_progress_in_title": true,
        "samplers_in_dropdown": true,
        "dimensions_and_batch_together": true,
        "keyedit_precision_attention": 0.1,
        "keyedit_precision_extra": 0.05,
        "keyedit_delimiters": ".,\\/!?%^*;:{}=`~()",
        "keyedit_move": true,
        "quicksettings_list": [
            "sd_model_checkpoint"
        ],
        "ui_tab_order": [],
        "hidden_tabs": [],
        "ui_reorder_list": [],
        "hires_fix_show_sampler": false,
        "hires_fix_show_prompts": false,
        "disable_token_counters": false,
        "add_model_hash_to_info": true,
        "add_model_name_to_info": true,
        "add_user_name_to_info": false,
        "add_version_to_infotext": true,
        "disable_weights_auto_swap": true,
        "infotext_styles": "Apply if any",
        "show_progressbar": true,
        "live_previews_enable": true,
        "live_previews_image_format": "png",
        "show_progress_grid": true,
        "show_progress_every_n_steps": 10,
        "show_progress_type": "Approx NN",
        "live_preview_allow_lowvram_full": false,
        "live_preview_content": "Prompt",
        "live_preview_refresh_period": 1000,
        "live_preview_fast_interrupt": false,
        "hide_samplers": [],
        "eta_ddim": 0.0,
        "eta_ancestral": 1.0,
        "ddim_discretize": "uniform",
        "s_churn": 0.0,
        "s_tmin": 0.0,
        "s_tmax": 0.0,
        "s_noise": 1.0,
        "k_sched_type": "Automatic",
        "sigma_min": 0.0,
        "sigma_max": 0.0,
        "rho": 0.0,
        "eta_noise_seed_delta": 0,
        "always_discard_next_to_last_sigma": false,
        "sgm_noise_multiplier": false,
        "uni_pc_variant": "bh1",
        "uni_pc_skip_type": "time_uniform",
        "uni_pc_order": 3,
        "uni_pc_lower_order_final": true,
        "postprocessing_enable_in_main_ui": [],
        "postprocessing_operation_order": [],
        "upscaling_max_images_in_cache": 5,
        "disabled_extensions": [],
        "disable_all_extensions": "none",
        "restore_config_state_file": "",
        "sd_checkpoint_hash": "6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa"
    },
    "Startup": {
        "total": 8.067688226699829,
        "records": {
            "initial startup": 0.0010001659393310547,
            "prepare environment/checks": 0.011222362518310547,
            "prepare environment/git version info": 0.06258058547973633,
            "prepare environment/clone repositores": 0.1489861011505127,
            "prepare environment/run extensions installers": 0.0,
            "prepare environment": 3.4833614826202393,
            "launcher": 0.011620044708251953,
            "import torch": 2.336815357208252,
            "import gradio": 1.0830433368682861,
            "setup paths": 1.5443236827850342,
            "import ldm": 0.005000114440917969,
            "import sgm": 0.0,
            "initialize shared": 0.9382119178771973,
            "other imports": 0.3214888572692871,
            "opts onchange": 0.010561704635620117,
            "setup SD model": 0.0015053749084472656,
            "setup codeformer": 0.05410480499267578,
            "setup gfpgan": 0.019858121871948242,
            "set samplers": 0.0,
            "list extensions": 0.001001119613647461,
            "restore config state file": 0.0,
            "list SD models": 0.0,
            "list localizations": 0.0,
            "load scripts/custom_code.py": 0.0020012855529785156,
            "load scripts/img2imgalt.py": 0.000997304916381836,
            "load scripts/loopback.py": 0.0,
            "load scripts/outpainting_mk_2.py": 0.0010006427764892578,
            "load scripts/poor_mans_outpainting.py": 0.0,
            "load scripts/postprocessing_codeformer.py": 0.0,
            "load scripts/postprocessing_gfpgan.py": 0.0,
            "load scripts/postprocessing_upscale.py": 0.0009999275207519531,
            "load scripts/prompt_matrix.py": 0.0,
            "load scripts/prompts_from_file.py": 0.0,
            "load scripts/refiner.py": 0.0010530948638916016,
            "load scripts/sd_upscale.py": 0.0,
            "load scripts/seed.py": 0.0,
            "load scripts/xyz_grid.py": 0.0010037422180175781,
            "load scripts/ldsr_model.py": 0.6370980739593506,
            "load scripts/lora_script.py": 0.0935966968536377,
            "load scripts/scunet_model.py": 0.01702713966369629,
            "load scripts/swinir_model.py": 0.015645742416381836,
            "load scripts/hotkey_config.py": 0.0,
            "load scripts/extra_options_section.py": 0.001001119613647461,
            "load scripts": 0.7714247703552246,
            "load upscalers": 0.002348184585571289,
            "refresh VAE": 0.0009982585906982422,
            "refresh textual inversion templates": 0.0,
            "scripts list_optimizers": 0.0,
            "scripts list_unets": 0.0,
            "reload hypernetworks": 0.0011942386627197266,
            "initialize extra networks": 0.004004478454589844,
            "scripts before_ui_callback": 0.0009996891021728516,
            "create ui": 0.4460933208465576,
            "gradio launch": 0.2769594192504883,
            "add APIs": 0.012342214584350586,
            "app_started_callback/lora_script.py": 0.0,
            "app_started_callback": 0.0
        }
    },
    "Packages": [
        "absl-py==2.0.0",
        "accelerate==0.21.0",
        "addict==2.4.0",
        "aenum==3.1.15",
        "aiofiles==23.2.1",
        "aiohttp==3.8.6",
        "aiosignal==1.3.1",
        "alembic==1.12.1",
        "altair==5.1.2",
        "antlr4-python3-runtime==4.9.3",
        "anyio==3.7.1",
        "async-timeout==4.0.3",
        "attrs==23.1.0",
        "basicsr==1.4.2",
        "beautifulsoup4==4.12.2",
        "blendmodes==2022",
        "boltons==23.1.1",
        "cachetools==5.3.2",
        "certifi==2023.7.22",
        "charset-normalizer==3.3.2",
        "clean-fid==0.1.35",
        "click==8.1.7",
        "clip==1.0",
        "colorama==0.4.6",
        "coloredlogs==15.0.1",
        "colorlog==6.7.0",
        "contourpy==1.2.0",
        "cycler==0.12.1",
        "datasets==2.14.6",
        "deprecation==2.1.0",
        "diffusers==0.23.0",
        "dill==0.3.7",
        "einops==0.4.1",
        "exceptiongroup==1.1.3",
        "facexlib==0.3.0",
        "fastapi==0.94.0",
        "ffmpy==0.3.1",
        "filelock==3.13.1",
        "filterpy==1.4.5",
        "flatbuffers==23.5.26",
        "fonttools==4.44.0",
        "frozenlist==1.4.0",
        "fsspec==2023.10.0",
        "ftfy==6.1.1",
        "future==0.18.3",
        "gdown==4.7.1",
        "gfpgan==1.3.8",
        "gitdb==4.0.11",
        "gitpython==3.1.32",
        "google-auth-oauthlib==1.1.0",
        "google-auth==2.23.4",
        "gradio-client==0.5.0",
        "gradio==3.41.2",
        "greenlet==3.0.1",
        "grpcio==1.59.2",
        "h11==0.12.0",
        "httpcore==0.15.0",
        "httpx==0.24.1",
        "huggingface-hub==0.19.0",
        "humanfriendly==10.0",
        "idna==3.4",
        "imageio==2.32.0",
        "importlib-metadata==6.8.0",
        "importlib-resources==6.1.1",
        "inflection==0.5.1",
        "invisible-watermark==0.2.0",
        "jinja2==3.1.2",
        "jsonmerge==1.8.0",
        "jsonschema-specifications==2023.7.1",
        "jsonschema==4.19.2",
        "kiwisolver==1.4.5",
        "kornia==0.6.7",
        "lark==1.1.2",
        "lazy-loader==0.3",
        "lightning-utilities==0.9.0",
        "llvmlite==0.41.1",
        "lmdb==1.4.1",
        "lpips==0.1.4",
        "mako==1.3.0",
        "markdown==3.5.1",
        "markupsafe==2.1.3",
        "matplotlib==3.8.1",
        "mpmath==1.3.0",
        "multidict==6.0.4",
        "multiprocess==0.70.15",
        "networkx==3.2.1",
        "numba==0.58.1",
        "numpy==1.23.5",
        "oauthlib==3.2.2",
        "olive-ai==0.3.3",
        "omegaconf==2.2.3",
        "onnx==1.15.0",
        "onnxruntime-directml==1.16.2",
        "onnxruntime==1.16.2",
        "open-clip-torch==2.20.0",
        "opencv-python==4.8.1.78",
        "optimum==1.14.0",
        "optuna==3.4.0",
        "orjson==3.9.10",
        "packaging==23.2",
        "pandas==2.1.3",
        "piexif==1.1.3",
        "pillow==9.5.0",
        "pip==22.2.1",
        "platformdirs==4.0.0",
        "protobuf==3.20.3",
        "psutil==5.9.5",
        "pyarrow==14.0.1",
        "pyasn1-modules==0.3.0",
        "pyasn1==0.5.0",
        "pydantic==1.10.13",
        "pydub==0.25.1",
        "pyparsing==3.1.1",
        "pyreadline3==3.4.1",
        "pysocks==1.7.1",
        "python-dateutil==2.8.2",
        "python-multipart==0.0.6",
        "pytorch-lightning==1.9.4",
        "pytz==2023.3.post1",
        "pywavelets==1.4.1",
        "pyyaml==6.0.1",
        "realesrgan==0.3.0",
        "referencing==0.30.2",
        "regex==2023.10.3",
        "requests-oauthlib==1.3.1",
        "requests==2.31.0",
        "resize-right==0.0.2",
        "rpds-py==0.12.0",
        "rsa==4.9",
        "safetensors==0.3.1",
        "scikit-image==0.21.0",
        "scipy==1.11.3",
        "semantic-version==2.10.0",
        "sentencepiece==0.1.99",
        "setuptools==63.2.0",
        "six==1.16.0",
        "smmap==5.0.1",
        "sniffio==1.3.0",
        "soupsieve==2.5",
        "sqlalchemy==2.0.23",
        "starlette==0.26.1",
        "sympy==1.12",
        "tb-nightly==2.16.0a20231111",
        "tensorboard-data-server==0.7.2",
        "tifffile==2023.9.26",
        "timm==0.9.2",
        "tokenizers==0.13.3",
        "tomesd==0.1.3",
        "tomli==2.0.1",
        "toolz==0.12.0",
        "torch-directml==0.1.13.1.dev230413",
        "torch==1.13.1",
        "torchdiffeq==0.2.3",
        "torchmetrics==0.10.3",
        "torchsde==0.2.5",
        "torchvision==0.14.1",
        "tqdm==4.66.1",
        "trampoline==0.1.2",
        "transformers==4.32.1",
        "typing-extensions==4.8.0",
        "tzdata==2023.3",
        "urllib3==2.0.7",
        "uvicorn==0.24.0.post1",
        "wcwidth==0.2.9",
        "websockets==11.0.3",
        "werkzeug==3.0.1",
        "xxhash==3.4.1",
        "yapf==0.40.2",
        "yarl==1.9.2",
        "zipp==3.17.0"
    ]
}

### What browsers do you use to access the UI ?

_Edge_

### Console logs

```Shell
Optimizing text_encoder
[2023-11-12 16:54:06,840] [INFO] [engine.py:181:setup_accelerators] Running workflow on accelerator specs: gpu-dml
[2023-11-12 16:54:06,858] [INFO] [engine.py:924:_run_pass] Running pass convert:OnnxConversion
C:\Users\23j20\Downloads\SDXL\modules\dml\hijack\transformers.py:13: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  min = torch.tensor(torch.finfo(dtype).min, device="cpu")
C:\Users\23j20\Downloads\SDXL\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:287: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_weights.size() != (bsz * self.num_heads, tgt_len, src_len):
C:\Users\23j20\Downloads\SDXL\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:295: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if causal_attention_mask.size() != (bsz, 1, tgt_len, src_len):
C:\Users\23j20\Downloads\SDXL\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:327: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_output.size() != (bsz * self.num_heads, tgt_len, self.head_dim):
[2023-11-12 16:54:16,076] [INFO] [engine.py:924:_run_pass] Running pass optimize:OrtTransformersOptimization
ERROR:onnxruntime.transformers.optimizer:There is no gpu for onnxruntime to do optimization.
```

**Comment by lshqqytiger** [comment]
Olive does not support optimization on gpu. You have to optimize your model using cpu and it will automatically does. So you can ignore that error.

**Comment by MCShotty** [comment]
A

> Olive does not support optimization on gpu with DmlExecutionProvider. You have to optimize your model using cpu and it will automatically does. So you can ignore that error.

Ah makes sense, thanks.

**Comment by kazssym** [comment]
I made [this change](https://github.com/microsoft/onnxruntime/pull/17490) in onnxruntime for the upcoming 1.17 and [this unfinished change](https://github.com/microsoft/Olive/pull/651) in Olive. Are you interested in the optimization?

The message indicates optimization by onnxruntime was not failed but just skipped.
