### ISSUE TITLE
 There have been no updates for a long time

### ISSUE THREAD

**Issue by SunGreen777** [lshqqytiger/stable-diffusion-webui-directml#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

 Seunghoon Lee Have you stopped providing support? 
 Can you please tell me who to write to at AMD so they can contact you so they can allocate staff to your team?

Maybe they don't get the request and think that nobody needs it, let's create such a request, let AMD start thinking about comunitti.

If you have a different opinion, just delete this post. Thank you.  : )

**Comment by bebop210** [comment]
I concur.. It seems like all the focus is on Sd.next but that is inferior experience not optimised (I can not even load a model that's been "olived" all flash but completely useless.. Unless you're waiting for rocm like the rest of us.. But I'm still unsure whether to upgrade to torch 2.0 for directml so I have two conda envs but it seems like torch 1.3 can inpaint and enjoy Lora support but 2.0 won't work with either.. But at least they both start and load a model which is more than I can do with SD next vladmandic

**Comment by SunGreen777** [comment]
Seunghoon Lee  Thanks!

**Comment by ArchAngelAries** [comment]
> There is no stable release on the upstream after recent update, there's no update of `torch-directml` after April and I'm busy now due to personal schedules until the end of December. AMD has already released ROCm for Windows and we have to wait for PyTorch to support it.

Whoa, thought they were gonna take forever to release ROCm for windows, hopefully pytorch support for it doesn't take too long to implement.
