### ISSUE TITLE
[Bug]: Cannot create models

### ISSUE THREAD

**Issue by PonyLucky** [lshqqytiger/stable-diffusion-webui-directml#343]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

## The error

When I launch the webui after a fresh install it says :
```
Loading weights [35dae95c74] from /home/louis/AI-tools/stable-diffusion-webui/models/Stable-diffusion/cuteyukimixAdorable_kemiaomiao.safetensors
Creating model from config: /home/louis/AI-tools/stable-diffusion-webui/configs/v1-inference.yaml
webui.sh : ligne 256 : 59765 Erreur de segmentation  (core dumped)"${python_cmd}" -u "${LAUNCH_SCRIPT}" "$@"
```

This error also happens with default `v1-5-pruned-emaonly`.

---

## Context

So when I start the webui.

The web ui starts and after ~5 seconds 3 errors same popups are warning me.
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/60187395/b8fe3cd8-1f74-48a1-bf3b-88054c2d4b59)

Then SD checkpoint stays empty and the server is crashed therefore if I refresh it says the address doesn't exist. When I go back to the terminal, the last three lines are those I copied up there.

---

## My config

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/60187395/b222ea8c-6e73-4b9f-af4c-59d6edf2d684)

---

## Hypothesis

I just changed my graphic card and had a NVIDIA 3080 before, the OS is on a portable SSD and my father's computer has a 4090, I ran this ui both on the 3080 and 4090 with no issues. Maybe the OS don't like switching proprietary nvidia drivers to open source mesa on the fly ?

### Steps to reproduce the problem

1. Fresh install of stable-diffusion-webui
2. wait for the app to download then load and crash.

### What should have happened?

created the model from the safe sensors, so I can start doing what this tool does the best.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2023-12-27-14-52.json](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/13779370/sysinfo-2023-12-27-14-52.json)

### Console logs

```Shell
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on louis user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: 
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Style database not found: /home/louis/AI-tools/stable-diffusion-webui/styles.csv
Calculating sha256 for /home/louis/AI-tools/stable-diffusion-webui/models/Stable-diffusion/cuteyukimixAdorable_kemiaomiao.safetensors: Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 8.5s (prepare environment: 2.2s, import torch: 2.3s, import gradio: 0.6s, setup paths: 1.7s, other imports: 0.5s, load scripts: 0.3s, create ui: 0.4s, gradio launch: 0.3s).
35dae95c7495f1a28d4d1f916d7276db9ed622cf9364acb40d1a8f042460c01c
Loading weights [35dae95c74] from /home/louis/AI-tools/stable-diffusion-webui/models/Stable-diffusion/cuteyukimixAdorable_kemiaomiao.safetensors
Creating model from config: /home/louis/AI-tools/stable-diffusion-webui/configs/v1-inference.yaml
webui.sh : ligne 256 : 65402 Erreur de segmentation  (core dumped)"${python_cmd}" -u "${LAUNCH_SCRIPT}" "$@"
```
```


### Additional information

Changed GPU recently, had 3080 from nvidia and now 7800XT from AMD. Did all updates.

**Comment by lshqqytiger** [comment]
Repo miss. Please move to [upstream](https://github.com/AUTOMATIC1111/stable-diffusion-webui).
