### ISSUE TITLE
[Bug]: Different outputs than Nvidia GPUs, with identical prompts and seeds

### ISSUE THREAD

**Issue by Magiwarriorx** [lshqqytiger/stable-diffusion-webui-directml#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When generating an image with a specific seed and prompt, images generated differ from images generated on the main Automatic1111 branch.

Result from SD1.5, with a seed of "100" and a prompt of "apple" on Euler A
![00012-100](https://user-images.githubusercontent.com/76668941/224246520-95e7089e-a406-4170-a28d-da35b2b4f3ba.png)

Result from the main Automatic1111 branch, with an Nvidia GPU. SD1.5, with a seed of "100" and a prompt of "apple" on Euler A

![00578-100-apple](https://user-images.githubusercontent.com/76668941/224248125-1fb53190-9ab5-4d07-925e-20130779dea8.png)

### Steps to reproduce the problem

1. Generate an image of your choosing, noting the prompt, seed, and model
2. Install an Nvidia GPU and the main Automatic1111 branch
3. Attempt to replicate the image with the same settings

### What should have happened?

The images generated should match

### Commit where the problem happens

https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/ff558348682fea569785dcfae1f1282cfbefda6b

### Command Line Arguments

```Shell
--opt-split-attention-v1 --opt-sub-quad-attention --always-batch-cond-uncond --disable-nan-check --sub-quad-kv-chunk-size 512 --sub-quad-q-chunk-size 512 --sub-quad-chunk-threshold 25 --no-half --no-half-vae --precision full --medvram
```

### List of extensions

No

### Console logs

```Shell
Log not saved, and no longer have AMD GPU (see below)
```

### Additional information

I recently purchased a 7900XT, and noticed I could no longer replicate images with specific prompts. I returned it this afternoon, but decided to generate a side-by-side before I uninstalled it. Sadly this means I am no longer able to generate the bugged images.

**Comment by lshqqytiger** [comment]
Each CUDA device and DirectML device generates different images although you use same seed, prompt and configurations.
It is similar to using xformers on NVIDIA device, resulting in different results than otherwise.
