### ISSUE TITLE
[Bug]: Error appears when starting webui

### ISSUE THREAD

**Issue by Hunter9886** [lshqqytiger/stable-diffusion-webui-directml#382]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

I opened webui and this error appears , at first i couldnt it didnt even start the webui but now it does, but the error still appears

-pytorch_lightning.utilities bug
-ONNX bug

### Steps to reproduce the problem

1- start webui-user.bat
2- error appears

### What should have happened?

webui starts with no bugs or erros 

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

[sysinfo-2024-02-11-22-55.json](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/14234361/sysinfo-2024-02-11-22-55.json)

### Console logs

```Shell
C:\Users\Username\Desktop\stable-diffusion-webui-directml>git pull
Already up to date.
venv "C:\Users\Username\Desktop\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.7.0
Commit hash: 03a88617fcd9442313ce2ed7facfecf6cdf72c36
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\Username\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Collecting onnxruntime-gpu
  Using cached onnxruntime_gpu-1.17.0-cp310-cp310-win_amd64.whl (148.6 MB)
Requirement already satisfied: numpy>=1.21.6 in c:\users\Username\desktop\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime-gpu) (1.23.5)
Requirement already satisfied: packaging in c:\users\Username\desktop\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime-gpu) (23.2)
Requirement already satisfied: sympy in c:\users\Username\desktop\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime-gpu) (1.12)
Requirement already satisfied: coloredlogs in c:\users\Username\desktop\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime-gpu) (15.0.1)
Requirement already satisfied: protobuf in c:\users\Username\desktop\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime-gpu) (3.20.3)
Requirement already satisfied: flatbuffers in c:\users\Username\desktop\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime-gpu) (23.5.26)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\Username\desktop\stable-diffusion-webui-directml\venv\lib\site-packages (from coloredlogs->onnxruntime-gpu) (10.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\Username\desktop\stable-diffusion-webui-directml\venv\lib\site-packages (from sympy->onnxruntime-gpu) (1.3.0)
Requirement already satisfied: pyreadline3 in c:\users\Username\desktop\stable-diffusion-webui-directml\venv\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-gpu) (3.4.1)
Installing collected packages: onnxruntime-gpu
Error: The 'onnxruntime-gpu' distribution was not found and is required by the application
```

**Comment by Hunter9886** [comment]
the pytorch_lightning.utilities bug is the most one im worried about because i dont want problems while using stable diffiusion, ill just wait for an answer maybe i messed somthing up myself

**Comment by lshqqytiger** [comment]
Run `git pull` and add `--skip-ort`

**Comment by Hunter9886** [comment]
> Run `git pull` and add `--skip-ort`

this worked thanks!

the bug didn't show up again after adding  --skip-ort 

i will close the issue.

**Comment by Hunter9886** [comment]
i reopend the isse because the same or a similar bug appears.

i git pull and add --skip-ort but this 1 bug came back again :

(stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
rank_zero_deprecation)




[Console] :

C:\Users\Username\Desktop\stable-diffusion-webui-directml>git pull
Already up to date.
venv "C:\Users\Username\Desktop\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\Username\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --skip-ort --use-directml --medvram --use-cpu-torch --no-half --precision full --opt-split-attention-v1 --disable-nan-check --no-half-vae --skip-version-check --update-all-extensions --theme dark --autolaunch
Loading weights [6ce0161689] from C:\Users\Username\Desktop\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\Users\Username\Desktop\stable-diffusion-webui-directml\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 6.2s (prepare environment: 8.6s, initialize shared: 1.6s, other imports: 0.3s, load scripts: 2.4s, create ui: 0.9s, gradio launch: 0.6s).
Applying attention optimization: V1... done.
Model loaded in 5.0s (load weights from disk: 1.0s, create model: 0.7s, apply weights to model: 2.6s, calculate empty prompt: 0.6s).


i can generate images and at the same speed as before so i think its not using the cpu, but concerned about the pytorch-lightning bug. is this a bug because of some new updates?

**Comment by Hunter9886** [comment]
> i reopend the isse because the same or a similar bug appears.
> 
> i git pull and add --skip-ort but this 1 bug came back again :
> 
> (stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead. rank_zero_deprecation)
> 
> [Console] :
> 
> C:\Users\Username\Desktop\stable-diffusion-webui-directml>git pull Already up to date. venv "C:\Users\Username\Desktop\stable-diffusion-webui-directml\venv\Scripts\Python.exe" fatal: No names found, cannot describe anything. Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] Version: 1.8.0-RC Commit hash: [25a3b6c](https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a) no module 'xformers'. Processing without... no module 'xformers'. Processing without... No module 'xformers'. Proceeding without it. C:\Users\Username\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead. rank_zero_deprecation( Launching Web UI with arguments: --skip-ort --use-directml --medvram --use-cpu-torch --no-half --precision full --opt-split-attention-v1 --disable-nan-check --no-half-vae --skip-version-check --update-all-extensions --theme dark --autolaunch Loading weights [6ce0161689] from C:\Users\Username\Desktop\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors Creating model from config: C:\Users\Username\Desktop\stable-diffusion-webui-directml\configs\v1-inference.yaml Running on local URL: http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`. Startup time: 6.2s (prepare environment: 8.6s, initialize shared: 1.6s, other imports: 0.3s, load scripts: 2.4s, create ui: 0.9s, gradio launch: 0.6s). Applying attention optimization: V1... done. Model loaded in 5.0s (load weights from disk: 1.0s, create model: 0.7s, apply weights to model: 2.6s, calculate empty prompt: 0.6s).
> 
> i can generate images and at the same speed as before so i think its not using the cpu, but concerned about the pytorch-lightning bug. is this a bug because of some new updates?

**Comment by lshqqytiger** [comment]
It is not a bug as it is a warning, not an error.

**Comment by Hunter9886** [comment]
> It is not a bug as it is a warning, not an error.

i see, alright then i will close this issue again.

thanks as always.
