### ISSUE TITLE
[Bug]: Error: The 'onnxruntime-gpu' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by SunGreen777** [lshqqytiger/stable-diffusion-webui-directml#383]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [x] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I have an error, does anyone know what it is?
Error: The 'onnxruntime-gpu' distribution was not found and is required by the application

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/61922120/b0dfb1a0-1d0f-419d-aab3-a72e105d387a)

### Steps to reproduce the problem

-

### What should have happened?

-

### Sysinfo

-

### Console logs

```Shell
-
```

**Comment by waylaa** [comment]
Did you follow the steps from [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs)?

After that, if you want ONNX to use DirectML, follow [this](https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/149#discussioncomment-8392257)

**Comment by lshqqytiger** [comment]
Add `--skip-ort` if you don't want ONNX.

**Comment by SunGreen777** [comment]
This is a little confusing, I don’t understand at all whether it is needed or not, and if it is better, faster, then why is it not enabled by default? Can explain please )

**Comment by lshqqytiger** [comment]
ONNX is slightly fast, Olive optimized ONNX model is much faster. But the overhead follows. (model conversion and optimization)

**Comment by SunGreen777** [comment]
> ONNX is slightly fast, Olive optimized ONNX model is much faster. But the overhead follows. (model conversion and optimization)

I'm understood, thank you :)

**Comment by vutym** [comment]
open CMD as administrator  or  Consider using the `--user` option or check the permissions.
>pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/

**Comment by e2heintz** [comment]
I had the same error. Partially managed to fix it, but only partially.

I tried using Forge yesterday and it wasn't working properly. Came back to Directml this morning and had lots of errors, ending up with this 'no onnx runtime' thing. Now webui bypassed both my GPU-s and generated on the CPU.

What I did:
1. Deleted venv fom Directml folder : no help
2. pip install torch-directml and onnxruntime-gpu : no help
3. Completely deleted both the Forge folder and the Directml folder, then git pull, then added torch-directml to requirements, added cmd args --use-directml --skip-ort : somewhat working, but…

I cannot use --device-id. Getting ‘invalid string’. Which is very bad. I really really really need that other GPU with its clean vram untouched by the OS and all the apps.

**Comment by e2heintz** [comment]
Update:
Uninstalled Python and Git. Deleted webui folder comlepely. Restarted. Reinstalled Python and Git. Git pulled webui folder.
SD is working with --skip-torch-cuda-test --use-directml, but it is using the wrong GPU. I don't want it to use my display-out GPU, I want it to use my secondary GPU.
When adding --device-id, I get this error "'onnxruntime-gpu' distribution was not found' and "invalid device string".
--skip-ort does not help.

**Comment by luckyzsd1975** [comment]
![image](https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu/assets/172060035/2bc148da-bd63-46cd-a3ad-75b628406edb)
已经安装了pip install onnxruntime，但在运行open-webui serve时还是报上面的错误，who knows the reason?

**Comment by Chr-Wol** [comment]
get the same issue, have you got help to solve it?

**Comment by serhiy-popov** [comment]
> ![image](https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu/assets/172060035/2bc148da-bd63-46cd-a3ad-75b628406edb) 已经安装了pip install onnxruntime，但在运行open-webui serve时还是报上面的错误，who knows the reason?

If you see this message in the beginning -  Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
Try to install vc_redist.x64
then run: open-webui serve
