### ISSUE TITLE
[Bug]: Missing sampling method when use olive ONNX directml webui

### ISSUE THREAD

**Issue by fanksid** [lshqqytiger/stable-diffusion-webui-directml#393]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Many thanks to stable-diffusion-webui-directml for making AMD GPU users to use stable diffusion more efficiently. I use it with olive ONNX. When start webui, there are only few old sampling method available:
![Screenshot 2024-02-24 183737](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/13077605/2dc69004-f120-4c5b-8895-ca53105e3dc2)
samplers_k_diffusion has correct list element but can't load in webui:
![Screenshot 2024-02-24 223009](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/13077605/5785d66a-0fc0-4738-a336-b76e1c755ef0)

### Steps to reproduce the problem

1. Start webui with code: ` webui.bat --use-cpu-torch  --skip-torch-cuda-test`
2. Enable ONNX feature 
![Screenshot 2024-02-24 223252](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/13077605/9c421a8e-0abb-45ea-a660-df69961a513b)
3. Check sampling method in webui

### What should have happened?

WebUI should load all sampling method in samplers_k_diffusion.

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

[sysinfo-2024-02-24-14-36.json](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/14393192/sysinfo-2024-02-24-14-36.json)

### Console logs

```Shell
venv "F:\SD\refactor-olive\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
NVIDIA driver was found.
fatal: No names found, cannot describe anything.
Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Version: 1.7.0
Commit hash: 601f7e3704707d09ca88241e663a763a2493b11a
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
F:\SD\refactor-olive\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-cpu-torch --skip-torch-cuda-test
Style database not found: F:\SD\refactor-olive\stable-diffusion-webui-directml\styles.csv
Warning: caught exception 'No CUDA GPUs are available', memory monitor disabled
F:\SD\refactor-olive\stable-diffusion-webui-directml\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
ONNX: selected=DmlExecutionProvider, available=['DmlExecutionProvider', 'CPUExecutionProvider']
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 5.7s (prepare environment: 11.6s, import ldm: 0.1s, initialize shared: 1.8s, setup codeformer: 0.1s, load scripts: 1.6s, create ui: 0.8s, gradio launch: 0.6s).
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Applying attention optimization: InvokeAI... done.
```

### Additional information

GPU AMD 6750xt.
Driver version 24.1.1

**Comment by lshqqytiger** [comment]
This repository has limited support for ONNX. For full support, refer to [SD.Next](https://github.com/vladmandic/automatic). [Wiki](https://github.com/vladmandic/automatic/wiki/ONNX-Runtime-&-Olive)
