### ISSUE TITLE
[Bug]: Unable to launch ui / load model(s)

### ISSUE THREAD

**Issue by essigwurst** [lshqqytiger/stable-diffusion-webui-directml#399]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When launching the WebUI it crashes after a few (~1 to 5) seconds after the browser opens. 

Everything seems to be installing fine, no warnings or errors are reported. When the UI launches (e.g. opens the browser), it takes about 1 to 5 seconds until a memory access violation "Speicherzugriffsfehler" is thrown.

### Steps to reproduce the problem

1. Get a clean installation
2. Launch via ./webui.sh
3. Wait, until everything is installed
4. Wait, until the browser launches
5. The application crashes in about 1 to 5 seconds
(6. Browser reports "connection errored out", obviously)

### What should have happened?

The application should not throw a memory access violation.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo.json](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/14422969/sysinfo.json)

### Console logs

```Shell
https://pastebin.com/uT2RGPyQ
```

### Additional information

All latest system packages and drivers installed.

**Comment by lshqqytiger** [comment]
Go to https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues

**Comment by essigwurst** [comment]
Note for anyone stumbling across this issue, adding the following line into `webui-user.sh` fixed it:
`export HSA_OVERRIDE_GFX_VERSION=11.0.0`
