### ISSUE TITLE
[Bug]: Couldn't find Stable Diffusion in any of

### ISSUE THREAD

**Issue by kirill-21** [lshqqytiger/stable-diffusion-webui-directml#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![image](https://user-images.githubusercontent.com/63228361/219365595-d1155715-3996-49da-a843-66f41ed28fec.png)

I followed this guide, opened webui-user.bat and got this error 

![image](https://user-images.githubusercontent.com/63228361/219365683-a49b6088-e89e-40e0-a22d-572d40e605f7.png)

I've tried to clone this repo git clone https://github.com/Stability-AI/stablediffusion repositories/stable-diffusion-stability-ai to \repositories folder but that leads to "ModuleNotFoundError: No module named 'k_diffusion'" error
![image](https://user-images.githubusercontent.com/63228361/219366583-4b2dc834-13bf-4372-b84b-c352a7690c2f.png)
![image](https://user-images.githubusercontent.com/63228361/219366615-8b5aeec8-5a74-424a-b7f4-8e63060aa469.png)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

WeUI should have been launched

### Commit where the problem happens

a0f4cd6fdd2b7ef3e2b666694f1a1ca13ee17066

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
venv "C:\Applications\Development\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a0f4cd6fdd2b7ef3e2b666694f1a1ca13ee17066
Installing requirements for Web UI
Launching Web UI with arguments:
Memory optimization for DirectML is disabled. Because this is not Windows platform.
Traceback (most recent call last):
  File "C:\Applications\Development\stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "C:\Applications\Development\stable-diffusion-webui-directml\launch.py", line 344, in start
    import webui
  File "C:\Applications\Development\stable-diffusion-webui-directml\webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "C:\Applications\Development\stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "C:\Applications\Development\stable-diffusion-webui-directml\modules\shared.py", line 12, in <module>
    import modules.interrogate
  File "C:\Applications\Development\stable-diffusion-webui-directml\modules\interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "C:\Applications\Development\stable-diffusion-webui-directml\modules\paths.py", line 26, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['C:\\Applications\\Development\\stable-diffusion-webui-directml\\repositories/stable-diffusion-stability-ai', '.', 'C:\\Applications\\Development']
```

**Comment by kirill-21** [comment]
As a temporary solution i renamed stablediffusion-directml to stable-diffusion-stability-ai and k-diffusion-directml to k-diffusion. I guess this paths should be added to code

**Comment by lshqqytiger** [comment]
I recommend to use `git submodule`.
```
$ git submodule init
$ git submodule update
```

**Comment by NotSoCommonSense** [comment]
> 

What do you mean by this? I'm having the same issue.

**Comment by lshqqytiger** [comment]
You can clone other repositories into a repository (or its child directory) using git submodule.
[What is git submodule?](https://git-scm.com/docs/gitsubmodules)
