### ISSUE TITLE
Error using 'restore faces' after 1.8.0-RC 

### ISSUE THREAD

**Issue by macacafoo** [lshqqytiger/stable-diffusion-webui-directml#407]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After update to 1.8.0-RC when enabling 'restore faces' the image is generated but no face correction is applied. 

### Steps to reproduce the problem

enable 'restore faces'
press generate

### What should have happened?

faces a bit better

### Sysinfo

.

### Console logs

```Shell
WARNING:modules.face_restoration_utils:Unable to load face-restoration model
Traceback (most recent call last):
  File "C:\Diffusion\stable-diffusion-webui-directml\modules\face_restoration_utils.py", line 150, in restore_with_helper
    self.net = self.load_net()
  File "C:\Diffusion\stable-diffusion-webui-directml\modules\codeformer_model.py", line 37, in load_net
    return modelloader.load_spandrel_model(
  File "C:\Diffusion\stable-diffusion-webui-directml\modules\modelloader.py", line 150, in load_spandrel_model
    model_descriptor = spandrel.ModelLoader(device=device).load_from_file(str(path))
  File "C:\Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\spandrel\__helpers\loader.py", line 41, in load_from_file
    state_dict = self.load_state_dict_from_file(path)
  File "C:\Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\spandrel\__helpers\loader.py", line 60, in load_state_dict_from_file
    state_dict = self._load_pth(path)
  File "C:\Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\spandrel\__helpers\loader.py", line 82, in _load_pth
    return torch.load(
  File "C:\Diffusion\stable-diffusion-webui-directml\modules\safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "C:\Diffusion\stable-diffusion-webui-directml\modules\safe.py", line 156, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1172, in _load    result = unpickler.load()
  File "C:\Program Files\Python310\lib\pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "C:\Program Files\Python310\lib\pickle.py", line 1254, in load_binpersid
    self.append(self.persistent_load(pid))
  File "C:\Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1086, in restore_location
    return default_restore_location(storage, str(map_location))
  File "C:\Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 220, in default_restore_location
    raise RuntimeError("don't know how to restore data location of "
RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with privateuseone:0)
```

### Additional information

I have already removed the old 'venv'. Same error with CodeFormer and/or GFPGAN. The models are installed in their respective directories.

**Comment by lshqqytiger** [comment]
https://github.com/microsoft/DirectML/issues/196

**Comment by macacafoo** [comment]
Hi lshqqytiger, thanks for your reply. I'll revert back to 1.7 as SD.Next is slow than your fork on my aging GCN card.

**Comment by Zira3l137** [comment]
> Hi lshqqytiger, thanks for your reply. I'll revert back to 1.7 as SD.Next is slow than your fork on my aging GCN card.

Hi, did reverting back to 1.7 help? If yes, could you please tell me how to do that?

**Comment by macacafoo** [comment]
Hi Zira3l137, yes, going back to version 1.7 brought back the function of restoring faces. I chose to go back to commit '601f7e3704707d09ca88241e663a763a2493b11a' (fix sysinfo), from February 16, which was the last update I did and everything worked.

The command I used was (without quotes): "git reset --hard 601f7e3"

Keep in mind that any changes made to 'webui-user.bat' will be lost, so I recommend backing up the settings before reverting to 1.7. As a precaution, make a copy of the 'config.json', 'ui-config.json' and 'styles.csv' files as well, even though these weren't modified when reverting, it's better to be on the safe side.

Another, less drastic, option is to use the CPU for functions that use CodeFormer and GFPGAN, by adding the command '--use-cpu gfpgan codeformer' to your 'webui-user.bat'. As my processor is a Ryzen gen1, using CodeFormer (my favorite) on the CPU was very slow, which is why I personally chose to revert to 1.7.

Hope I've helped and good luck with the process.

**Comment by Zira3l137** [comment]
> Hi Zira3l137, yes, going back to version 1.7 brought back the function of restoring faces. I chose to go back to commit '601f7e3704707d09ca88241e663a763a2493b11a' (fix sysinfo), from February 16, which was the last update I did and everything worked.
> 
> The command I used was (without quotes): "git reset --hard 601f7e3"
> 
> Keep in mind that any changes made to 'webui-user.bat' will be lost, so I recommend backing up the settings before reverting to 1.7. As a precaution, make a copy of the 'config.json', 'ui-config.json' and 'styles.csv' files as well, even though these weren't modified when reverting, it's better to be on the safe side.
> 
> Another, less drastic, option is to use the CPU for functions that use CodeFormer and GFPGAN, by adding the command '--use-cpu gfpgan codeformer' to your 'webui-user.bat'. As my processor is a Ryzen gen1, using CodeFormer (my favorite) on the CPU was very slow, which is why I personally chose to revert to 1.7.
> 
> Hope I've helped and good luck with the process.

Thank you so much my friend, you've no idea how much you've helped me! Cheers!

**Comment by HyunJae5463** [comment]
> Hi Zira3l137, yes, going back to version 1.7 brought back the function of restoring faces. I chose to go back to commit '601f7e3704707d09ca88241e663a763a2493b11a' (fix sysinfo), from February 16, which was the last update I did and everything worked.
> 
> The command I used was (without quotes): "git reset --hard [601f7e3](https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/601f7e3704707d09ca88241e663a763a2493b11a)"
> 
> Keep in mind that any changes made to 'webui-user.bat' will be lost, so I recommend backing up the settings before reverting to 1.7. As a precaution, make a copy of the 'config.json', 'ui-config.json' and 'styles.csv' files as well, even though these weren't modified when reverting, it's better to be on the safe side.
> 
> Another, less drastic, option is to use the CPU for functions that use CodeFormer and GFPGAN, by adding the command '--use-cpu gfpgan codeformer' to your 'webui-user.bat'. As my processor is a Ryzen gen1, using CodeFormer (my favorite) on the CPU was very slow, which is why I personally chose to revert to 1.7.
> 
> Hope I've helped and good luck with the process.

Thanks, the --use-cpu gfpgan codeformer command works great. However, after one generation, Stable Diffusion crashes and it has to be restarted every time. Any idea why this happens? So I can generate one image, the second one just crashes SD without an Error. It only says "Press any keyto continue..."

**Comment by macacafoo** [comment]
Hi HyunJae5463, I've never come across this type of error. Maybe you can send the ´logs' to a file and get an error message that will give you a clue.

Using '--use-cpu gfpgan codeformer' I couldn't reproduce the error you mentioned. I generated consecutive images with the 'restore faces' function enabled. No errors either with CodeFormer or GFPGAN. All the images had a satisfactory correction. Using the CPU for face correction works fine here in 1.8.0.

I don't use this extension, so I don't know if it would break here too. Perhaps opening an issue with the developers of the 'FaceSwap' extension would help.

**Comment by HyunJae5463** [comment]
> Hi HyunJae5463, I've never come across this type of error. Maybe you can send the ´logs' to a file and get an error message that will give you a clue.
> 
> Using '--use-cpu gfpgan codeformer' I couldn't reproduce the error you mentioned. I generated consecutive images with the 'restore faces' function enabled. No errors either with CodeFormer or GFPGAN. All the images had a satisfactory correction. Using the CPU for face correction works fine here in 1.8.0.
> 
> I don't use this extension, so I don't know if it would break here too. Perhaps opening an issue with the developers of the 'FaceSwap' extension would help.

Doesn't seem to be extension related. I noticed it even happens when I go to Extras and just enable CodeFormer for example from there.
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/107355366/37a8ace6-2a4c-4d1c-b75c-0fc0bea5892e)
After that I have to restart SD.
The same happens on A1111 fork, but for some reason not on SD.Next.

**Comment by macacafoo** [comment]
Sorry HyunJae5463, inconclusive.

**Comment by riccorohl** [comment]
How did you revert to 1.7.0?

**Comment by lshqqytiger** [comment]
> How did you revert to 1.7.0?

https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/407#issuecomment-1985705125

**Comment by lshqqytiger** [comment]
Fixed
