### ISSUE TITLE
[Bug]: raise RuntimeError(

### ISSUE THREAD

**Issue by mollenmest** [lshqqytiger/stable-diffusion-webui-directml#422]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

venv "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a
Traceback (most recent call last):
  File "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\modules\launch_utils.py", line 568, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Press any key to continue . . .

 böyle bir hata almaktayım ? 

### Steps to reproduce the problem

    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

### What should have happened?

Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a

### What browsers do you use to access the UI ?

Other

### Sysinfo

https://prnt.sc/U-EOtTSz3Kp7

### Console logs

```Shell
--skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
```

### Additional information

İşletim Sistemi Adı	Microsoft Windows 11 Pro
Amd Rx6750xt 12 GB ekran kartım var bu hatayı alıyorum
İşlemci	AMD Ryzen 7 5800X 8-Core Processor, 3801 Mhz, 8 Çekirdek, 16 Mantıksal İşlemci
Temel Kart Ürünü	B450 TOMAHAWK MAX (MS-7C02)
Yüklü Fiziksel Bellek (RAM)	32,0 GB

**Comment by lshqqytiger** [comment]
DirectML: add `--use-directml`
ZLUDA: add `--use-zluda`

**Comment by hwwgh555** [comment]
> DirectML: add `--use-directml` ZLUDA: add `--use-zluda`

I don't understand "ZLUDA: add --use-zluda"

I just do these steps and successfully run it.

### step1:  add params "--use-directml" for "webui-user.bat"
```
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
# modifed line
set COMMANDLINE_ARGS=--use-directml

call webui.bat
```

### step2 :  remove directory "venv"
if you have run "webui-user.bat", the directory "venv" will exist.

### step3:  run modified "webui-user.bat" again

**Comment by mollenmest** [comment]
dediğinizi yaptıktan sonra böyle hata aldım 
'#' is not recognized as an internal or external command,
operable program or batch file.
Creating venv in directory C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\venv using python "C:\Users\dulda\AppData\Local\Programs\Python\Python312\python.exe"
venv "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a
Installing torch and torchvision
ERROR: Could not find a version that satisfies the requirement torch==2.0.0 (from versions: 2.2.0, 2.2.1)
ERROR: No matching distribution found for torch==2.0.0
Traceback (most recent call last):
  File "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\modules\launch_utils.py", line 561, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\modules\launch_utils.py", line 121, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install torch==2.0.0 torchvision==0.15.1 torch-directml
Error code: 1
Press any key to continue . . .

**Comment by lshqqytiger** [comment]
Python 3.12 is not compatible with DirectML. Downgrade to <=3.10.

**Comment by mollenmest** [comment]
Creating venv in directory C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\venv using python "C:\Users\dulda\AppData\Local\Programs\Python\Python310\python.exe"
venv "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a
Installing torch and torchvision
Collecting torch==2.0.0
  Downloading torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.3/172.3 MB 5.0 MB/s eta 0:00:00
Collecting torchvision==0.15.1
  Downloading torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 5.4 MB/s eta 0:00:00
Collecting torch-directml
  Downloading torch_directml-0.2.0.dev230426-cp310-cp310-win_amd64.whl (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 5.8 MB/s eta 0:00:00
Collecting networkx
  Downloading networkx-3.2.1-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 5.8 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Collecting filelock
  Downloading filelock-3.13.3-py3-none-any.whl (11 kB)
Collecting jinja2
  Downloading Jinja2-3.1.3-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.2/133.2 kB 4.0 MB/s eta 0:00:00
Collecting sympy
  Downloading sympy-1.12-py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 5.4 MB/s eta 0:00:00
Collecting pillow!=8.3.*,>=5.3.0
  Downloading pillow-10.2.0-cp310-cp310-win_amd64.whl (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 4.8 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 5.8 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB ? eta 0:00:00
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.6-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB ? eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.3/100.3 kB 6.0 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 7.4 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 5.0 MB/s eta 0:00:00
Collecting mpmath>=0.19
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 5.6 MB/s eta 0:00:00
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torch-directml
Successfully installed MarkupSafe-2.1.5 certifi-2024.2.2 charset-normalizer-3.3.2 filelock-3.13.3 idna-3.6 jinja2-3.1.3 mpmath-1.3.0 networkx-3.2.1 numpy-1.26.4 pillow-10.2.0 requests-2.31.0 sympy-1.12 torch-2.0.0 torch-directml-0.2.0.dev230426 torchvision-0.15.1 typing-extensions-4.10.0 urllib3-2.2.1

[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\venv\Scripts\python.exe -m pip install --upgrade pip
Failed to automatically patch torch with ZLUDA. Could not find ZLUDA from PATH.
Installing clip
Installing open_clip
Installing requirements


python 3.10 düşürdüm    şimdide bu hatayı alıyorum

**Comment by mollenmest** [comment]
venv "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a
Installing requirements

 @echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--use-directml --use-zluda

call webui.bat

kodları böyle yaptğımdada bu hatayı veriyor

**Comment by lshqqytiger** [comment]
You should have only one of `--use-directml` and `--use-zluda`.
For GCN cards (~Radeon VII), add only `--use-directml`.
For other newer cards, try `--use-zluda`.

**Comment by mollenmest** [comment]
--use-zluda  bunda hata veriyor  
Amd Radeon RX6750 XT 12GB ekran kartım 


--use-directml
venv "C:\Users\dulda\sd\webui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a
Installing requirements

**Comment by mollenmest** [comment]
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
# modifed line
set COMMANDLINE_ARGS=--use-directml

call webui.bat
  bölye yaptım çalıştı teşekkürler
