### ISSUE TITLE
Inpaint simply doesn't change anything in the image

### ISSUE THREAD

**Issue by NiotGG** [lshqqytiger/stable-diffusion-webui-directml#434]
### Checklist

- [x] The issue exists after disabling all extensions
- [x] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [x] The issue exists in the current version of the webui
- [x] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Inpaint simply doesn't change anything in the image

### Steps to reproduce the problem

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/43074514/1110e3cc-b911-45db-a391-e4c9968f3b87)

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/43074514/60347b47-4cbb-4457-87c8-db378780a1ee)

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/43074514/160d8237-1439-4cfa-80f8-f914fc706462)

### What should have happened?

should put a bow tie on the man in the image

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-03-31-19-15.json](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/14817351/sysinfo-2024-03-31-19-15.json)

### Console logs

```Shell
2024-03-31 16:06:38,057 - ControlNet - INFO - unit_separate = False, style_align = False| 1/26 [00:01<00:40,  1.61s/it]
2024-03-31 16:06:38,241 - ControlNet - WARNING - Unable to determine version for ControlNet model 'diffusion_pytorch_model [458b7f40]'.
2024-03-31 16:06:38,242 - ControlNet - INFO - Loading model from cache: diffusion_pytorch_model [458b7f40]
2024-03-31 16:06:38,280 - ControlNet - INFO - Using preprocessor: openpose_full
2024-03-31 16:06:38,280 - ControlNet - INFO - preprocessor resolution = 512
2024-03-31 16:06:38,319 - ControlNet - INFO - ControlNet Hooked - Time = 0.26602983474731445
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:46<00:00,  3.61s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:47<00:00,  3.62s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 26/26 [01:33<00:00,  3.59s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 26/26 [01:33<00:00,  3.61s/it]
```

**Comment by erixwd** [comment]
What GPU and arguments are you using?

Try adding `--no-half --opt-sub-quad-attention` in the arguments. Solved the issue for me.

**Comment by erixwd** [comment]
What arguments are you using?

Try adding --no-half --opt-sub-quad-attention in the arguments. Solved the issue for me.

**Comment by NiotGG** [comment]
> What arguments are you using?
> 
> Try adding --no-half --opt-sub-quad-attention in the arguments. Solved the issue for me.

This worked perfectly for me, thank you very much.
