### ISSUE TITLE
[Bug]:  Couldn't find Stable Diffusion in any of:

### ISSUE THREAD

**Issue by metekymkc** [lshqqytiger/stable-diffusion-webui-directml#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I tried launching webui.bat, but when I do it just gives me this error message.

### Steps to reproduce the problem

1. Go to Stable Diffusion installation path
2. Press webui.bat or webui-user,bat
3. error

### What should have happened?

Well I guess it should have worked.

### Commit where the problem happens

f64ad25386ad77d1e07986a204dac923b9a46894

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### List of extensions

no

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\AI\amd\stable-diffusion-webui-directml\launch.py", line 377, in <module>
    start()
  File "D:\AI\amd\stable-diffusion-webui-directml\launch.py", line 368, in start
    import webui
  File "D:\AI\amd\stable-diffusion-webui-directml\webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "D:\AI\amd\stable-diffusion-webui-directml\modules\paths.py", line 26, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['D:\\AI\\amd\\stable-diffusion-webui-directml\\repositories/stable-diffusion-stability-ai', '.', 'D:\\AI\\amd']
```

### Additional information

pls help.

**Comment by Sourgin** [comment]
Delete folder, install again following the guide.
