### ISSUE TITLE
only coming 6 its 

### ISSUE THREAD

**Issue by neonarc4** [lshqqytiger/stable-diffusion-webui-directml#459]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

text to image only show 2its lamo 
### What should have happened?

should be 23 its on rx 7900 xtx sad

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome, Brave, Other

### Sysinfo

latest 

### Console logs

```Shell
To create a public link, set `share=True` in `launch()`.
Startup time: 434.3s (prepare environment: 53.8s, initialize shared: 3.2s, other imports: 0.2s, list SD models: 381.9s, load scripts: 2.3s, create ui: 0.7s, gradio launch: 0.4s).
6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa
Loading weights [6ce0161689] from X:\Nebula\dml\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: X:\Nebula\dml\stable-diffusion-webui-directml\configs\v1-inference.yaml
X:\Nebula\dml\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Applying attention optimization: InvokeAI... done.
Model loaded in 11.2s (calculate hash: 5.8s, create model: 0.4s, apply weights to model: 3.6s, apply half(): 0.4s, calculate empty prompt: 0.8s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:44<00:00,  2.22s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:40<00:00,  2.01s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:43<00:00,  2.19s/it]
Total progress:  35%|███████████████████████▍                                           | 7/20 [00:42<01:18,  6.06s/it]
Total progress:  35%|███████████████████████▍                                           | 7/20 [00:42<01:20,  6.21s/it]
```

**Comment by lshqqytiger** [comment]
What resolution, which sampler, backend, settings?

**Comment by neonarc4** [comment]
```js
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--use-directml

call webui.bat

```

**Comment by neonarc4** [comment]
https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/140290288/50947f60-8720-450c-b7ab-ec91b3002b6b

now it coming 5-6 but it suck if u see shark amd they have 24 its on amd

**Comment by lshqqytiger** [comment]
You can't reach 23it/s with DirectML.
Change these settings:
```
precision: fp16 (half)
use autocast
attention method: scaled-dot product (sdp) or sub-quadratic
```
You can reach about 5it/s with the optimized settings.
By the way, you can reach 17it/s ~ 23it/s with ZLUDA, and 27~28it/s with Olive (need conversion/optimization).

**Comment by neonarc4** [comment]
where i can change these setting ?

**Comment by lshqqytiger** [comment]
Go to system tab

**Comment by neonarc4** [comment]
its already set to fp 16 
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/140290288/fe4872e5-3fac-43eb-9946-09e568ea5468)

**Comment by neonarc4** [comment]
cant found those settings

**Comment by neonarc4** [comment]
> autocast
found 1 cross attention
u mean by this 
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/140290288/28e50b45-672e-48cf-a3ba-f9e1b84f2e53)

**Comment by neonarc4** [comment]
@lshqqytiger  when i apply oliva i get this error 
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/140290288/32f4be64-a38b-419f-aa3d-e1565a02c36d)

**Comment by neonarc4** [comment]
i will close it for now i will test it little bit more before reopening thnx alot ishqqy

**Comment by neonarc4** [comment]
zelda is just frozen 

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/140290288/c1e77c88-ae4d-42ac-bbab-a62ad24135ef)

**Comment by neonarc4** [comment]
@lshqqytiger 
https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/140290288/91a5b0a7-318e-4325-b0fa-36d7dafa7a81

**Comment by neonarc4** [comment]
https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/140290288/48f254d3-0938-478c-bd65-7560199bdbff

@lshqqytiger

**Comment by lshqqytiger** [comment]
ZLUDA has to compile GPU codes and make caches at the first launch. It will take ~20 minutes.

**Comment by neonarc4** [comment]
zesus lol i should go with onnx then

**Comment by neonarc4** [comment]
@lshqqytiger  i forget to say thank u again 

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/140290288/9bee2fb6-d085-48f5-ac64-579a2338f729)
i really getting good result now
