### ISSUE TITLE
Bug]: Error with webui-user

### ISSUE THREAD

**Issue by Winnougan** [lshqqytiger/stable-diffusion-webui-directml#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I followed the steps provided, and tried to launch the webui-user bat file and got the following error (see below)

### Steps to reproduce the problem

venv "E:\SD\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
==============================================================================================================
INCOMPATIBLE PYTHON VERSION

This program is tested with 3.10.6 Python, but you have 3.11.2.
If you encounter an error with "RuntimeError: Couldn't install torch." message,
or any other error regarding unsuccessful package (library) installation,
please downgrade (or upgrade) to the latest version of 3.10 Python
and delete current Python and "venv" folder in WebUI's directory.

You can download 3.10 Python from here: https://www.python.org/downloads/release/python-3109/

Alternatively, use a binary release of WebUI: https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases

Use --skip-python-version-check to suppress this warning.
==============================================================================================================
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
Commit hash: f64ad25386ad77d1e07986a204dac923b9a46894
Installing torch and torchvision
ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: 2.0.0)
ERROR: No matching distribution found for torch==1.13.1

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: E:\SD\stable-diffusion-webui-directml\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "E:\SD\stable-diffusion-webui-directml\launch.py", line 376, in <module>
    prepare_environment()
  File "E:\SD\stable-diffusion-webui-directml\launch.py", line 285, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "E:\SD\stable-diffusion-webui-directml\launch.py", line 97, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "E:\SD\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install torch==1.13.1 torchvision==0.14.1 torch-directml
Error code: 1
Press any key to continue . . .

### What should have happened?

Pytorch should have installed - could not fetch it.

### Commit where the problem happens

Happens when I try to launch webui-user

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
venv "E:\SD\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
==============================================================================================================
INCOMPATIBLE PYTHON VERSION

This program is tested with 3.10.6 Python, but you have 3.11.2.
If you encounter an error with "RuntimeError: Couldn't install torch." message,
or any other error regarding unsuccessful package (library) installation,
please downgrade (or upgrade) to the latest version of 3.10 Python
and delete current Python and "venv" folder in WebUI's directory.

You can download 3.10 Python from here: https://www.python.org/downloads/release/python-3109/

Alternatively, use a binary release of WebUI: https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases

Use --skip-python-version-check to suppress this warning.
==============================================================================================================
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
Commit hash: f64ad25386ad77d1e07986a204dac923b9a46894
Installing torch and torchvision
ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: 2.0.0)
ERROR: No matching distribution found for torch==1.13.1

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: E:\SD\stable-diffusion-webui-directml\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "E:\SD\stable-diffusion-webui-directml\launch.py", line 376, in <module>
    prepare_environment()
  File "E:\SD\stable-diffusion-webui-directml\launch.py", line 285, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "E:\SD\stable-diffusion-webui-directml\launch.py", line 97, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "E:\SD\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install torch==1.13.1 torchvision==0.14.1 torch-directml
Error code: 1
Press any key to continue . . .
```

**Comment by lshqqytiger** [comment]
Try again with Python 3.10.x not 3.11.

**Comment by Winnougan** [comment]
Thank you, doing it now
