### ISSUE TITLE
[Bug]: Upscaling errors with the last update

### ISSUE THREAD

**Issue by dieselinoo** [lshqqytiger/stable-diffusion-webui-directml#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Batch process upscaling using R-ESGRAN Anime gives errors

### Steps to reproduce the problem

1. Go to the extras tab
2. Go to batch processing
3. Add images and choose R-ESGRAN Anime

### What should have happened?

It should have upscaled the images without giving me any errors

### Commit where the problem happens

41d5450a0a559469b354fd56cac0fe1ab3cf2f40

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--opt-sub-quad-attention --no-half
```

### List of extensions

No

### Console logs

```Shell
https://pastebin.com/GPg2pxNv
```

### Additional information

Prior to the latest update this has always worked and I never had any issues  before.

**Comment by lshqqytiger** [comment]
Found same issue.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8952
