### ISSUE TITLE
[Bug]: Unable to install dependencies.gfpgan\clip\openclip

### ISSUE THREAD

**Issue by Kuron88** [lshqqytiger/stable-diffusion-webui-directml#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Unable to install dependencies
gfpgan_package = os.environ.get('GFPGAN_PACKAGE', "git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379")
clip_package = os.environ.get('CLIP_PACKAGE', "git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1")
openclip_package = os.environ.get('OPENCLIP_PACKAGE', "git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b")

### Steps to reproduce the problem

After the git source code, run webui-user.bat and it cannot be installed. Open the launch.py and find that the links of these 3 dependent files are not found.

### What should have happened?

Normally, these dependencies should be installed sequentially

### Commit where the problem happens

Run:webui-user.bat

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sub-quad-attention --no-half --precision full --lowvram
```

### List of extensions

NO

### Console logs

```Shell
Installing gfpgan
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-directml\launch.py", line 352, in <module>
    prepare_environment()
  File "D:\stable-diffusion-webui-directml\launch.py", line 262, in prepare_environment
    run_pip(f"install {gfpgan_package}", "gfpgan")
  File "D:\stable-diffusion-webui-directml\launch.py", line 129, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "D:\stable-diffusion-webui-directml\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install gfpgan.
Command: "D:\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379
  Cloning https://github.com/TencentARC/GFPGAN.git (to revision 8d2447a2d918f8eba5a4a01463fd48e45126a379) to c:\users\kuron\appdata\local\temp\pip-req-build-a553kloq

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\kuron\AppData\Local\Temp\pip-req-build-a553kloq'
  fatal: unable to access 'https://github.com/TencentARC/GFPGAN.git/': Failed to connect to github.com port 443 after 21044 ms: Couldn't connect to server
  error: subprocess-exited-with-error

  git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\kuron\AppData\Local\Temp\pip-req-build-a553kloq' did not run successfully.
  exit code: 128

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\kuron\AppData\Local\Temp\pip-req-build-a553kloq' did not run successfully.
exit code: 128

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Additional information

_No response_

**Comment by Kuron88** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and checked the recent builds/commits
> 
> ### What happened?
> Unable to install dependencies gfpgan_package = os.environ.get('GFPGAN_PACKAGE', "git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379") clip_package = os.environ.get('CLIP_PACKAGE', "git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1") openclip_package = os.environ.get('OPENCLIP_PACKAGE', "git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b")
> 
> ### Steps to reproduce the problem
> After the git source code, run webui-user.bat and it cannot be installed. Open the launch.py and find that the links of these 3 dependent files are not found.
> 
> ### What should have happened?
> Normally, these dependencies should be installed sequentially
> 
> ### Commit where the problem happens
> Run:webui-user.bat
> 
> ### What platforms do you use to access the UI ?
> Windows
> 
> ### What browsers do you use to access the UI ?
> Google Chrome
> 
> ### Command Line Arguments
> ```shell
> --opt-sub-quad-attention --no-half --precision full --lowvram
> ```
> 
> ### List of extensions
> NO
> 
> ### Console logs
> ```shell
> Installing gfpgan
> Traceback (most recent call last):
>   File "D:\stable-diffusion-webui-directml\launch.py", line 352, in <module>
>     prepare_environment()
>   File "D:\stable-diffusion-webui-directml\launch.py", line 262, in prepare_environment
>     run_pip(f"install {gfpgan_package}", "gfpgan")
>   File "D:\stable-diffusion-webui-directml\launch.py", line 129, in run_pip
>     return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
>   File "D:\stable-diffusion-webui-directml\launch.py", line 97, in run
>     raise RuntimeError(message)
> RuntimeError: Couldn't install gfpgan.
> Command: "D:\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 --prefer-binary
> Error code: 1
> stdout: Collecting git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379
>   Cloning https://github.com/TencentARC/GFPGAN.git (to revision 8d2447a2d918f8eba5a4a01463fd48e45126a379) to c:\users\kuron\appdata\local\temp\pip-req-build-a553kloq
> 
> stderr:   Running command git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\kuron\AppData\Local\Temp\pip-req-build-a553kloq'
>   fatal: unable to access 'https://github.com/TencentARC/GFPGAN.git/': Failed to connect to github.com port 443 after 21044 ms: Couldn't connect to server
>   error: subprocess-exited-with-error
> 
>   git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\kuron\AppData\Local\Temp\pip-req-build-a553kloq' did not run successfully.
>   exit code: 128
> 
>   See above for output.
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\kuron\AppData\Local\Temp\pip-req-build-a553kloq' did not run successfully.
> exit code: 128
> 
> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> ### Additional information
> 
> _No response_
> ```

**Comment by Fox-dream** [comment]
I have the same problem AS [above.](url)
![Snipaste_2023-04-07_11-38-01](https://user-images.githubusercontent.com/36251457/230536132-da02d789-e562-40ed-a83f-6392cb1cf3fb.png)
