### ISSUE TITLE
[Bug]: Blue Screen with VRAM memory error after trying to generate photo 'Torch not compiled with CUDA enabled', memory monitor disabled

### ISSUE THREAD

**Issue by Griphen116** [lshqqytiger/stable-diffusion-webui-directml#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Trying to run on a laptop with a Ryzen 2700U with Vega10 graphics. When starting up the webui-user bat this is the message that appeared: 
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
![image](https://user-images.githubusercontent.com/11777204/219538206-23a66b7e-0d30-4d6b-93c0-90eae47efa84.png)

When trying to generate a test photo, i immediately crashed to a windows bluescreen with a VRAM memory error.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Not crash

### Commit where the problem happens

https://github.com/lshqqytiger/stable-diffusion-webui-directml

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
venv "C:\StableDifusion\stable-diffusion-directml\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: a0f4cd6fdd2b7ef3e2b666694f1a1ca13ee17066
Installing requirements for Web UI
Launching Web UI with arguments:
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [543bcbc212] from C:\StableDifusion\stable-diffusion-directml\stable-diffusion-webui-directml\models\Stable-diffusion\Anything-V3.0.ckpt
Creating model from config: C:\StableDifusion\stable-diffusion-directml\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 16.1s (load weights from disk: 10.5s, create model: 0.7s, apply weights to model: 1.2s, apply half(): 0.9s, move model to device: 2.7s).
Running on local URL:  http://127.0.0.1:7860
```

**Comment by lshqqytiger** [comment]
It seems to be a graphic driver issue. Please update or reinstall your gpu driver to latest one, and try again.

**Comment by lshqqytiger** [comment]
I found same issue from `microsoft/DirectML`. Increase your dedicated GPU memory or wait for update.
https://github.com/microsoft/DirectML/issues/379

**Comment by brianorca** [comment]
I tried latest 23.2.1 AMD driver 2023-Feb-14 with MLIR and maxed out the GPU HBCC memory sharing to 24GB. (On my Vega 56 8GB) - still getting the blue screen, or the memory error if I turn HBCC sharing off. *sigh* Back to Shark, I guess.

**Comment by TomArrow** [comment]
Also getting Bluescreen, AMD 5700G here. Windows 10, pretty recent video driver (last month or so). Task manager shows 512 MB dedicated memory and up to 16GB shared. When I start generation I see the shared memory usage going up and when it reaches roughly 7 or 8 GB (I might be remembering wrong tho bc it happens so fast), I get the BSOD. 

The BSOD is a bugcheck code 370 (VIDEO_MEMORY_MANAGEMENT_INTERNAL) with a parameter 0x36 which according to microsoft means "The paging request failed on a paging packet or  device resume that was previously marked as unrecoverable, and was  expected to succeed subsequent calls." (see: https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x10e---video-memory-management-internal ). No idea what it means.

I could try this HBCC stuff or whatever but no idea where to set it up in the AMD Adrenalin settings. I tried to search for it but am not seeing it.

**Comment by injaan** [comment]
Same issue on AMD Radeon Vega Frontier edition with latest adrenaline driver 23.7.2

**Comment by HydraOrc** [comment]
I have noticed this is happening only on consecutive generations. Restarting the UI each time helps...
