### ISSUE TITLE
[Bug]:  assert sd_path is not None

### ISSUE THREAD

**Issue by Yamayukii1** [lshqqytiger/stable-diffusion-webui-directml#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I follow the Installation but i can't work.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

try a lot no help

### Commit where the problem happens

.

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
no
```

### List of extensions

no

### Console logs

```Shell
venv "F:\stable-diffusion-webui-directml-master\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-directml-master\launch.py", line 353, in <module>
    start()
  File "F:\stable-diffusion-webui-directml-master\launch.py", line 344, in start
    import webui
  File "F:\stable-diffusion-webui-directml-master\webui.py", line 16, in <module>
    from modules import paths, timer, import_hook, errors
  File "F:\stable-diffusion-webui-directml-master\modules\paths.py", line 19, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['F:\\stable-diffusion-webui-directml-master\\repositories/stable-diffusion-stability-ai', '.', 'F:\\']
```

**Comment by VileDemon07** [comment]
Hi lshqqytiger,
I have the same problem:
`
  File "C:\StableDiff\stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "C:\StableDiff\stable-diffusion-webui-directml\launch.py", line 344, in start
    import webui
  File "C:\StableDiff\stable-diffusion-webui-directml\webui.py", line 16, in <module>
    from modules import paths, timer, import_hook, errors
  File "C:\StableDiff\stable-diffusion-webui-directml\modules\paths.py", line 19, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['C:\\StableDiff\\stable-diffusion-webui-directml\\repositories/stable-diffusion-stability-ai', '.', 'C:\\StableDiff']
`
The \stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai folder is empty

I did exactly, what was written on Automatic1111 Wiki:
`git clone https://github.com/lshqqytiger/stable-diffusion-webui-directml && cd stable-diffusion-webui-directml && git submodule init && git submodule update`

So I have cloned as you said, but still got the same error...
