### ISSUE TITLE
[Bug]: Unable to load the model with the. safensere suffix

### ISSUE THREAD

**Issue by BMud** [lshqqytiger/stable-diffusion-webui-directml#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

An exception occurs when a model with the suffix. safesensors is in the model library.Expecting value: line 1 column 1 (char 0)

### Steps to reproduce the problem

safesensors in model

### What should have happened?

Does the current version temporarily not support the model with the suffix. safesensors？

### Commit where the problem happens

choose model

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
ython launch.py --precision full --no-half --lowvram --share
```

### List of extensions

none

### Console logs

```Shell
Expecting value: line 1 column 1 (char 0)
```

**Comment by EmKs** [comment]
I also encountered this problem and spent a whole day before finally finding the cause. As a Chinese user accessing GitHub, sometimes I need to use a proxy, which causes this problem. You just need to turn off your proxy to solve it. I don't know if this can help you.

**Comment by BMud** [comment]
> 我也遇到了这个问题，折腾了一整天，终于找到原因了。作为中国用户访问GitHub，有时候需要使用代理，才会出现这个问题。您只需要关闭代理即可解决。我不知道这是否可以帮助你。

我确定我没有使用代理，您可以正常加载.safetensors后缀的模型吗？当我的模型库中只有.ckpt时一切正常，但是一旦放入了.safetensors的模型，就会出现错误。

**Comment by EmKs** [comment]
可以的，我下载了很多次，整了很多遍，结果发现是梯子导致加载失败，在AUTOMATIC1111原项目里也有人提到这个问题，下边还有另一种解决办法，就是在COMMANDLINE ARGS里加上 --no-gradio-queue 你可以试一下
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9150

**Comment by Miraihi** [comment]
It's `.safetensors` not `.safesensors`
