### ISSUE TITLE
[Bug]: Entry point for LoadLibraryW not found in api-ms-win-core-libraryloader-l1-2-1.dll

### ISSUE THREAD

**Issue by HydraOrc** [lshqqytiger/stable-diffusion-webui-directml#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Entry point for LoadLibraryW not found in api-ms-win-core-libraryloader-l1-2-1.dll

### Steps to reproduce the problem

Launch webui-user.bat

### What should have happened?

No error

### Commit where the problem happens

ae337fa39b6d4598b377ff312c53b14c15142331

### What platforms do you use to access the UI ?

Windows

### Command Line Arguments

```Shell
None
```

### List of extensions

None

### Console logs

```Shell
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "launch.py", line 353, in <module>
    start()
  File "launch.py", line 344, in start
    import webui
  File "K:\stable-diffusion-webui-directml\webui.py", line 31, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "K:\stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints
.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "K:\stable-diffusion-webui-directml\modules\shared.py", line 12, in <modu
le>
    import modules.interrogate
  File "K:\stable-diffusion-webui-directml\modules\interrogate.py", line 15, in
<module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "K:\stable-diffusion-webui-directml\modules\devices.py", line 4, in <modu
le>
    import torch_directml
  File "K:\stable-diffusion-webui-directml\venv\lib\site-packages\torch_directml
\__init__.py", line 13, in <module>
    torch.ops.load_library(directml_dll)
  File "K:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_ops.py"
, line 573, in load_library
    ctypes.CDLL(path)
  File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 373, in __init__

    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'K:\stable-diffusion-webui-directml\ven
v\Lib\site-packages\torch_directml\DirectML.dll' (or one of its dependencies). T
ry using the full path with constructor syntax.
```

### Additional information

Can maybe somebody share the working api-ms-win-core-libraryloader-l1-2-1.dll ?

**Comment by HydraOrc** [comment]
> DirectML.dll

DirectML.dll is present, I think the issue is in using LoadLibraryW. Maybe replace it with LoadLibrary?

**Comment by lshqqytiger** [comment]
`LoadLibraryW` seems to be [correct](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw).
Reinstall python to version 3.10.x and try again.

**Comment by HydraOrc** [comment]
It does not start with 3.10 at all throwing some hex error code, the closest version I got it to at least try to start is 3.8. Can somebody rewrite using LoadLibrary? I am not familiar with the languages in this repository to do myself.

**Comment by lshqqytiger** [comment]
Which is calling `LoadLibraryW` is the Python.
Python tried to load DirectML.dll using `LoadLibraryW`, but it is failing because there is no `LoadLibraryW` in api-ms-win-core-libraryloader-l1-2-1.dll.
