### ISSUE TITLE
[Bug]: Torch and Torchvision wont install

### ISSUE THREAD

**Issue by vwitem21** [lshqqytiger/stable-diffusion-webui-directml#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Stable Diffusion Wont Install Torch

### Steps to reproduce the problem

1. Launch webui-user.bat

### What should have happened?

It Should install the Torch

### Commit where the problem happens

Commit hash: ae337fa39b6d4598b377ff312c53b14c15142331

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
venv "C:\Users\Username\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Commit hash: ae337fa39b6d4598b377ff312c53b14c15142331
Installing torch and torchvision
C:\Users\vwite\stable-diffusion-webui-directml\venv\Scripts\python.exe: No module named pip
Traceback (most recent call last):
  File "C:\Users\Username\stable-diffusion-webui-directml\launch.py", line 352, in <module>
    prepare_environment()
  File "C:\Users\Username\stable-diffusion-webui-directml\launch.py", line 259, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "C:\Users\Username\stable-diffusion-webui-directml\launch.py", line 81, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "C:\Users\Username\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install torch==1.13.1 torchvision==0.14.1 torch-directml
Error code: 1
```

**Comment by lshqqytiger** [comment]
Make sure pip installed and is available.

**Comment by Freddy-Kong** [comment]
running into the same problem after the latest pull:

when starting webui:

import torch_directml_native
ImportError: DLL load failed while importing torch_directml_native: The specified procedure could not be found.

**Comment by jolene00negative** [comment]
I just started having a similar problem

    import torch_directml_native
ImportError: DLL load failed while importing torch_directml_native: The specified procedure could not be found.

**Comment by GREG114** [comment]
> 

got it too, I just reinstall my windows, it been ok before,don't know why

**Comment by painzzzzz** [comment]
did anyone find the solution for this?

**Comment by Freddy-Kong** [comment]
i deleted venv, updated python to 3.10.10, fixed paths, and it worked.

**Comment by kongfu-cat** [comment]
some problem, it worked after I removed the "torch-directml" and "torch" packages from the "venv/Lib/site-packages" directory

**Comment by linhnapt** [comment]
> i deleted venv, updated python to 3.10.10, fixed paths, and it worked.

mee too, and it work thank you
