### ISSUE TITLE
[Bug]: Importing a Style doesn't update the Negative Prompts token count.

### ISSUE THREAD

**Issue by brknsoul** [lshqqytiger/stable-diffusion-webui-directml#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When importing a saved Style, the Negative Prompts token count isn't updated and doesn't apply to generations unless the Negative Prompt box is changed.

### Steps to reproduce the problem

Create a prompt and a negative prompt, save the style, restart the server/client (or reload the UI), load saved style.

### What should have happened?

While it seems the Positive Prompt token count is updated, the negative isn't.

### Commit where the problem happens

fd59537d

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-split-attention --disable-nan-check --medvram --always-batch-cond-uncond --opt-sub-quad-attention --no-half-vae
```

### List of extensions

![image](https://user-images.githubusercontent.com/1969381/234484189-1b642178-386d-4ed3-9957-d648bc74ab8c.png)

### Console logs

```Shell
n/a
```

**Comment by Miraihi** [comment]
Happened to me. This is caused by webui-state extension.
